// Plain-text glossary for GCSE Maths.
// Each entry is rendered server-side at /glossary and /glossary/[term].

export type GlossaryCategory =
  | 'Command Words'
  | 'Number'
  | 'Algebra'
  | 'Geometry'
  | 'Statistics & Probability'

export interface GlossaryEntry {
  slug: string
  term: string
  category: GlossaryCategory
  short: string
  long: string
  example?: string
  confusion?: string
  relatedTopics?: Array<{ label: string; href: string }>
  related?: string[] // related glossary slugs
}

const E = (e: GlossaryEntry): GlossaryEntry => e

export const GLOSSARY: GlossaryEntry[] = [
  // ── COMMAND WORDS ─────────────────────────────────────────
  E({
    slug: 'show-that',
    term: 'Show that',
    category: 'Command Words',
    short: 'You must demonstrate the result starting from given values — the answer is provided, your job is the working.',
    long: '"Show that" questions give you both the start and the end. You must produce every step that connects the two. Starting from the answer and working backwards earns zero marks. The whole credit is in the method.',
    example: 'Show that 3 × (2 + 5) = 21. You must write: 3 × (2 + 5) = 3 × 7 = 21. Not just "= 21".',
    confusion: 'Often mistaken for "Prove". "Show that" wants numerical or algebraic demonstration with given values. "Prove" wants a general argument that works for all cases.',
    relatedTopics: [{ label: 'Algebraic proof', href: '/topics/algebraic-proof' }],
    related: ['prove', 'hence', 'verify'],
  }),
  E({
    slug: 'prove',
    term: 'Prove',
    category: 'Command Words',
    short: 'Demonstrate that a statement is always true, using general (often algebraic) reasoning, not specific numbers.',
    long: 'A "prove" question requires a watertight argument that holds for every case, not just one example. Substituting numbers is not a proof — it is an example. Use letters (n for any integer, 2n for any even number, 2n+1 for any odd) and reason symbolically.',
    example: 'Prove that the sum of two consecutive integers is odd. Let the integers be n and n+1. Their sum is 2n+1, which is odd by definition. QED.',
    confusion: '"Show that" usually involves substituting specific numbers. "Prove" needs a general argument.',
    relatedTopics: [{ label: 'Algebraic proof', href: '/topics/algebraic-proof' }],
    related: ['show-that', 'hence'],
  }),
  E({
    slug: 'hence',
    term: 'Hence',
    category: 'Command Words',
    short: 'Use the previous part of the question to answer this part. You must connect to what you have already found.',
    long: '"Hence" is a load-bearing word. The mark scheme expects you to reuse a result from earlier in the same question. Solving the new part from scratch with a different method usually scores zero, even if the final answer is correct.',
    example: 'After Part (a) you have factorised x² − 5x + 6 = (x−2)(x−3). Part (b) says "Hence solve x² − 5x + 6 = 0." Use your factors: x = 2 or x = 3.',
    confusion: 'Students often ignore "hence" and start fresh with the quadratic formula. That can lose all the marks.',
    related: ['hence-or-otherwise', 'show-that'],
  }),
  E({
    slug: 'hence-or-otherwise',
    term: 'Hence or otherwise',
    category: 'Command Words',
    short: '"Hence" gives the easy path. "Otherwise" lets you use any valid method. You earn the same marks either way — but easier with hence.',
    long: 'When you see "hence or otherwise", the previous part of the question hints at the easiest method. You are allowed to use a different approach, but if "hence" works, use it — it is usually the fastest. "Otherwise" is the safety net if you cannot see the connection.',
    example: 'Hence or otherwise solve 2sin(x) + 1 = 0. Hence: rearrange to sin(x) = −½ and use known angles. Otherwise: any valid trig method.',
    confusion: 'Many students think "otherwise" forbids using the previous answer — it does not. It just permits a different method.',
    related: ['hence', 'show-that'],
  }),
  E({
    slug: 'estimate',
    term: 'Estimate',
    category: 'Command Words',
    short: 'Round every value to 1 significant figure, then calculate. Do not use the exact values.',
    long: 'In maths exams, "estimate" almost always means: round everything to 1 significant figure and then calculate. Using the exact numbers loses every mark on the question, even if your final answer is close.',
    example: 'Estimate 5.84 × 19.7. Round to 1 s.f.: 6 × 20 = 120. Answer: 120.',
    confusion: 'Students round to 2 or 3 s.f. — losing marks because the mark scheme demands 1 s.f. for an estimate.',
    relatedTopics: [{ label: 'Bounds and error intervals', href: '/topics/bounds-and-error-intervals' }],
    related: ['calculate', 'work-out'],
  }),
  E({
    slug: 'calculate',
    term: 'Calculate',
    category: 'Command Words',
    short: 'Work out an exact value using the given numbers. Show your method.',
    long: '"Calculate" expects an exact answer to the required precision (rounding only at the final step). Show every working step — the marks are usually split between method and final answer.',
    example: 'Calculate 4 × (3 + 5). Method: 4 × 8 = 32. Answer: 32.',
    confusion: 'Skipping the working — even with a correct answer, you can lose method marks.',
    related: ['work-out', 'find'],
  }),
  E({
    slug: 'find',
    term: 'Find',
    category: 'Command Words',
    short: 'Determine the value or solution. Working not always required, but always shown by competent students.',
    long: '"Find" is the most general command word. It can be one mark (one-line answer) or several marks (multi-step). Always check the mark allocation: 1 mark = answer only; 2+ marks = show working.',
    example: 'Find the value of x when 3x + 7 = 22. Working: 3x = 15, x = 5.',
    related: ['calculate', 'work-out', 'solve'],
  }),
  E({
    slug: 'work-out',
    term: 'Work out',
    category: 'Command Words',
    short: 'Show how you reached the answer. Synonymous with "calculate" but emphasises the working.',
    long: '"Work out" explicitly invites you to show your method. Examiners want to award method marks. Lay your working out clearly: line by line, with the key operation on each line.',
    related: ['calculate', 'find'],
  }),
  E({
    slug: 'describe',
    term: 'Describe',
    category: 'Command Words',
    short: 'Write a complete sentence describing what was asked — usually a transformation needs every component.',
    long: 'In transformation questions, "describe fully" means you must give every required component: type (translation, reflection, rotation, enlargement), plus the necessary parameters (vector for translation; mirror line for reflection; centre, angle and direction for rotation; centre and scale factor for enlargement).',
    example: 'Describe the transformation. Answer: "A rotation of 90° clockwise about the origin." All three components: 90°, clockwise, about origin.',
    confusion: 'Missing one component (e.g. forgetting "clockwise") loses a mark.',
    relatedTopics: [{ label: 'Transformations: reflection, rotation, translation', href: '/topics/transformations-reflection-rotation-translation' }],
    related: ['explain', 'state'],
  }),
  E({
    slug: 'explain',
    term: 'Explain',
    category: 'Command Words',
    short: 'A short written statement showing why your answer is correct, using mathematical language.',
    long: '"Explain" requires a sentence, not just a calculation. The sentence must use correct mathematical vocabulary and reference the relevant rule, theorem or definition.',
    example: 'Explain why a triangle with angles 30°, 60°, 90° is a right-angled triangle. Answer: "Because one of its angles is 90°."',
    related: ['describe', 'give-reasons'],
  }),
  E({
    slug: 'give-reasons',
    term: 'Give reasons / Give a reason',
    category: 'Command Words',
    short: 'In angle and circle questions, name the theorem or rule that justifies your step.',
    long: 'When asked to give reasons, you must name the specific angle rule (e.g. "angles on a straight line sum to 180°", "alternate angles are equal", "angle at the centre is twice angle at the circumference"). Vague answers like "geometry" earn zero.',
    example: 'Find x and give a reason. "x = 60° because angles in a triangle sum to 180°."',
    confusion: 'Saying "from the diagram" or "it is obvious" earns nothing. Name the rule.',
    relatedTopics: [{ label: 'Circle theorems', href: '/topics/circle-theorems' }, { label: 'Angles basic rules and parallel lines', href: '/topics/angles-basic-rules-and-parallel-lines' }],
  }),
  E({
    slug: 'verify',
    term: 'Verify',
    category: 'Command Words',
    short: 'Substitute the given value into the equation and show that it satisfies it.',
    long: '"Verify" is gentler than "prove" or "show that". You are given a value and asked to confirm it works. Substitute it in. Show both sides simplify to the same number.',
    example: 'Verify that x = 3 satisfies x² − 9 = 0. Substitute: 3² − 9 = 9 − 9 = 0. Verified.',
    related: ['show-that', 'prove'],
  }),
  E({
    slug: 'state',
    term: 'State',
    category: 'Command Words',
    short: 'One-word or one-line answer, with no working required.',
    long: '"State" usually means a single fact or value. Over-explaining wastes time. Write the answer, move on.',
    example: 'State the y-intercept of y = 3x + 5. Answer: 5.',
    confusion: 'Students sometimes "show working" on a "state" question and waste exam time.',
  }),
  E({
    slug: 'sketch-vs-draw-vs-plot',
    term: 'Sketch vs Draw vs Plot',
    category: 'Command Words',
    short: '"Plot" needs accurate axes and exact points. "Draw" is accurate but freer. "Sketch" shows the shape and key features only.',
    long: 'These three are NOT synonyms. "Plot" demands graph paper and exact point-by-point work. "Draw" expects ruler accuracy. "Sketch" just needs a freehand curve with axes labelled and key features (intercepts, turning points, asymptotes) marked.',
    confusion: 'Treating a "sketch" like a "plot" wastes exam time. Treating a "plot" like a "sketch" loses all the marks.',
    relatedTopics: [{ label: 'Quadratic graphs', href: '/topics/quadratic-graphs' }, { label: 'Linear graphs and equation of a line', href: '/topics/linear-graphs-and-equation-of-a-line' }],
  }),
  E({
    slug: 'not-drawn-accurately',
    term: 'Not drawn accurately',
    category: 'Command Words',
    short: 'A warning that the diagram is approximate. Do NOT measure with a ruler — use the given values only.',
    long: 'When a diagram is labelled "not drawn accurately", you must rely entirely on the values printed on the diagram. Measuring an angle or length from the diagram is forbidden — the diagram is deliberately misleading.',
    confusion: 'Students measure with a ruler or protractor and use the measurement in their working. This loses every mark on the question.',
  }),

  // ── NUMBER ────────────────────────────────────────────────
  E({
    slug: 'integer',
    term: 'Integer',
    category: 'Number',
    short: 'A whole number — positive, negative or zero. No fractions or decimals.',
    long: 'The integers are: ..., −3, −2, −1, 0, 1, 2, 3, ... The set is denoted ℤ. Integers include negatives. Natural numbers are the positive integers (some definitions include 0).',
    example: '−5, 0, 7 are all integers. 2.5 and ¾ are not.',
    confusion: 'Integers are sometimes confused with natural numbers (positive integers only) or with rationals (any fraction).',
    related: ['rational', 'irrational', 'prime'],
  }),
  E({
    slug: 'rational',
    term: 'Rational number',
    category: 'Number',
    short: 'A number you can write as a fraction p/q where p and q are integers and q ≠ 0.',
    long: 'Rational numbers include every integer, every terminating decimal, and every recurring decimal. The set is denoted ℚ.',
    example: '½, −0.75, 3, 0.333... are all rational. π and √2 are not.',
    related: ['irrational', 'integer', 'surd'],
  }),
  E({
    slug: 'irrational',
    term: 'Irrational number',
    category: 'Number',
    short: 'A number that cannot be written as a fraction of two integers — its decimal goes on forever without repeating.',
    long: 'Irrational numbers include surds like √2 and constants like π. Their decimal expansions never terminate and never settle into a repeating pattern.',
    example: '√2, √3, π, e are all irrational.',
    related: ['rational', 'surd'],
  }),
  E({
    slug: 'surd',
    term: 'Surd',
    category: 'Number',
    short: 'An irrational root that cannot be simplified to a rational number, e.g. √2, √15.',
    long: 'A surd is a root of a number (usually a square root) whose value is irrational. Surds are kept in exact form rather than rounded. You can simplify, multiply and rationalise the denominator using surd rules.',
    example: '√12 simplifies to 2√3. √4 is NOT a surd because it equals 2 (rational).',
    relatedTopics: [{ label: 'Surds', href: '/topics/surds' }],
    related: ['rational', 'irrational'],
  }),
  E({
    slug: 'prime',
    term: 'Prime number',
    category: 'Number',
    short: 'A whole number greater than 1 whose only factors are 1 and itself.',
    long: 'The first primes are 2, 3, 5, 7, 11, 13, 17, 19, 23. 1 is NOT a prime. 2 is the only even prime. Every other prime is odd.',
    confusion: 'Students often include 1 as prime. By the modern definition, 1 is not prime.',
    relatedTopics: [{ label: 'Prime factorisation, HCF and LCM', href: '/topics/prime-factorisation-hcf-and-lcm' }],
    related: ['factor', 'integer'],
  }),
  E({
    slug: 'factor',
    term: 'Factor',
    category: 'Number',
    short: 'A number that divides another exactly, with no remainder.',
    long: 'The factors of 12 are 1, 2, 3, 4, 6, 12 — every number that 12 is divisible by. "Factorising" a polynomial uses the same idea: writing the polynomial as a product of simpler factors.',
    example: 'Factors of 18: 1, 2, 3, 6, 9, 18.',
    relatedTopics: [{ label: 'Prime factorisation, HCF and LCM', href: '/topics/prime-factorisation-hcf-and-lcm' }, { label: 'Factorising expressions', href: '/topics/factorising-expressions' }],
    related: ['multiple', 'prime'],
  }),
  E({
    slug: 'multiple',
    term: 'Multiple',
    category: 'Number',
    short: 'A number found by multiplying another by an integer. Multiples of 5: 5, 10, 15, 20, ...',
    long: 'Multiples extend infinitely. The lowest common multiple (LCM) of two numbers is the smallest positive integer that is a multiple of both.',
    relatedTopics: [{ label: 'Prime factorisation, HCF and LCM', href: '/topics/prime-factorisation-hcf-and-lcm' }],
    related: ['factor', 'lcm'],
  }),
  E({
    slug: 'hcf',
    term: 'HCF (Highest Common Factor)',
    category: 'Number',
    short: 'The largest number that divides exactly into two or more numbers.',
    long: 'Find by listing factors of each number, or by prime factorisation: take all primes common to both, with the lowest power. The HCF of 18 and 24 is 6.',
    example: 'HCF of 12 and 18: factors of 12 are 1,2,3,4,6,12; factors of 18 are 1,2,3,6,9,18. Common factors: 1,2,3,6. HCF = 6.',
    relatedTopics: [{ label: 'Prime factorisation, HCF and LCM', href: '/topics/prime-factorisation-hcf-and-lcm' }],
    related: ['lcm', 'factor'],
  }),
  E({
    slug: 'lcm',
    term: 'LCM (Lowest Common Multiple)',
    category: 'Number',
    short: 'The smallest positive number that is a multiple of two or more numbers.',
    long: 'Find by listing multiples of each, or by prime factorisation: take all primes that appear, with the highest power. The LCM of 4 and 6 is 12.',
    example: 'LCM of 6 and 8. Multiples of 6: 6, 12, 18, 24. Multiples of 8: 8, 16, 24. LCM = 24.',
    relatedTopics: [{ label: 'Prime factorisation, HCF and LCM', href: '/topics/prime-factorisation-hcf-and-lcm' }],
    related: ['hcf', 'multiple'],
  }),
  E({
    slug: 'reciprocal',
    term: 'Reciprocal',
    category: 'Number',
    short: 'The reciprocal of a number x is 1/x. Multiplying a number by its reciprocal gives 1.',
    long: 'The reciprocal of 4 is ¼. The reciprocal of ⅔ is 3/2. The reciprocal of 0 does not exist (division by zero is undefined).',
    example: 'Reciprocal of 5 is 1/5. Reciprocal of 2/3 is 3/2.',
    related: ['rational'],
  }),
  E({
    slug: 'standard-form',
    term: 'Standard form',
    category: 'Number',
    short: 'A way of writing very large or very small numbers as a × 10ⁿ where 1 ≤ a < 10 and n is an integer.',
    long: '300,000 in standard form is 3 × 10⁵. 0.00047 is 4.7 × 10⁻⁴. The mantissa a is always between 1 (inclusive) and 10 (exclusive).',
    example: 'Write 56,000 in standard form. 5.6 × 10⁴.',
    confusion: 'A mantissa of 0.5 × 10⁵ is NOT standard form — the mantissa must be ≥ 1.',
    relatedTopics: [{ label: 'Standard form', href: '/topics/standard-form' }],
  }),
  E({
    slug: 'significant-figure',
    term: 'Significant figure',
    category: 'Number',
    short: 'A digit that contributes to the precision of a number. Leading zeros do not count.',
    long: 'In 0.00342, the first significant figure is 3. The second is 4. The third is 2. In 1500, all four digits are significant unless the trailing zeros are placeholders. Rounding to 1 s.f. means keeping only the first non-zero digit.',
    example: '1234 to 2 s.f. is 1200. 0.0567 to 2 s.f. is 0.057.',
    related: ['decimal-place', 'estimate'],
  }),
  E({
    slug: 'decimal-place',
    term: 'Decimal place',
    category: 'Number',
    short: 'The position after the decimal point. "To 2 d.p." means two digits after the decimal point.',
    long: '3.14159 rounded to 2 d.p. is 3.14. Rounded to 3 d.p. is 3.142. Look at the next digit to decide whether to round up.',
    related: ['significant-figure'],
  }),
  E({
    slug: 'upper-bound',
    term: 'Upper bound',
    category: 'Number',
    short: 'The largest value a rounded measurement could be. For a length given as 12 cm to the nearest cm, the upper bound is 12.5 cm.',
    long: 'When a measurement is rounded, the upper bound is found by adding half the rounding unit. For 12 cm (nearest cm), upper bound = 12 + 0.5 = 12.5 cm. The upper bound itself is excluded — it is the supremum.',
    relatedTopics: [{ label: 'Bounds and error intervals', href: '/topics/bounds-and-error-intervals' }],
    related: ['lower-bound'],
  }),
  E({
    slug: 'lower-bound',
    term: 'Lower bound',
    category: 'Number',
    short: 'The smallest value a rounded measurement could be. For 12 cm to the nearest cm, the lower bound is 11.5 cm.',
    long: 'Found by subtracting half the rounding unit from the rounded value. For 12 cm (nearest cm), lower bound = 12 − 0.5 = 11.5 cm. The lower bound IS included.',
    relatedTopics: [{ label: 'Bounds and error intervals', href: '/topics/bounds-and-error-intervals' }],
    related: ['upper-bound'],
  }),

  // ── ALGEBRA ───────────────────────────────────────────────
  E({
    slug: 'expression',
    term: 'Expression',
    category: 'Algebra',
    short: 'A combination of numbers, letters and operations with no equals sign, e.g. 3x + 5.',
    long: 'An expression cannot be "solved" — it has no equation to balance. It can be simplified, expanded, factorised or substituted into.',
    example: '4x² − 7y + 3 is an expression. 4x² − 7y + 3 = 0 is an equation.',
    confusion: 'Students often try to "solve" an expression — but there is nothing to solve.',
    relatedTopics: [{ label: 'Simplifying expressions', href: '/topics/simplifying-expressions' }],
    related: ['equation', 'identity', 'formula'],
  }),
  E({
    slug: 'equation',
    term: 'Equation',
    category: 'Algebra',
    short: 'A mathematical statement with an equals sign — true for some specific value(s) of the unknown.',
    long: 'Equations are solved to find the value(s) of the unknown that make the statement true. Linear equations have one solution; quadratics have up to two; cubics up to three.',
    example: 'x + 5 = 12 is an equation. It is true when x = 7 and false otherwise.',
    relatedTopics: [{ label: 'Solving linear equations', href: '/topics/solving-linear-equations' }],
    related: ['expression', 'identity', 'inequality'],
  }),
  E({
    slug: 'identity',
    term: 'Identity',
    category: 'Algebra',
    short: 'A statement that is true for every value of the variable. Uses the ≡ symbol.',
    long: 'An identity, unlike an equation, is true for all values of the variable. (x + 1)² ≡ x² + 2x + 1 is an identity because it holds for every x.',
    example: '2(x + 3) ≡ 2x + 6 is an identity.',
    confusion: 'An equation x + 5 = 12 is true only for x = 7. An identity is true everywhere.',
    related: ['equation', 'expression'],
  }),
  E({
    slug: 'inequality',
    term: 'Inequality',
    category: 'Algebra',
    short: 'A statement using <, >, ≤ or ≥ instead of =, expressing a range of valid values.',
    long: 'Solve inequalities like equations, except: multiplying or dividing both sides by a negative number flips the direction of the inequality.',
    example: '2x + 3 < 11 → 2x < 8 → x < 4.',
    relatedTopics: [{ label: 'Solving inequalities', href: '/topics/solving-inequalities' }],
    related: ['equation'],
  }),
  E({
    slug: 'coefficient',
    term: 'Coefficient',
    category: 'Algebra',
    short: 'The number multiplying a variable, e.g. in 4x the coefficient is 4.',
    long: 'In 3x² − 5x + 7: the coefficient of x² is 3, the coefficient of x is −5, and 7 is the constant term. Signs are part of the coefficient.',
    example: 'In 2y − 9, the coefficient of y is 2.',
  }),
  E({
    slug: 'expand',
    term: 'Expand',
    category: 'Algebra',
    short: 'Multiply out brackets so that no brackets remain.',
    long: '"Expand and simplify" means: multiply out, then collect like terms. Single brackets use the distributive law. Double brackets use FOIL (First, Outer, Inner, Last) or the grid method.',
    example: '3(x + 4) = 3x + 12. (x + 2)(x + 3) = x² + 5x + 6.',
    relatedTopics: [{ label: 'Expanding brackets', href: '/topics/expanding-brackets' }],
    related: ['factorise', 'simplify'],
  }),
  E({
    slug: 'factorise',
    term: 'Factorise',
    category: 'Algebra',
    short: 'Rewrite an expression as a product of its factors — the opposite of expanding.',
    long: 'Factorising can mean: taking out a common factor (4x + 8 = 4(x + 2)); factorising a quadratic into two brackets (x² + 5x + 6 = (x + 2)(x + 3)); or using the difference of two squares (x² − 9 = (x − 3)(x + 3)).',
    example: 'Factorise x² + 7x + 12 = (x + 3)(x + 4).',
    relatedTopics: [{ label: 'Factorising expressions', href: '/topics/factorising-expressions' }, { label: 'Solving quadratic equations: factorising', href: '/topics/solving-quadratic-equations-factorising' }],
    related: ['expand'],
  }),
  E({
    slug: 'gradient',
    term: 'Gradient',
    category: 'Algebra',
    short: 'The steepness of a line. Calculated as (change in y) ÷ (change in x), often written m.',
    long: 'A positive gradient slopes upward left-to-right; negative slopes downward. Horizontal lines have gradient 0; vertical lines have undefined gradient.',
    example: 'Line passing through (1, 2) and (3, 8). Gradient = (8 − 2) ÷ (3 − 1) = 3.',
    relatedTopics: [{ label: 'Linear graphs and equation of a line', href: '/topics/linear-graphs-and-equation-of-a-line' }],
    related: ['y-intercept'],
  }),
  E({
    slug: 'y-intercept',
    term: 'y-intercept',
    category: 'Algebra',
    short: 'The point where a line or curve crosses the y-axis. Found by setting x = 0.',
    long: 'In the form y = mx + c, the y-intercept is c. The corresponding coordinate is (0, c).',
    example: 'y = 2x + 5. y-intercept is 5; the line crosses the y-axis at (0, 5).',
    relatedTopics: [{ label: 'Linear graphs and equation of a line', href: '/topics/linear-graphs-and-equation-of-a-line' }],
    related: ['gradient'],
  }),
  E({
    slug: 'discriminant',
    term: 'Discriminant',
    category: 'Algebra',
    short: 'The quantity b² − 4ac inside the quadratic formula. Determines how many real roots a quadratic has.',
    long: 'For ax² + bx + c = 0: if b² − 4ac > 0 there are two real roots; if b² − 4ac = 0 there is one repeated root; if b² − 4ac < 0 there are no real roots.',
    example: 'x² + 5x + 6 = 0. b² − 4ac = 25 − 24 = 1 > 0, so two real roots.',
    relatedTopics: [{ label: 'Solving quadratic equations: quadratic formula', href: '/topics/solving-quadratic-equations-quadratic-formula' }],
  }),
  E({
    slug: 'nth-term',
    term: 'nth term',
    category: 'Algebra',
    short: 'A formula in terms of n that gives any term of a sequence.',
    long: 'For an arithmetic sequence with first term a and common difference d, the nth term is a + (n − 1)d. For a geometric sequence with first term a and common ratio r, the nth term is ar^(n − 1).',
    example: 'Sequence 5, 9, 13, 17. First term 5, common difference 4. nth term = 5 + (n − 1) × 4 = 4n + 1.',
    relatedTopics: [{ label: 'Sequences and nth term', href: '/topics/sequences-and-nth-term' }],
  }),
  E({
    slug: 'iteration',
    term: 'Iteration',
    category: 'Algebra',
    short: 'A repeated process where each step uses the previous result to approximate the solution of an equation.',
    long: 'Given an iterative formula x_(n+1) = f(x_n) and a starting value x_0, generate x_1, x_2, ... until two consecutive terms agree to the required precision. Used when an equation has no nice algebraic solution.',
    example: 'x_(n+1) = ³√(4x_n + 2), x_0 = 2. Generates 2.154, 2.199, 2.212, 2.215, 2.216, 2.216 — root is 2.216 to 3 d.p.',
    relatedTopics: [{ label: 'Iteration', href: '/topics/iteration' }],
  }),
  E({
    slug: 'function',
    term: 'Function',
    category: 'Algebra',
    short: 'A rule that takes an input x and produces a single output f(x).',
    long: 'Function notation f(x) replaces y. f(2) means substitute 2 for x. Composite functions like fg(x) mean apply g first, then f to the result. Inverse functions f⁻¹(x) reverse f.',
    example: 'If f(x) = 3x + 1 then f(2) = 7. Inverse: f⁻¹(x) = (x − 1)/3.',
    relatedTopics: [{ label: 'Functions and function notation', href: '/topics/functions-and-function-notation' }, { label: 'Inverse and composite functions', href: '/topics/inverse-and-composite-functions' }],
  }),

  // ── GEOMETRY ──────────────────────────────────────────────
  E({
    slug: 'hypotenuse',
    term: 'Hypotenuse',
    category: 'Geometry',
    short: 'The longest side of a right-angled triangle — the side opposite the right angle.',
    long: 'In Pythagoras and trigonometry, identify the hypotenuse first. It is the side that does NOT touch the right angle. Mislabelling the hypotenuse is the most common error in these topics.',
    relatedTopics: [{ label: "Pythagoras' theorem", href: '/topics/pythagoras-theorem' }, { label: 'Trigonometry: SOH-CAH-TOA', href: '/topics/trigonometry-sohcahtoa' }],
  }),
  E({
    slug: 'tangent',
    term: 'Tangent',
    category: 'Geometry',
    short: 'A line that touches a circle (or curve) at exactly one point without crossing it.',
    long: 'In circle geometry, the tangent at a point is perpendicular to the radius at that point. In calculus and gradients, the tangent line shows the instantaneous rate of change.',
    relatedTopics: [{ label: 'Circle theorems', href: '/topics/circle-theorems' }],
  }),
  E({
    slug: 'chord',
    term: 'Chord',
    category: 'Geometry',
    short: 'A straight line whose endpoints both lie on the circumference of a circle.',
    long: 'A diameter is the longest possible chord — it passes through the centre. The perpendicular from the centre to a chord bisects the chord (one of the circle theorems).',
    relatedTopics: [{ label: 'Circle theorems', href: '/topics/circle-theorems' }],
  }),
  E({
    slug: 'arc',
    term: 'Arc',
    category: 'Geometry',
    short: 'A portion of the circumference of a circle.',
    long: 'An arc is measured either as a length (s) or by the angle it subtends at the centre (θ). Arc length = (θ/360) × 2πr for θ in degrees.',
    relatedTopics: [{ label: 'Arc length and sector area', href: '/topics/arc-length-and-sector-area' }, { label: 'Circle theorems', href: '/topics/circle-theorems' }],
  }),
  E({
    slug: 'sector',
    term: 'Sector',
    category: 'Geometry',
    short: 'The "pizza slice" region of a circle bounded by two radii and an arc.',
    long: 'Sector area = (θ/360) × πr² for θ in degrees, where θ is the angle at the centre.',
    relatedTopics: [{ label: 'Arc length and sector area', href: '/topics/arc-length-and-sector-area' }],
  }),
  E({
    slug: 'segment',
    term: 'Segment',
    category: 'Geometry',
    short: 'The region of a circle enclosed by a chord and an arc.',
    long: 'Distinct from a sector (bounded by two radii). The minor segment is the smaller region, the major segment the larger.',
    relatedTopics: [{ label: 'Circle theorems', href: '/topics/circle-theorems' }],
  }),
  E({
    slug: 'congruent',
    term: 'Congruent',
    category: 'Geometry',
    short: 'Two shapes are congruent if they are identical in size and shape — one can be mapped to the other by translation, rotation or reflection.',
    long: 'Triangles are congruent if any of: three sides match (SSS); two sides and the included angle (SAS); two angles and a corresponding side (ASA or AAS); right angle, hypotenuse and one side (RHS).',
    relatedTopics: [{ label: 'Congruence and similarity', href: '/topics/congruence-and-similarity' }],
    related: ['similar'],
  }),
  E({
    slug: 'similar',
    term: 'Similar',
    category: 'Geometry',
    short: 'Two shapes are similar if they have the same shape but possibly different sizes — one is an enlargement of the other.',
    long: 'In similar shapes, corresponding angles are equal and corresponding sides are in the same ratio (the scale factor). Areas scale by the square of the factor; volumes by the cube.',
    relatedTopics: [{ label: 'Congruence and similarity', href: '/topics/congruence-and-similarity' }, { label: 'Transformations: enlargement and scale factor', href: '/topics/transformations-enlargement-and-scale-factor' }],
    related: ['congruent'],
  }),
  E({
    slug: 'bearing',
    term: 'Bearing',
    category: 'Geometry',
    short: 'A direction measured clockwise from north, expressed as a three-figure number from 000° to 360°.',
    long: 'East is a bearing of 090°. South is 180°. North-west is 315°. Bearings are always given as three digits, so 50° becomes 050°.',
    relatedTopics: [{ label: 'Bearings', href: '/topics/bearings' }],
  }),
  E({
    slug: 'vector',
    term: 'Vector',
    category: 'Geometry',
    short: 'A quantity with both magnitude (size) and direction. Often written as a column or in bold.',
    long: 'A column vector (3, 2) describes a translation of 3 right and 2 up. The magnitude (length) of (x, y) is √(x² + y²). Vectors can be added by adding components.',
    relatedTopics: [{ label: 'Vectors', href: '/topics/vectors' }],
  }),
  E({
    slug: 'parallel',
    term: 'Parallel',
    category: 'Geometry',
    short: 'Two lines that never meet and have the same gradient.',
    long: 'Parallel lines have equal gradients. When a transversal crosses parallel lines, it creates alternate angles (equal), corresponding angles (equal) and co-interior angles (sum to 180°).',
    relatedTopics: [{ label: 'Angles basic rules and parallel lines', href: '/topics/angles-basic-rules-and-parallel-lines' }, { label: 'Linear graphs and equation of a line', href: '/topics/linear-graphs-and-equation-of-a-line' }],
  }),
  E({
    slug: 'perpendicular',
    term: 'Perpendicular',
    category: 'Geometry',
    short: 'Two lines that meet at a right angle (90°).',
    long: 'Perpendicular lines have gradients whose product is −1. If one gradient is m, the perpendicular gradient is −1/m.',
    relatedTopics: [{ label: 'Linear graphs and equation of a line', href: '/topics/linear-graphs-and-equation-of-a-line' }],
  }),
  E({
    slug: 'locus',
    term: 'Locus (plural: loci)',
    category: 'Geometry',
    short: 'The set of all points satisfying a given condition. The locus of points 3 cm from O is a circle of radius 3 cm.',
    long: 'Common loci: circle (constant distance from a point); perpendicular bisector (equidistant from two points); angle bisector (equidistant from two lines).',
    relatedTopics: [{ label: 'Constructions and loci', href: '/topics/constructions-and-loci' }],
  }),

  // ── STATISTICS & PROBABILITY ──────────────────────────────
  E({
    slug: 'mean',
    term: 'Mean',
    category: 'Statistics & Probability',
    short: 'The arithmetic average. Sum of values divided by the number of values.',
    long: 'For a list: mean = (sum of values) ÷ (number of values). For a frequency table: sum of (value × frequency) divided by total frequency. For grouped data: use midpoints.',
    example: 'Mean of 4, 6, 7, 9, 14: (4 + 6 + 7 + 9 + 14) ÷ 5 = 8.',
    relatedTopics: [{ label: 'Mean, median, mode and range', href: '/topics/mean-median-mode-and-range' }],
    related: ['median', 'mode', 'range'],
  }),
  E({
    slug: 'median',
    term: 'Median',
    category: 'Statistics & Probability',
    short: 'The middle value when the data is sorted in order. For an even count, average the two middle values.',
    long: 'Sort the data first. For n values: the median is at position (n + 1) ÷ 2. The median is more robust than the mean against outliers.',
    example: 'Median of 3, 5, 7, 9, 11 is 7. Median of 3, 5, 7, 9 is (5 + 7) ÷ 2 = 6.',
    relatedTopics: [{ label: 'Mean, median, mode and range', href: '/topics/mean-median-mode-and-range' }],
    related: ['mean', 'mode', 'quartile'],
  }),
  E({
    slug: 'mode',
    term: 'Mode',
    category: 'Statistics & Probability',
    short: 'The value that appears most often. A data set can have one mode, more than one (bimodal), or no mode.',
    long: 'If two values tie for most frequent, the data is bimodal. If all values appear once, there is no mode.',
    example: 'Mode of 2, 3, 3, 5, 7, 7, 7, 9 is 7.',
    relatedTopics: [{ label: 'Mean, median, mode and range', href: '/topics/mean-median-mode-and-range' }],
    related: ['mean', 'median'],
  }),
  E({
    slug: 'range',
    term: 'Range',
    category: 'Statistics & Probability',
    short: 'A measure of spread: largest value minus smallest value.',
    long: 'Range is sensitive to outliers — a single extreme value changes the range dramatically. The interquartile range (Q3 − Q1) is more robust.',
    example: 'Range of 4, 7, 9, 12, 18 is 18 − 4 = 14.',
    relatedTopics: [{ label: 'Mean, median, mode and range', href: '/topics/mean-median-mode-and-range' }],
    related: ['interquartile-range'],
  }),
  E({
    slug: 'interquartile-range',
    term: 'Interquartile range (IQR)',
    category: 'Statistics & Probability',
    short: 'A measure of spread: Q3 − Q1. Less sensitive to outliers than the range.',
    long: 'Q1 (lower quartile) is the value 25% of the way through sorted data; Q3 (upper quartile) is at 75%. The IQR captures the middle half of the data.',
    relatedTopics: [{ label: 'Cumulative frequency and box plots', href: '/topics/cumulative-frequency-and-box-plots' }],
    related: ['quartile', 'range'],
  }),
  E({
    slug: 'quartile',
    term: 'Quartile',
    category: 'Statistics & Probability',
    short: 'The values that split sorted data into four equal parts. Q1 (25%), Q2 (median, 50%), Q3 (75%).',
    long: 'Read quartiles from a cumulative frequency graph by drawing horizontal lines at 25%, 50% and 75% of the total and reading off the x-values.',
    relatedTopics: [{ label: 'Cumulative frequency and box plots', href: '/topics/cumulative-frequency-and-box-plots' }],
    related: ['median', 'interquartile-range'],
  }),
  E({
    slug: 'frequency-density',
    term: 'Frequency density',
    category: 'Statistics & Probability',
    short: 'Frequency divided by class width. Used as the y-axis on a histogram.',
    long: 'frequency density = frequency ÷ class width. On a histogram, the AREA of each bar represents the frequency, not the height.',
    relatedTopics: [{ label: 'Histograms', href: '/topics/histograms' }],
  }),
  E({
    slug: 'correlation',
    term: 'Correlation',
    category: 'Statistics & Probability',
    short: 'The relationship between two variables on a scatter graph. Can be positive, negative or none.',
    long: 'Positive: as one rises, the other rises. Negative: as one rises, the other falls. None: no clear pattern. Correlation does not imply causation.',
    relatedTopics: [{ label: 'Scatter graphs and correlation', href: '/topics/scatter-graphs-and-correlation' }],
  }),
  E({
    slug: 'mutually-exclusive',
    term: 'Mutually exclusive',
    category: 'Statistics & Probability',
    short: 'Two events that cannot both happen at the same time. P(A or B) = P(A) + P(B).',
    long: 'Examples: rolling a 3 OR a 5 on one die (mutually exclusive). Rolling an even OR a multiple of 3 (NOT mutually exclusive — 6 is both).',
    relatedTopics: [{ label: 'Probability basics and relative frequency', href: '/topics/probability-basics-and-relative-frequency' }],
    related: ['independent', 'conditional'],
  }),
  E({
    slug: 'independent',
    term: 'Independent events',
    category: 'Statistics & Probability',
    short: 'Events where one occurring does not change the probability of the other. P(A and B) = P(A) × P(B).',
    long: 'Rolling a die twice — each roll is independent. Drawing two cards without replacement — NOT independent, because the first draw changes the second.',
    relatedTopics: [{ label: 'Probability tree diagrams', href: '/topics/probability-tree-diagrams' }],
    related: ['conditional', 'mutually-exclusive'],
  }),
  E({
    slug: 'conditional',
    term: 'Conditional probability',
    category: 'Statistics & Probability',
    short: 'The probability of one event given that another has occurred. Written P(A | B).',
    long: 'P(A | B) = P(A and B) ÷ P(B). In tree diagrams without replacement, conditional probabilities appear on the second branch.',
    example: 'Two cards drawn from a pack without replacement. P(2nd card is a heart | 1st was a heart) = 12/51.',
    relatedTopics: [{ label: 'Conditional probability', href: '/topics/conditional-probability' }],
    related: ['independent', 'tree-diagram'],
  }),
  E({
    slug: 'tree-diagram',
    term: 'Tree diagram',
    category: 'Statistics & Probability',
    short: 'A branching diagram showing all possible outcomes of two or more events and their probabilities.',
    long: 'Multiply along branches for combined probabilities; add across branches for "or" outcomes. Probabilities on each level must sum to 1.',
    relatedTopics: [{ label: 'Probability tree diagrams', href: '/topics/probability-tree-diagrams' }],
  }),
  E({
    slug: 'venn-diagram',
    term: 'Venn diagram',
    category: 'Statistics & Probability',
    short: 'A diagram showing sets as overlapping circles. Use set notation to describe regions.',
    long: 'A ∪ B is the union (everything in A or B or both). A ∩ B is the intersection (in both). A\' is the complement (everything not in A). The universal set is shown by the outer rectangle.',
    relatedTopics: [{ label: 'Venn diagrams', href: '/topics/venn-diagrams' }],
    related: ['mutually-exclusive'],
  }),
]

const SLUG_MAP = new Map(GLOSSARY.map(g => [g.slug, g]))

export function getGlossaryEntry(slug: string): GlossaryEntry | undefined {
  return SLUG_MAP.get(slug)
}

export function getGlossaryByCategory(): Record<GlossaryCategory, GlossaryEntry[]> {
  const grouped: Record<string, GlossaryEntry[]> = {}
  for (const e of GLOSSARY) {
    if (!grouped[e.category]) grouped[e.category] = []
    grouped[e.category].push(e)
  }
  for (const k of Object.keys(grouped)) {
    grouped[k].sort((a, b) => a.term.localeCompare(b.term))
  }
  return grouped as Record<GlossaryCategory, GlossaryEntry[]>
}

export function getGlossaryAlphabetical(): GlossaryEntry[] {
  return [...GLOSSARY].sort((a, b) => a.term.localeCompare(b.term))
}
