import type { TopicMCQSet } from './types'

export const NUMBER_MCQS: TopicMCQSet[] = [
  /* ------------------------------------------------------------------ */
  /*  1. fractions                                                       */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'fractions',
    topicTitle: 'Fractions',
    strand: 'Number',
    questions: [
      {
        id: 'fractions-1',
        topicSlug: 'fractions',
        question: 'What is 2/3 + 1/4?',
        options: ['3/7', '11/12', '3/12', '8/12'],
        correctIndex: 1,
        explanation: 'Find the LCD (12): 8/12 + 3/12 = 11/12.',
        misconception: 'Choosing 3/7 means you added numerators and denominators separately.',
        tier: 'Foundation',
      },
      {
        id: 'fractions-2',
        topicSlug: 'fractions',
        question: 'Which fraction is larger: 3/5 or 7/12?',
        options: ['3/5', '7/12', 'They are equal', 'Cannot tell'],
        correctIndex: 0,
        explanation: '3/5 = 36/60 and 7/12 = 35/60, so 3/5 is larger.',
        misconception: 'Picking 7/12 because 7 > 3 ignores the different denominators.',
        tier: 'Foundation',
      },
      {
        id: 'fractions-3',
        topicSlug: 'fractions',
        question: 'Simplify 18/24.',
        options: ['9/12', '3/4', '6/8', '2/3'],
        correctIndex: 1,
        explanation: 'Divide numerator and denominator by their HCF (6): 18/24 = 3/4.',
        misconception: 'Stopping at 9/12 means you only divided by 2 instead of fully simplifying.',
        tier: 'Foundation',
      },
      {
        id: 'fractions-4',
        topicSlug: 'fractions',
        question: 'Convert 2 3/5 to an improper fraction.',
        options: ['23/5', '13/5', '11/5', '6/5'],
        correctIndex: 1,
        explanation: '2 x 5 + 3 = 13, so 2 3/5 = 13/5.',
        misconception: 'Writing 23/5 means you just placed the whole number next to the numerator.',
        tier: 'Higher',
      },
      {
        id: 'fractions-5',
        topicSlug: 'fractions',
        question: 'What is 7/8 - 1/2?',
        options: ['6/6', '3/8', '6/8', '5/8'],
        correctIndex: 1,
        explanation: '1/2 = 4/8, so 7/8 - 4/8 = 3/8.',
        misconception: 'Choosing 6/6 means you subtracted numerators and denominators separately.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  2. adding-and-subtracting-fractions                                */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'adding-and-subtracting-fractions',
    topicTitle: 'Adding and Subtracting Fractions',
    strand: 'Number',
    questions: [
      {
        id: 'adding-and-subtracting-fractions-1',
        topicSlug: 'adding-and-subtracting-fractions',
        question: 'What is 1/3 + 1/6?',
        options: ['2/9', '1/2', '2/6', '1/3'],
        correctIndex: 1,
        explanation: '1/3 = 2/6, so 2/6 + 1/6 = 3/6 = 1/2.',
        misconception: 'Choosing 2/9 means you added both numerators and both denominators.',
        tier: 'Foundation',
      },
      {
        id: 'adding-and-subtracting-fractions-2',
        topicSlug: 'adding-and-subtracting-fractions',
        question: 'What is 5/6 - 1/3?',
        options: ['4/3', '1/2', '4/6', '2/3'],
        correctIndex: 1,
        explanation: '1/3 = 2/6, so 5/6 - 2/6 = 3/6 = 1/2.',
        misconception: 'Choosing 4/3 means you subtracted denominators as well as numerators.',
        tier: 'Foundation',
      },
      {
        id: 'adding-and-subtracting-fractions-3',
        topicSlug: 'adding-and-subtracting-fractions',
        question: 'What is 2/5 + 3/10?',
        options: ['5/15', '7/10', '5/10', '1/2'],
        correctIndex: 1,
        explanation: '2/5 = 4/10, so 4/10 + 3/10 = 7/10.',
        misconception: 'Choosing 5/15 means you added numerators and denominators directly.',
        tier: 'Foundation',
      },
      {
        id: 'adding-and-subtracting-fractions-4',
        topicSlug: 'adding-and-subtracting-fractions',
        question: 'What is 3 1/4 + 2 2/3?',
        options: ['5 3/7', '5 11/12', '5 3/12', '6 1/12'],
        correctIndex: 1,
        explanation: '1/4 = 3/12 and 2/3 = 8/12; 3/12 + 8/12 = 11/12; whole parts: 3 + 2 = 5.',
        misconception: 'Choosing 5 3/7 means you added the fraction parts by adding numerators and denominators.',
        tier: 'Higher',
      },
      {
        id: 'adding-and-subtracting-fractions-5',
        topicSlug: 'adding-and-subtracting-fractions',
        question: 'What is 4 1/3 - 1 3/4?',
        options: ['3 1/1', '2 7/12', '3 2/7', '2 5/12'],
        correctIndex: 1,
        explanation: '4 1/3 = 52/12 and 1 3/4 = 21/12; 52/12 - 21/12 = 31/12 = 2 7/12.',
        misconception: 'Choosing 3 2/7 means you subtracted whole numbers and then added fraction numerators and denominators.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  3. multiplying-and-dividing-fractions                              */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'multiplying-and-dividing-fractions',
    topicTitle: 'Multiplying and Dividing Fractions',
    strand: 'Number',
    questions: [
      {
        id: 'multiplying-and-dividing-fractions-1',
        topicSlug: 'multiplying-and-dividing-fractions',
        question: 'What is 2/3 x 3/4?',
        options: ['6/7', '5/7', '1/2', '6/12'],
        correctIndex: 2,
        explanation: '2 x 3 = 6 and 3 x 4 = 12; 6/12 = 1/2.',
        misconception: 'Choosing 6/7 means you added the denominators instead of multiplying them.',
        tier: 'Foundation',
      },
      {
        id: 'multiplying-and-dividing-fractions-2',
        topicSlug: 'multiplying-and-dividing-fractions',
        question: 'What is 3/5 / 2?',
        options: ['6/5', '3/10', '1/5', '3/7'],
        correctIndex: 1,
        explanation: 'Dividing by 2 means multiplying by 1/2: 3/5 x 1/2 = 3/10.',
        misconception: 'Choosing 6/5 means you multiplied the numerator by 2 instead of dividing.',
        tier: 'Foundation',
      },
      {
        id: 'multiplying-and-dividing-fractions-3',
        topicSlug: 'multiplying-and-dividing-fractions',
        question: 'What is 4/7 / 2/3?',
        options: ['8/21', '6/7', '12/14', '14/12'],
        correctIndex: 1,
        explanation: 'Flip and multiply: 4/7 x 3/2 = 12/14 = 6/7.',
        misconception: 'Choosing 8/21 means you multiplied straight across without flipping the second fraction.',
        tier: 'Foundation',
      },
      {
        id: 'multiplying-and-dividing-fractions-4',
        topicSlug: 'multiplying-and-dividing-fractions',
        question: 'What is 1 2/3 x 2 1/5?',
        options: ['2 2/15', '3 2/3', '3 11/15', '2 3/8'],
        correctIndex: 1,
        explanation: '1 2/3 = 5/3 and 2 1/5 = 11/5. 5/3 x 11/5 = 55/15 = 11/3 = 3 2/3.',
        misconception: 'Choosing 2 2/15 means you multiplied the whole numbers and fraction parts separately.',
        tier: 'Higher',
      },
      {
        id: 'multiplying-and-dividing-fractions-5',
        topicSlug: 'multiplying-and-dividing-fractions',
        question: 'What is 2 1/2 / 1 1/4?',
        options: ['2', '2 1/2', '1 1/2', '3 1/8'],
        correctIndex: 0,
        explanation: '5/2 / 5/4 = 5/2 x 4/5 = 20/10 = 2.',
        misconception: 'Choosing 3 1/8 means you multiplied instead of dividing.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  4. decimals                                                        */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'decimals',
    topicTitle: 'Decimals',
    strand: 'Number',
    questions: [
      {
        id: 'decimals-1',
        topicSlug: 'decimals',
        question: 'What is 0.3 + 0.25?',
        options: ['0.28', '0.55', '0.325', '0.525'],
        correctIndex: 1,
        explanation: '0.30 + 0.25 = 0.55.',
        misconception: 'Choosing 0.28 means you added 3 + 25 = 28 without aligning decimal places.',
        tier: 'Foundation',
      },
      {
        id: 'decimals-2',
        topicSlug: 'decimals',
        question: 'Put these in order from smallest to largest: 0.4, 0.38, 0.401.',
        options: [
          '0.4, 0.38, 0.401',
          '0.38, 0.4, 0.401',
          '0.401, 0.4, 0.38',
          '0.38, 0.401, 0.4',
        ],
        correctIndex: 1,
        explanation: '0.38 = 0.380, 0.4 = 0.400, 0.401 = 0.401. So order is 0.38, 0.4, 0.401.',
        misconception: 'Choosing 0.4, 0.38, 0.401 assumes fewer digits means a smaller number.',
        tier: 'Foundation',
      },
      {
        id: 'decimals-3',
        topicSlug: 'decimals',
        question: 'What is 5 - 2.37?',
        options: ['3.63', '2.63', '3.37', '2.73'],
        correctIndex: 1,
        explanation: '5.00 - 2.37 = 2.63.',
        misconception: 'Choosing 3.63 suggests an error carrying across the decimal point.',
        tier: 'Foundation',
      },
      {
        id: 'decimals-4',
        topicSlug: 'decimals',
        question: 'Which decimal is equivalent to 7/8?',
        options: ['0.78', '0.875', '0.85', '0.7'],
        correctIndex: 1,
        explanation: '7 / 8 = 0.875.',
        misconception: 'Choosing 0.78 means you just placed the numerator and denominator side by side.',
        tier: 'Higher',
      },
      {
        id: 'decimals-5',
        topicSlug: 'decimals',
        question: 'What is 0.1 + 0.02 + 0.003?',
        options: ['0.123', '0.6', '0.15', '0.321'],
        correctIndex: 0,
        explanation: '0.100 + 0.020 + 0.003 = 0.123.',
        misconception: 'Choosing 0.6 means you added 1 + 2 + 3 = 6 and placed it after the decimal.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  5. multiplying-and-dividing-decimals                               */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'multiplying-and-dividing-decimals',
    topicTitle: 'Multiplying and Dividing Decimals',
    strand: 'Number',
    questions: [
      {
        id: 'multiplying-and-dividing-decimals-1',
        topicSlug: 'multiplying-and-dividing-decimals',
        question: 'What is 0.3 x 0.2?',
        options: ['0.6', '0.06', '0.006', '6'],
        correctIndex: 1,
        explanation: '3 x 2 = 6; two decimal places total gives 0.06.',
        misconception: 'Choosing 0.6 means you only counted one decimal place instead of two.',
        tier: 'Foundation',
      },
      {
        id: 'multiplying-and-dividing-decimals-2',
        topicSlug: 'multiplying-and-dividing-decimals',
        question: 'What is 2.4 / 0.6?',
        options: ['0.4', '4', '0.25', '14.4'],
        correctIndex: 1,
        explanation: '2.4 / 0.6 = 24 / 6 = 4.',
        misconception: 'Choosing 0.4 means you divided digits but misplaced the decimal point.',
        tier: 'Foundation',
      },
      {
        id: 'multiplying-and-dividing-decimals-3',
        topicSlug: 'multiplying-and-dividing-decimals',
        question: 'What is 0.7 x 0.7?',
        options: ['0.49', '4.9', '0.14', '0.77'],
        correctIndex: 0,
        explanation: '7 x 7 = 49; two decimal places gives 0.49.',
        misconception: 'Choosing 4.9 means you only counted one decimal place.',
        tier: 'Foundation',
      },
      {
        id: 'multiplying-and-dividing-decimals-4',
        topicSlug: 'multiplying-and-dividing-decimals',
        question: 'What is 0.12 x 0.3?',
        options: ['0.36', '0.036', '0.0036', '3.6'],
        correctIndex: 1,
        explanation: '12 x 3 = 36; three decimal places total gives 0.036.',
        misconception: 'Choosing 0.36 means you only counted two decimal places instead of three.',
        tier: 'Higher',
      },
      {
        id: 'multiplying-and-dividing-decimals-5',
        topicSlug: 'multiplying-and-dividing-decimals',
        question: 'What is 0.48 / 0.08?',
        options: ['0.6', '6', '60', '0.06'],
        correctIndex: 1,
        explanation: '0.48 / 0.08 = 48 / 8 = 6.',
        misconception: 'Choosing 0.6 means you divided correctly but misplaced the decimal point.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  6. percentages                                                     */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'percentages',
    topicTitle: 'Percentages',
    strand: 'Number',
    questions: [
      {
        id: 'percentages-1',
        topicSlug: 'percentages',
        question: 'What is 50% as a fraction in its simplest form?',
        options: ['5/10', '1/2', '50/1', '1/5'],
        correctIndex: 1,
        explanation: '50% = 50/100 = 1/2.',
        misconception: 'Choosing 1/5 confuses 50% with dividing by 5.',
        tier: 'Foundation',
      },
      {
        id: 'percentages-2',
        topicSlug: 'percentages',
        question: 'What is 25% as a decimal?',
        options: ['2.5', '0.025', '0.25', '25.0'],
        correctIndex: 2,
        explanation: '25% = 25 / 100 = 0.25.',
        misconception: 'Choosing 2.5 means you divided by 10 instead of 100.',
        tier: 'Foundation',
      },
      {
        id: 'percentages-3',
        topicSlug: 'percentages',
        question: 'What percentage is equivalent to the fraction 3/10?',
        options: ['3%', '30%', '0.3%', '33%'],
        correctIndex: 1,
        explanation: '3/10 = 0.3 = 30%.',
        misconception: 'Choosing 3% means you treated the numerator as the percentage directly.',
        tier: 'Foundation',
      },
      {
        id: 'percentages-4',
        topicSlug: 'percentages',
        question: 'What is 0.07 as a percentage?',
        options: ['70%', '0.7%', '7%', '0.07%'],
        correctIndex: 2,
        explanation: '0.07 x 100 = 7%.',
        misconception: 'Choosing 70% means you multiplied by 1000 instead of 100.',
        tier: 'Higher',
      },
      {
        id: 'percentages-5',
        topicSlug: 'percentages',
        question: 'Which is the largest: 1/3, 30%, or 0.35?',
        options: ['1/3', '30%', '0.35', 'They are all equal'],
        correctIndex: 2,
        explanation: '1/3 = 0.333..., 30% = 0.30, 0.35 = 0.35. So 0.35 is the largest.',
        misconception: 'Choosing 1/3 because it is a recurring decimal assumes recurring = bigger.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  7. percentage-of-an-amount                                         */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'percentage-of-an-amount',
    topicTitle: 'Percentage of an Amount',
    strand: 'Number',
    questions: [
      {
        id: 'percentage-of-an-amount-1',
        topicSlug: 'percentage-of-an-amount',
        question: 'What is 10% of 250?',
        options: ['2.5', '25', '250', '50'],
        correctIndex: 1,
        explanation: '10% of 250 = 250 / 10 = 25.',
        misconception: 'Choosing 2.5 means you divided by 100 instead of 10.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-of-an-amount-2',
        topicSlug: 'percentage-of-an-amount',
        question: 'What is 15% of 60?',
        options: ['9', '90', '6', '15'],
        correctIndex: 0,
        explanation: '10% of 60 = 6, 5% = 3, so 15% = 6 + 3 = 9.',
        misconception: 'Choosing 90 means you multiplied 15 x 6 instead of finding a percentage.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-of-an-amount-3',
        topicSlug: 'percentage-of-an-amount',
        question: 'What is 40% of 80?',
        options: ['320', '32', '20', '48'],
        correctIndex: 1,
        explanation: '40% of 80 = 0.4 x 80 = 32.',
        misconception: 'Choosing 320 means you multiplied 40 x 80 and forgot to divide by 100.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-of-an-amount-4',
        topicSlug: 'percentage-of-an-amount',
        question: 'What is 17.5% of 200?',
        options: ['35', '17.5', '3.5', '350'],
        correctIndex: 0,
        explanation: '10% = 20, 5% = 10, 2.5% = 5; 20 + 10 + 5 = 35.',
        misconception: 'Choosing 17.5 means you just read the percentage without applying it to 200.',
        tier: 'Higher',
      },
      {
        id: 'percentage-of-an-amount-5',
        topicSlug: 'percentage-of-an-amount',
        question: 'A coat costs 120. It is reduced by 30%. What is the sale price?',
        options: ['90', '36', '84', '156'],
        correctIndex: 2,
        explanation: '30% of 120 = 36. Sale price = 120 - 36 = 84.',
        misconception: 'Choosing 90 means you found 30/120 = 1/4 and subtracted a quarter instead of 30%.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  8. percentage-change                                               */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'percentage-change',
    topicTitle: 'Percentage Change',
    strand: 'Number',
    questions: [
      {
        id: 'percentage-change-1',
        topicSlug: 'percentage-change',
        question: 'A price increases from 40 to 50. What is the percentage increase?',
        options: ['10%', '20%', '25%', '80%'],
        correctIndex: 2,
        explanation: 'Change = 10. 10/40 x 100 = 25%.',
        misconception: 'Choosing 20% means you divided the change by the new value (10/50) instead of the original.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-change-2',
        topicSlug: 'percentage-change',
        question: 'A price drops from 80 to 60. What is the percentage decrease?',
        options: ['20%', '25%', '33.3%', '75%'],
        correctIndex: 1,
        explanation: 'Change = 20. 20/80 x 100 = 25%.',
        misconception: 'Choosing 33.3% means you divided the change by the new value (20/60).',
        tier: 'Foundation',
      },
      {
        id: 'percentage-change-3',
        topicSlug: 'percentage-change',
        question: 'The number of students rises from 200 to 230. What is the percentage increase?',
        options: ['30%', '15%', '13%', '86.9%'],
        correctIndex: 1,
        explanation: 'Change = 30. 30/200 x 100 = 15%.',
        misconception: 'Choosing 30% means you just used the change as the percentage.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-change-4',
        topicSlug: 'percentage-change',
        question: 'A share price goes from 1.50 to 1.80. What is the percentage increase?',
        options: ['30%', '20%', '16.7%', '80%'],
        correctIndex: 1,
        explanation: 'Change = 0.30. 0.30/1.50 x 100 = 20%.',
        misconception: 'Choosing 16.7% means you divided by the new value (0.30/1.80).',
        tier: 'Higher',
      },
      {
        id: 'percentage-change-5',
        topicSlug: 'percentage-change',
        question: 'After a 20% decrease, a value becomes 160. What was the original value?',
        options: ['192', '200', '128', '180'],
        correctIndex: 1,
        explanation: '80% of original = 160, so original = 160 / 0.8 = 200.',
        misconception: 'Choosing 192 means you added 20% of 160 to 160, using the wrong base.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /*  9. percentage-multipliers                                          */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'percentage-multipliers',
    topicTitle: 'Percentage Multipliers',
    strand: 'Number',
    questions: [
      {
        id: 'percentage-multipliers-1',
        topicSlug: 'percentage-multipliers',
        question: 'What multiplier represents a 15% increase?',
        options: ['0.15', '1.15', '0.85', '15'],
        correctIndex: 1,
        explanation: 'A 15% increase means you have 100% + 15% = 115% = 1.15.',
        misconception: 'Choosing 0.15 means you only found the percentage, not the multiplier for the total.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-multipliers-2',
        topicSlug: 'percentage-multipliers',
        question: 'What multiplier represents a 20% decrease?',
        options: ['0.20', '1.20', '0.80', '0.02'],
        correctIndex: 2,
        explanation: '100% - 20% = 80% = 0.80.',
        misconception: 'Choosing 1.20 confuses a decrease with an increase.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-multipliers-3',
        topicSlug: 'percentage-multipliers',
        question: 'A TV costs 400 and increases by 5%. Using a multiplier, what is the new price?',
        options: ['405', '420', '380', '2000'],
        correctIndex: 1,
        explanation: '400 x 1.05 = 420.',
        misconception: 'Choosing 405 means you added 5 instead of calculating 5% of 400.',
        tier: 'Foundation',
      },
      {
        id: 'percentage-multipliers-4',
        topicSlug: 'percentage-multipliers',
        question: '500 is invested at 3% compound interest for 2 years. What is the final amount?',
        options: ['530', '530.45', '515', '560'],
        correctIndex: 1,
        explanation: '500 x 1.03^2 = 500 x 1.0609 = 530.45.',
        misconception: 'Choosing 530 means you used simple interest (500 + 2 x 15) instead of compound.',
        tier: 'Higher',
      },
      {
        id: 'percentage-multipliers-5',
        topicSlug: 'percentage-multipliers',
        question: 'A car depreciates by 12% per year. What single multiplier gives its value after 3 years?',
        options: ['0.64', '0.681472', '0.36', '0.88'],
        correctIndex: 1,
        explanation: '0.88^3 = 0.681472.',
        misconception: 'Choosing 0.64 means you subtracted 12% three times (100 - 36 = 64) as simple calculation.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 10. expressing-one-quantity-as-a-percentage                         */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'expressing-one-quantity-as-a-percentage',
    topicTitle: 'Expressing as a Percentage',
    strand: 'Number',
    questions: [
      {
        id: 'expressing-one-quantity-as-a-percentage-1',
        topicSlug: 'expressing-one-quantity-as-a-percentage',
        question: 'Express 15 out of 60 as a percentage.',
        options: ['15%', '25%', '4%', '40%'],
        correctIndex: 1,
        explanation: '15/60 x 100 = 25%.',
        misconception: 'Choosing 15% means you just used the numerator as the percentage.',
        tier: 'Foundation',
      },
      {
        id: 'expressing-one-quantity-as-a-percentage-2',
        topicSlug: 'expressing-one-quantity-as-a-percentage',
        question: 'Express 3 out of 20 as a percentage.',
        options: ['3%', '6%', '15%', '30%'],
        correctIndex: 2,
        explanation: '3/20 x 100 = 15%.',
        misconception: 'Choosing 3% means you just used the numerator as the percentage.',
        tier: 'Foundation',
      },
      {
        id: 'expressing-one-quantity-as-a-percentage-3',
        topicSlug: 'expressing-one-quantity-as-a-percentage',
        question: 'A student scores 18 out of 25. What percentage is this?',
        options: ['18%', '72%', '75%', '36%'],
        correctIndex: 1,
        explanation: '18/25 x 100 = 72%.',
        misconception: 'Choosing 75% is a common rounding/estimation error confusing 18/25 with 3/4.',
        tier: 'Foundation',
      },
      {
        id: 'expressing-one-quantity-as-a-percentage-4',
        topicSlug: 'expressing-one-quantity-as-a-percentage',
        question: 'Express 45 cm as a percentage of 1.5 m.',
        options: ['30%', '3%', '45%', '33.3%'],
        correctIndex: 0,
        explanation: '1.5 m = 150 cm. 45/150 x 100 = 30%.',
        misconception: 'Choosing 3% means you forgot to convert metres to centimetres (45/1500).',
        tier: 'Higher',
      },
      {
        id: 'expressing-one-quantity-as-a-percentage-5',
        topicSlug: 'expressing-one-quantity-as-a-percentage',
        question: 'Express 250 g as a percentage of 2 kg.',
        options: ['125%', '12.5%', '25%', '1.25%'],
        correctIndex: 1,
        explanation: '2 kg = 2000 g. 250/2000 x 100 = 12.5%.',
        misconception: 'Choosing 125% means you divided 250 by 200 instead of 2000, forgetting the unit conversion.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 11. powers-and-roots                                                */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'powers-and-roots',
    topicTitle: 'Powers and Roots',
    strand: 'Number',
    questions: [
      {
        id: 'powers-and-roots-1',
        topicSlug: 'powers-and-roots',
        question: 'What is 2^5?',
        options: ['10', '25', '32', '64'],
        correctIndex: 2,
        explanation: '2^5 = 2 x 2 x 2 x 2 x 2 = 32.',
        misconception: 'Choosing 10 means you multiplied the base by the exponent (2 x 5).',
        tier: 'Foundation',
      },
      {
        id: 'powers-and-roots-2',
        topicSlug: 'powers-and-roots',
        question: 'What is the square root of 144?',
        options: ['11', '12', '13', '14'],
        correctIndex: 1,
        explanation: '12 x 12 = 144.',
        misconception: 'Choosing 14 is a common guess confusing nearby square numbers.',
        tier: 'Foundation',
      },
      {
        id: 'powers-and-roots-3',
        topicSlug: 'powers-and-roots',
        question: 'What is the cube root of 27?',
        options: ['9', '3', '27', '4'],
        correctIndex: 1,
        explanation: '3 x 3 x 3 = 27.',
        misconception: 'Choosing 9 means you found 27/3 (dividing by 3 instead of cube rooting).',
        tier: 'Foundation',
      },
      {
        id: 'powers-and-roots-4',
        topicSlug: 'powers-and-roots',
        question: 'What is 4^3?',
        options: ['12', '43', '64', '81'],
        correctIndex: 2,
        explanation: '4 x 4 x 4 = 64.',
        misconception: 'Choosing 12 means you multiplied 4 x 3 instead of raising to a power.',
        tier: 'Higher',
      },
      {
        id: 'powers-and-roots-5',
        topicSlug: 'powers-and-roots',
        question: 'What is the cube root of 125?',
        options: ['5', '25', '15', '12.5'],
        correctIndex: 0,
        explanation: '5 x 5 x 5 = 125.',
        misconception: 'Choosing 25 means you divided 125 by 5 instead of finding the cube root.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 12. square-numbers-and-cube-numbers                                 */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'square-numbers-and-cube-numbers',
    topicTitle: 'Square and Cube Numbers',
    strand: 'Number',
    questions: [
      {
        id: 'square-numbers-and-cube-numbers-1',
        topicSlug: 'square-numbers-and-cube-numbers',
        question: 'Which of these is a square number?',
        options: ['18', '25', '30', '45'],
        correctIndex: 1,
        explanation: '25 = 5 x 5.',
        misconception: 'Choosing 30 may come from confusing multiples of 5 with square numbers.',
        tier: 'Foundation',
      },
      {
        id: 'square-numbers-and-cube-numbers-2',
        topicSlug: 'square-numbers-and-cube-numbers',
        question: 'What is 13 squared?',
        options: ['26', '156', '169', '196'],
        correctIndex: 2,
        explanation: '13 x 13 = 169.',
        misconception: 'Choosing 26 means you doubled 13 instead of squaring it.',
        tier: 'Foundation',
      },
      {
        id: 'square-numbers-and-cube-numbers-3',
        topicSlug: 'square-numbers-and-cube-numbers',
        question: 'Which of these is a cube number?',
        options: ['9', '16', '27', '36'],
        correctIndex: 2,
        explanation: '27 = 3 x 3 x 3.',
        misconception: 'Choosing 9 confuses square numbers (3^2) with cube numbers (3^3).',
        tier: 'Foundation',
      },
      {
        id: 'square-numbers-and-cube-numbers-4',
        topicSlug: 'square-numbers-and-cube-numbers',
        question: 'What is the value of 7^2 + 3^3?',
        options: ['76', '58', '100', '52'],
        correctIndex: 0,
        explanation: '7^2 = 49 and 3^3 = 27; 49 + 27 = 76.',
        misconception: 'Choosing 58 means you squared 3 instead of cubing it (49 + 9 = 58).',
        tier: 'Higher',
      },
      {
        id: 'square-numbers-and-cube-numbers-5',
        topicSlug: 'square-numbers-and-cube-numbers',
        question: 'Find a number that is both a square number and a cube number between 1 and 100.',
        options: ['8', '36', '49', '64'],
        correctIndex: 3,
        explanation: '64 = 8^2 and 64 = 4^3.',
        misconception: 'Choosing 36 because it is a well-known square (6^2) but it is not a cube number.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 13. estimating-square-roots                                         */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'estimating-square-roots',
    topicTitle: 'Estimating Square Roots',
    strand: 'Number',
    questions: [
      {
        id: 'estimating-square-roots-1',
        topicSlug: 'estimating-square-roots',
        question: 'Between which two whole numbers does the square root of 20 lie?',
        options: ['3 and 4', '4 and 5', '5 and 6', '9 and 10'],
        correctIndex: 1,
        explanation: '4^2 = 16 and 5^2 = 25, so sqrt(20) lies between 4 and 5.',
        misconception: 'Choosing 9 and 10 means you halved 20 instead of finding the square root.',
        tier: 'Foundation',
      },
      {
        id: 'estimating-square-roots-2',
        topicSlug: 'estimating-square-roots',
        question: 'Estimate the square root of 50 to 1 decimal place.',
        options: ['6.8', '7.1', '7.5', '25'],
        correctIndex: 1,
        explanation: '7^2 = 49 and 7.1^2 = 50.41, so sqrt(50) is approximately 7.1.',
        misconception: 'Choosing 25 means you halved 50 instead of finding the square root.',
        tier: 'Foundation',
      },
      {
        id: 'estimating-square-roots-3',
        topicSlug: 'estimating-square-roots',
        question: 'Between which two whole numbers does the square root of 70 lie?',
        options: ['7 and 8', '8 and 9', '6 and 7', '35 and 36'],
        correctIndex: 1,
        explanation: '8^2 = 64 and 9^2 = 81, so sqrt(70) is between 8 and 9.',
        misconception: 'Choosing 7 and 8 means you confused 7^2 = 49 with a number close to 70.',
        tier: 'Foundation',
      },
      {
        id: 'estimating-square-roots-4',
        topicSlug: 'estimating-square-roots',
        question: 'The square root of 90 is closest to which value?',
        options: ['9', '9.5', '10', '45'],
        correctIndex: 1,
        explanation: '9^2 = 81 and 10^2 = 100. 90 is about halfway, so sqrt(90) is approximately 9.5.',
        misconception: 'Choosing 45 means you halved 90 instead of square rooting it.',
        tier: 'Higher',
      },
      {
        id: 'estimating-square-roots-5',
        topicSlug: 'estimating-square-roots',
        question: 'Estimate the square root of 200 to the nearest whole number.',
        options: ['10', '14', '15', '100'],
        correctIndex: 1,
        explanation: '14^2 = 196 and 15^2 = 225. 200 is closer to 196, so sqrt(200) is approximately 14.',
        misconception: 'Choosing 100 means you halved 200 instead of finding the square root.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 14. indices-and-index-laws                                          */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'indices-and-index-laws',
    topicTitle: 'Indices and Index Laws',
    strand: 'Number',
    questions: [
      {
        id: 'indices-and-index-laws-1',
        topicSlug: 'indices-and-index-laws',
        question: 'Simplify a^3 x a^4.',
        options: ['a^7', 'a^12', '2a^7', 'a^34'],
        correctIndex: 0,
        explanation: 'When multiplying same bases, add the powers: 3 + 4 = 7.',
        misconception: 'Choosing a^12 means you multiplied the powers instead of adding them.',
        tier: 'Foundation',
      },
      {
        id: 'indices-and-index-laws-2',
        topicSlug: 'indices-and-index-laws',
        question: 'Simplify b^8 / b^3.',
        options: ['b^24', 'b^5', 'b^11', 'b^(8/3)'],
        correctIndex: 1,
        explanation: 'When dividing same bases, subtract the powers: 8 - 3 = 5.',
        misconception: 'Choosing b^24 means you multiplied the powers instead of subtracting.',
        tier: 'Foundation',
      },
      {
        id: 'indices-and-index-laws-3',
        topicSlug: 'indices-and-index-laws',
        question: 'Simplify (c^2)^3.',
        options: ['c^5', 'c^6', 'c^8', 'c^23'],
        correctIndex: 1,
        explanation: 'Multiply the powers: 2 x 3 = 6.',
        misconception: 'Choosing c^5 means you added the powers instead of multiplying.',
        tier: 'Foundation',
      },
      {
        id: 'indices-and-index-laws-4',
        topicSlug: 'indices-and-index-laws',
        question: 'What is the value of 5^0?',
        options: ['0', '5', '1', '50'],
        correctIndex: 2,
        explanation: 'Any non-zero number raised to the power 0 equals 1.',
        misconception: 'Choosing 0 means you think anything to the power 0 gives 0.',
        tier: 'Higher',
      },
      {
        id: 'indices-and-index-laws-5',
        topicSlug: 'indices-and-index-laws',
        question: 'Simplify (2x^3)^2.',
        options: ['2x^6', '4x^6', '4x^5', '2x^5'],
        correctIndex: 1,
        explanation: '2^2 = 4 and (x^3)^2 = x^6, so (2x^3)^2 = 4x^6.',
        misconception: 'Choosing 2x^6 means you forgot to square the coefficient 2.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 15. negative-and-fractional-indices                                 */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'negative-and-fractional-indices',
    topicTitle: 'Negative and Fractional Indices',
    strand: 'Number',
    questions: [
      {
        id: 'negative-and-fractional-indices-1',
        topicSlug: 'negative-and-fractional-indices',
        question: 'What is 2^(-3)?',
        options: ['-8', '-6', '1/8', '8'],
        correctIndex: 2,
        explanation: '2^(-3) = 1/2^3 = 1/8.',
        misconception: 'Choosing -8 means you think a negative index makes the result negative.',
        tier: 'Foundation',
      },
      {
        id: 'negative-and-fractional-indices-2',
        topicSlug: 'negative-and-fractional-indices',
        question: 'What is 9^(1/2)?',
        options: ['4.5', '3', '81', '18'],
        correctIndex: 1,
        explanation: '9^(1/2) = sqrt(9) = 3.',
        misconception: 'Choosing 4.5 means you halved 9 instead of finding the square root.',
        tier: 'Foundation',
      },
      {
        id: 'negative-and-fractional-indices-3',
        topicSlug: 'negative-and-fractional-indices',
        question: 'What is 10^(-1)?',
        options: ['-10', '0.1', '-1', '0.01'],
        correctIndex: 1,
        explanation: '10^(-1) = 1/10 = 0.1.',
        misconception: 'Choosing -10 means you think a negative index negates the base.',
        tier: 'Foundation',
      },
      {
        id: 'negative-and-fractional-indices-4',
        topicSlug: 'negative-and-fractional-indices',
        question: 'What is 8^(2/3)?',
        options: ['4', '16/3', '2', '12'],
        correctIndex: 0,
        explanation: '8^(1/3) = 2, then 2^2 = 4.',
        misconception: 'Choosing 16/3 means you calculated 8 x 2/3 instead of using index laws.',
        tier: 'Higher',
      },
      {
        id: 'negative-and-fractional-indices-5',
        topicSlug: 'negative-and-fractional-indices',
        question: 'What is 25^(-1/2)?',
        options: ['-5', '1/5', '-12.5', '5'],
        correctIndex: 1,
        explanation: '25^(1/2) = 5, so 25^(-1/2) = 1/5.',
        misconception: 'Choosing -5 means you think the negative index negates the answer.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 16. standard-form                                                   */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'standard-form',
    topicTitle: 'Standard Form',
    strand: 'Number',
    questions: [
      {
        id: 'standard-form-1',
        topicSlug: 'standard-form',
        question: 'Which of these is written in correct standard form?',
        options: [
          '32 x 10^4',
          '3.2 x 10^5',
          '0.32 x 10^6',
          '320 x 10^3',
        ],
        correctIndex: 1,
        explanation: 'In standard form, the number must be between 1 and 10. Only 3.2 satisfies this.',
        misconception: 'Choosing 32 x 10^4 means you forgot the number before the x 10 must be between 1 and 10.',
        tier: 'Foundation',
      },
      {
        id: 'standard-form-2',
        topicSlug: 'standard-form',
        question: 'What is 4.7 x 10^3 as an ordinary number?',
        options: ['47', '470', '4700', '47000'],
        correctIndex: 2,
        explanation: '4.7 x 10^3 = 4.7 x 1000 = 4700.',
        misconception: 'Choosing 470 means you only multiplied by 100 (10^2) instead of 10^3.',
        tier: 'Foundation',
      },
      {
        id: 'standard-form-3',
        topicSlug: 'standard-form',
        question: 'What is 5.1 x 10^(-2) as an ordinary number?',
        options: ['510', '51', '0.051', '0.51'],
        correctIndex: 2,
        explanation: '5.1 x 10^(-2) = 5.1 / 100 = 0.051.',
        misconception: 'Choosing 0.51 means you divided by 10 instead of 100.',
        tier: 'Foundation',
      },
      {
        id: 'standard-form-4',
        topicSlug: 'standard-form',
        question: 'Write 0.00036 in standard form.',
        options: [
          '3.6 x 10^(-3)',
          '3.6 x 10^(-4)',
          '36 x 10^(-5)',
          '0.36 x 10^(-3)',
        ],
        correctIndex: 1,
        explanation: '0.00036 = 3.6 x 10^(-4). The decimal moves 4 places to the right.',
        misconception: 'Choosing 3.6 x 10^(-3) means you miscounted the number of decimal places.',
        tier: 'Higher',
      },
      {
        id: 'standard-form-5',
        topicSlug: 'standard-form',
        question: 'Write 8 250 000 in standard form.',
        options: [
          '8.25 x 10^6',
          '82.5 x 10^5',
          '8.25 x 10^7',
          '0.825 x 10^7',
        ],
        correctIndex: 0,
        explanation: '8 250 000 = 8.25 x 10^6.',
        misconception: 'Choosing 8.25 x 10^7 means you miscounted the number of places the decimal moved.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 17. writing-in-standard-form                                        */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'writing-in-standard-form',
    topicTitle: 'Writing in Standard Form',
    strand: 'Number',
    questions: [
      {
        id: 'writing-in-standard-form-1',
        topicSlug: 'writing-in-standard-form',
        question: 'Write 56 000 in standard form.',
        options: [
          '5.6 x 10^3',
          '5.6 x 10^4',
          '56 x 10^3',
          '5.6 x 10^5',
        ],
        correctIndex: 1,
        explanation: '56 000 = 5.6 x 10^4.',
        misconception: 'Choosing 5.6 x 10^3 means you miscounted the decimal places by one.',
        tier: 'Foundation',
      },
      {
        id: 'writing-in-standard-form-2',
        topicSlug: 'writing-in-standard-form',
        question: 'Write 0.0042 in standard form.',
        options: [
          '4.2 x 10^(-2)',
          '4.2 x 10^(-3)',
          '42 x 10^(-4)',
          '4.2 x 10^3',
        ],
        correctIndex: 1,
        explanation: '0.0042 = 4.2 x 10^(-3). The decimal moves 3 places to the right.',
        misconception: 'Choosing 4.2 x 10^(-2) means you miscounted the number of zeros.',
        tier: 'Foundation',
      },
      {
        id: 'writing-in-standard-form-3',
        topicSlug: 'writing-in-standard-form',
        question: 'Write 710 000 000 in standard form.',
        options: [
          '7.1 x 10^7',
          '71 x 10^7',
          '7.1 x 10^8',
          '7.1 x 10^9',
        ],
        correctIndex: 2,
        explanation: '710 000 000 = 7.1 x 10^8.',
        misconception: 'Choosing 7.1 x 10^7 means you are off by one power of 10.',
        tier: 'Foundation',
      },
      {
        id: 'writing-in-standard-form-4',
        topicSlug: 'writing-in-standard-form',
        question: 'Write 0.000 005 9 in standard form.',
        options: [
          '5.9 x 10^(-5)',
          '5.9 x 10^(-6)',
          '59 x 10^(-7)',
          '5.9 x 10^(-7)',
        ],
        correctIndex: 1,
        explanation: '0.0000059 = 5.9 x 10^(-6). The decimal moves 6 places to the right.',
        misconception: 'Choosing 5.9 x 10^(-5) means you miscounted the number of places.',
        tier: 'Higher',
      },
      {
        id: 'writing-in-standard-form-5',
        topicSlug: 'writing-in-standard-form',
        question: 'A bacteria has mass 0.000 000 003 kg. Write this in standard form.',
        options: [
          '3 x 10^(-8)',
          '3 x 10^(-9)',
          '30 x 10^(-10)',
          '3 x 10^(-10)',
        ],
        correctIndex: 1,
        explanation: '0.000000003 = 3 x 10^(-9). The decimal moves 9 places.',
        misconception: 'Choosing 3 x 10^(-8) means you miscounted the zeros before the 3.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 18. calculating-with-standard-form                                  */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'calculating-with-standard-form',
    topicTitle: 'Calculating with Standard Form',
    strand: 'Number',
    questions: [
      {
        id: 'calculating-with-standard-form-1',
        topicSlug: 'calculating-with-standard-form',
        question: 'Calculate (3 x 10^4) x (2 x 10^3). Give your answer in standard form.',
        options: [
          '6 x 10^7',
          '5 x 10^7',
          '6 x 10^12',
          '6 x 10^8',
        ],
        correctIndex: 0,
        explanation: '3 x 2 = 6 and 10^4 x 10^3 = 10^7, so 6 x 10^7.',
        misconception: 'Choosing 6 x 10^12 means you multiplied the indices instead of adding them.',
        tier: 'Foundation',
      },
      {
        id: 'calculating-with-standard-form-2',
        topicSlug: 'calculating-with-standard-form',
        question: 'Calculate (8 x 10^5) / (4 x 10^2). Give your answer in standard form.',
        options: [
          '2 x 10^3',
          '2 x 10^7',
          '4 x 10^3',
          '2 x 10^2.5',
        ],
        correctIndex: 0,
        explanation: '8 / 4 = 2 and 10^5 / 10^2 = 10^3, so 2 x 10^3.',
        misconception: 'Choosing 2 x 10^7 means you added the indices instead of subtracting.',
        tier: 'Foundation',
      },
      {
        id: 'calculating-with-standard-form-3',
        topicSlug: 'calculating-with-standard-form',
        question: 'Calculate (5 x 10^3) + (3 x 10^3).',
        options: [
          '8 x 10^3',
          '15 x 10^3',
          '8 x 10^6',
          '8 x 10^9',
        ],
        correctIndex: 0,
        explanation: '5 + 3 = 8, keeping the same power: 8 x 10^3.',
        misconception: 'Choosing 8 x 10^6 means you added the powers together.',
        tier: 'Foundation',
      },
      {
        id: 'calculating-with-standard-form-4',
        topicSlug: 'calculating-with-standard-form',
        question: 'Calculate (6 x 10^5) x (7 x 10^3). Give your answer in standard form.',
        options: [
          '42 x 10^8',
          '4.2 x 10^8',
          '4.2 x 10^9',
          '4.2 x 10^15',
        ],
        correctIndex: 2,
        explanation: '6 x 7 = 42, 10^5 x 10^3 = 10^8. But 42 x 10^8 = 4.2 x 10^9.',
        misconception: 'Choosing 4.2 x 10^8 means you forgot to adjust 42 into standard form.',
        tier: 'Higher',
      },
      {
        id: 'calculating-with-standard-form-5',
        topicSlug: 'calculating-with-standard-form',
        question: 'Calculate (2.5 x 10^4) + (3 x 10^3). Give your answer in standard form.',
        options: [
          '5.5 x 10^4',
          '2.8 x 10^4',
          '5.5 x 10^7',
          '2.53 x 10^4',
        ],
        correctIndex: 1,
        explanation: '2.5 x 10^4 = 25000 and 3 x 10^3 = 3000. 25000 + 3000 = 28000 = 2.8 x 10^4.',
        misconception: 'Choosing 5.5 x 10^4 means you added 2.5 + 3 = 5.5 without matching powers first.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 19. order-of-operations-bidmas                                      */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'order-of-operations-bidmas',
    topicTitle: 'Order of Operations (BIDMAS)',
    strand: 'Number',
    questions: [
      {
        id: 'order-of-operations-bidmas-1',
        topicSlug: 'order-of-operations-bidmas',
        question: 'What is 3 + 4 x 2?',
        options: ['14', '11', '10', '24'],
        correctIndex: 1,
        explanation: 'Multiplication first: 4 x 2 = 8, then 3 + 8 = 11.',
        misconception: 'Choosing 14 means you added first (3 + 4 = 7) then multiplied.',
        tier: 'Foundation',
      },
      {
        id: 'order-of-operations-bidmas-2',
        topicSlug: 'order-of-operations-bidmas',
        question: 'What is 20 - 3 x 4?',
        options: ['68', '8', '32', '17'],
        correctIndex: 1,
        explanation: 'Multiplication first: 3 x 4 = 12, then 20 - 12 = 8.',
        misconception: 'Choosing 68 means you subtracted first (20 - 3 = 17) then multiplied by 4.',
        tier: 'Foundation',
      },
      {
        id: 'order-of-operations-bidmas-3',
        topicSlug: 'order-of-operations-bidmas',
        question: 'What is (5 + 3) x 2?',
        options: ['11', '16', '13', '30'],
        correctIndex: 1,
        explanation: 'Brackets first: 5 + 3 = 8, then 8 x 2 = 16.',
        misconception: 'Choosing 11 means you ignored the brackets and did 3 x 2 = 6, then 5 + 6 = 11.',
        tier: 'Foundation',
      },
      {
        id: 'order-of-operations-bidmas-4',
        topicSlug: 'order-of-operations-bidmas',
        question: 'What is 2 + 3^2 x 4?',
        options: ['44', '38', '56', '100'],
        correctIndex: 1,
        explanation: 'Indices first: 3^2 = 9. Then multiply: 9 x 4 = 36. Then add: 2 + 36 = 38.',
        misconception: 'Choosing 44 means you did 2 + 9 = 11 then 11 x 4, ignoring BIDMAS for multiplication.',
        tier: 'Higher',
      },
      {
        id: 'order-of-operations-bidmas-5',
        topicSlug: 'order-of-operations-bidmas',
        question: 'What is 48 / (2 x (3 + 1))?',
        options: ['6', '28', '96', '8'],
        correctIndex: 0,
        explanation: 'Inner bracket: 3 + 1 = 4. Then 2 x 4 = 8. Then 48 / 8 = 6.',
        misconception: 'Choosing 28 means you did 48/2 = 24 then added 3 + 1 = 4.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 20. prime-factorisation-hcf-and-lcm                                 */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'prime-factorisation-hcf-and-lcm',
    topicTitle: 'Prime Factorisation, HCF and LCM',
    strand: 'Number',
    questions: [
      {
        id: 'prime-factorisation-hcf-and-lcm-1',
        topicSlug: 'prime-factorisation-hcf-and-lcm',
        question: 'Write 60 as a product of prime factors.',
        options: [
          '2 x 3 x 10',
          '2^2 x 3 x 5',
          '4 x 15',
          '2 x 30',
        ],
        correctIndex: 1,
        explanation: '60 = 2 x 2 x 3 x 5 = 2^2 x 3 x 5.',
        misconception: 'Choosing 2 x 3 x 10 includes 10 which is not prime.',
        tier: 'Foundation',
      },
      {
        id: 'prime-factorisation-hcf-and-lcm-2',
        topicSlug: 'prime-factorisation-hcf-and-lcm',
        question: 'Write 72 as a product of prime factors.',
        options: [
          '2^3 x 3^2',
          '8 x 9',
          '2 x 36',
          '2^2 x 18',
        ],
        correctIndex: 0,
        explanation: '72 = 8 x 9 = 2^3 x 3^2.',
        misconception: 'Choosing 8 x 9 is correct factorisation but not into prime factors.',
        tier: 'Foundation',
      },
      {
        id: 'prime-factorisation-hcf-and-lcm-3',
        topicSlug: 'prime-factorisation-hcf-and-lcm',
        question: 'Find the HCF of 24 and 36.',
        options: ['6', '12', '72', '4'],
        correctIndex: 1,
        explanation: '24 = 2^3 x 3, 36 = 2^2 x 3^2. HCF = 2^2 x 3 = 12.',
        misconception: 'Choosing 6 means you stopped at a common factor that is not the highest.',
        tier: 'Foundation',
      },
      {
        id: 'prime-factorisation-hcf-and-lcm-4',
        topicSlug: 'prime-factorisation-hcf-and-lcm',
        question: 'Find the LCM of 12 and 18.',
        options: ['6', '36', '216', '72'],
        correctIndex: 1,
        explanation: '12 = 2^2 x 3, 18 = 2 x 3^2. LCM = 2^2 x 3^2 = 36.',
        misconception: 'Choosing 216 means you multiplied 12 x 18 instead of using prime factors.',
        tier: 'Higher',
      },
      {
        id: 'prime-factorisation-hcf-and-lcm-5',
        topicSlug: 'prime-factorisation-hcf-and-lcm',
        question: 'Find the LCM of 8 and 14.',
        options: ['2', '56', '112', '28'],
        correctIndex: 1,
        explanation: '8 = 2^3, 14 = 2 x 7. LCM = 2^3 x 7 = 56.',
        misconception: 'Choosing 112 means you multiplied 8 x 14 instead of finding the LCM.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 21. hcf-and-lcm                                                     */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'hcf-and-lcm',
    topicTitle: 'HCF and LCM',
    strand: 'Number',
    questions: [
      {
        id: 'hcf-and-lcm-1',
        topicSlug: 'hcf-and-lcm',
        question: 'Find the HCF of 16 and 24.',
        options: ['4', '8', '2', '48'],
        correctIndex: 1,
        explanation: 'Factors of 16: 1,2,4,8,16. Factors of 24: 1,2,3,4,6,8,12,24. HCF = 8.',
        misconception: 'Choosing 4 means you found a common factor but not the highest.',
        tier: 'Foundation',
      },
      {
        id: 'hcf-and-lcm-2',
        topicSlug: 'hcf-and-lcm',
        question: 'Find the LCM of 6 and 9.',
        options: ['3', '18', '54', '36'],
        correctIndex: 1,
        explanation: 'Multiples of 6: 6,12,18,... Multiples of 9: 9,18,... LCM = 18.',
        misconception: 'Choosing 54 means you multiplied 6 x 9 instead of finding the LCM.',
        tier: 'Foundation',
      },
      {
        id: 'hcf-and-lcm-3',
        topicSlug: 'hcf-and-lcm',
        question: 'Find the HCF of 30 and 45.',
        options: ['5', '15', '3', '90'],
        correctIndex: 1,
        explanation: '30 = 2 x 3 x 5, 45 = 3^2 x 5. HCF = 3 x 5 = 15.',
        misconception: 'Choosing 5 means you found a common factor but not the highest.',
        tier: 'Foundation',
      },
      {
        id: 'hcf-and-lcm-4',
        topicSlug: 'hcf-and-lcm',
        question: 'Find the LCM of 15 and 20.',
        options: ['5', '60', '300', '30'],
        correctIndex: 1,
        explanation: '15 = 3 x 5, 20 = 2^2 x 5. LCM = 2^2 x 3 x 5 = 60.',
        misconception: 'Choosing 300 means you multiplied 15 x 20 instead of using the LCM method.',
        tier: 'Higher',
      },
      {
        id: 'hcf-and-lcm-5',
        topicSlug: 'hcf-and-lcm',
        question: 'The HCF of two numbers is 6 and their LCM is 90. If one number is 18, what is the other?',
        options: ['15', '30', '5', '540'],
        correctIndex: 1,
        explanation: 'HCF x LCM = product of the two numbers. 6 x 90 = 540. 540 / 18 = 30.',
        misconception: 'Choosing 15 means you divided the LCM by the HCF (90/6) without using the product rule.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 22. factors-multiples-and-primes                                    */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'factors-multiples-and-primes',
    topicTitle: 'Factors, Multiples and Primes',
    strand: 'Number',
    questions: [
      {
        id: 'factors-multiples-and-primes-1',
        topicSlug: 'factors-multiples-and-primes',
        question: 'How many factors does 12 have?',
        options: ['4', '5', '6', '12'],
        correctIndex: 2,
        explanation: 'Factors of 12: 1, 2, 3, 4, 6, 12. That is 6 factors.',
        misconception: 'Choosing 4 means you missed some factor pairs.',
        tier: 'Foundation',
      },
      {
        id: 'factors-multiples-and-primes-2',
        topicSlug: 'factors-multiples-and-primes',
        question: 'Which of these is a prime number?',
        options: ['1', '9', '15', '23'],
        correctIndex: 3,
        explanation: '23 has exactly two factors: 1 and 23.',
        misconception: 'Choosing 1 is wrong because 1 is not a prime number (it has only one factor).',
        tier: 'Foundation',
      },
      {
        id: 'factors-multiples-and-primes-3',
        topicSlug: 'factors-multiples-and-primes',
        question: 'What is the 5th multiple of 7?',
        options: ['12', '28', '35', '42'],
        correctIndex: 2,
        explanation: 'Multiples of 7: 7, 14, 21, 28, 35. The 5th is 35.',
        misconception: 'Choosing 28 gives the 4th multiple; a common off-by-one error.',
        tier: 'Foundation',
      },
      {
        id: 'factors-multiples-and-primes-4',
        topicSlug: 'factors-multiples-and-primes',
        question: 'Which of these numbers is NOT prime?',
        options: ['29', '31', '33', '37'],
        correctIndex: 2,
        explanation: '33 = 3 x 11, so it is not prime.',
        misconception: 'Choosing 31 because odd numbers ending in 1 might seem non-prime, but 31 is prime.',
        tier: 'Higher',
      },
      {
        id: 'factors-multiples-and-primes-5',
        topicSlug: 'factors-multiples-and-primes',
        question: 'Find the sum of the prime factors of 30.',
        options: ['10', '11', '30', '8'],
        correctIndex: 0,
        explanation: '30 = 2 x 3 x 5. Sum = 2 + 3 + 5 = 10.',
        misconception: 'Choosing 30 means you added all the factors, not just the prime factors.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 23. fractions-of-amounts                                            */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'fractions-of-amounts',
    topicTitle: 'Fractions of Amounts',
    strand: 'Number',
    questions: [
      {
        id: 'fractions-of-amounts-1',
        topicSlug: 'fractions-of-amounts',
        question: 'What is 1/4 of 60?',
        options: ['20', '15', '12', '4'],
        correctIndex: 1,
        explanation: '60 / 4 = 15.',
        misconception: 'Choosing 20 means you divided by 3 instead of 4.',
        tier: 'Foundation',
      },
      {
        id: 'fractions-of-amounts-2',
        topicSlug: 'fractions-of-amounts',
        question: 'What is 2/5 of 35?',
        options: ['7', '10', '14', '17.5'],
        correctIndex: 2,
        explanation: '1/5 of 35 = 7, so 2/5 = 7 x 2 = 14.',
        misconception: 'Choosing 7 means you found 1/5 but forgot to multiply by 2.',
        tier: 'Foundation',
      },
      {
        id: 'fractions-of-amounts-3',
        topicSlug: 'fractions-of-amounts',
        question: 'What is 3/8 of 48?',
        options: ['6', '16', '18', '24'],
        correctIndex: 2,
        explanation: '1/8 of 48 = 6, so 3/8 = 6 x 3 = 18.',
        misconception: 'Choosing 6 means you found 1/8 but forgot to multiply by 3.',
        tier: 'Foundation',
      },
      {
        id: 'fractions-of-amounts-4',
        topicSlug: 'fractions-of-amounts',
        question: 'What is 5/6 of 72?',
        options: ['12', '60', '36', '84'],
        correctIndex: 1,
        explanation: '1/6 of 72 = 12, so 5/6 = 12 x 5 = 60.',
        misconception: 'Choosing 12 means you found 1/6 but forgot to multiply by 5.',
        tier: 'Higher',
      },
      {
        id: 'fractions-of-amounts-5',
        topicSlug: 'fractions-of-amounts',
        question: 'A bag contains 120 sweets. Tom eats 3/8 of them. How many does he have left?',
        options: ['45', '75', '80', '40'],
        correctIndex: 1,
        explanation: '3/8 of 120 = 45. Left = 120 - 45 = 75.',
        misconception: 'Choosing 45 gives how many he ate, not how many are left.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 24. equivalent-fractions-and-simplifying                            */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'equivalent-fractions-and-simplifying',
    topicTitle: 'Equivalent Fractions',
    strand: 'Number',
    questions: [
      {
        id: 'equivalent-fractions-and-simplifying-1',
        topicSlug: 'equivalent-fractions-and-simplifying',
        question: 'Which fraction is equivalent to 2/3?',
        options: ['4/9', '6/9', '4/6', '3/4'],
        correctIndex: 1,
        explanation: '2/3 x 3/3 = 6/9.',
        misconception: 'Choosing 4/9 means you multiplied top and bottom by different numbers.',
        tier: 'Foundation',
      },
      {
        id: 'equivalent-fractions-and-simplifying-2',
        topicSlug: 'equivalent-fractions-and-simplifying',
        question: 'Simplify 15/25.',
        options: ['3/5', '1/5', '5/5', '15/25'],
        correctIndex: 0,
        explanation: 'Divide both by 5: 15/25 = 3/5.',
        misconception: 'Choosing 1/5 means you divided the numerator by 15 and the denominator by 5.',
        tier: 'Foundation',
      },
      {
        id: 'equivalent-fractions-and-simplifying-3',
        topicSlug: 'equivalent-fractions-and-simplifying',
        question: 'Simplify 24/36.',
        options: ['12/18', '4/6', '2/3', '6/9'],
        correctIndex: 2,
        explanation: 'HCF of 24 and 36 is 12. 24/36 = 2/3.',
        misconception: 'Choosing 12/18 or 4/6 means you did not fully simplify.',
        tier: 'Foundation',
      },
      {
        id: 'equivalent-fractions-and-simplifying-4',
        topicSlug: 'equivalent-fractions-and-simplifying',
        question: 'Which fraction is NOT equivalent to 5/8?',
        options: ['10/16', '15/24', '20/32', '25/42'],
        correctIndex: 3,
        explanation: '25/42 cannot be reduced to 5/8. The others all simplify to 5/8.',
        misconception: 'Choosing 20/32 and thinking it is not equivalent (it is: divide by 4).',
        tier: 'Higher',
      },
      {
        id: 'equivalent-fractions-and-simplifying-5',
        topicSlug: 'equivalent-fractions-and-simplifying',
        question: 'Simplify 42/56.',
        options: ['6/8', '21/28', '3/4', '7/8'],
        correctIndex: 2,
        explanation: 'HCF of 42 and 56 is 14. 42/56 = 3/4.',
        misconception: 'Choosing 21/28 means you only divided by 2, not fully simplifying.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 25. converting-fractions-decimals-percentages                       */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'converting-fractions-decimals-percentages',
    topicTitle: 'Converting FDP',
    strand: 'Number',
    questions: [
      {
        id: 'converting-fractions-decimals-percentages-1',
        topicSlug: 'converting-fractions-decimals-percentages',
        question: 'Convert 3/8 to a decimal.',
        options: ['0.38', '0.375', '0.35', '0.83'],
        correctIndex: 1,
        explanation: '3 / 8 = 0.375.',
        misconception: 'Choosing 0.38 means you placed the 3 and 8 side by side as digits.',
        tier: 'Foundation',
      },
      {
        id: 'converting-fractions-decimals-percentages-2',
        topicSlug: 'converting-fractions-decimals-percentages',
        question: 'Convert 0.6 to a fraction in its simplest form.',
        options: ['6/10', '3/5', '1/6', '6/100'],
        correctIndex: 1,
        explanation: '0.6 = 6/10 = 3/5.',
        misconception: 'Choosing 6/10 is correct but not fully simplified.',
        tier: 'Foundation',
      },
      {
        id: 'converting-fractions-decimals-percentages-3',
        topicSlug: 'converting-fractions-decimals-percentages',
        question: 'Convert 45% to a fraction in its simplest form.',
        options: ['45/100', '9/20', '4/5', '9/25'],
        correctIndex: 1,
        explanation: '45/100 = 9/20.',
        misconception: 'Choosing 45/100 is correct but not simplified.',
        tier: 'Foundation',
      },
      {
        id: 'converting-fractions-decimals-percentages-4',
        topicSlug: 'converting-fractions-decimals-percentages',
        question: 'Convert 7/20 to a percentage.',
        options: ['72%', '35%', '7.2%', '14%'],
        correctIndex: 1,
        explanation: '7/20 = 0.35 = 35%.',
        misconception: 'Choosing 14% means you multiplied 7 by 2 but divided by 10 instead of converting properly.',
        tier: 'Higher',
      },
      {
        id: 'converting-fractions-decimals-percentages-5',
        topicSlug: 'converting-fractions-decimals-percentages',
        question: 'Put these in order from smallest to largest: 0.72, 3/4, 70%.',
        options: [
          '0.72, 70%, 3/4',
          '70%, 0.72, 3/4',
          '3/4, 0.72, 70%',
          '70%, 3/4, 0.72',
        ],
        correctIndex: 1,
        explanation: '70% = 0.70, 0.72, 3/4 = 0.75. So order is 70%, 0.72, 3/4.',
        misconception: 'Choosing 0.72, 70%, 3/4 means you think 0.72 < 0.70.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 26. recurring-decimals-to-fractions                                 */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'recurring-decimals-to-fractions',
    topicTitle: 'Recurring Decimals to Fractions',
    strand: 'Number',
    questions: [
      {
        id: 'recurring-decimals-to-fractions-1',
        topicSlug: 'recurring-decimals-to-fractions',
        question: 'Convert 0.333... (0.3 recurring) to a fraction.',
        options: ['3/10', '1/3', '33/100', '3/9'],
        correctIndex: 1,
        explanation: 'Let x = 0.333... Then 10x = 3.333... so 9x = 3, x = 1/3.',
        misconception: 'Choosing 3/10 means you treated it as a terminating decimal.',
        tier: 'Foundation',
      },
      {
        id: 'recurring-decimals-to-fractions-2',
        topicSlug: 'recurring-decimals-to-fractions',
        question: 'Convert 0.666... (0.6 recurring) to a fraction.',
        options: ['6/10', '3/5', '2/3', '6/9'],
        correctIndex: 2,
        explanation: 'x = 0.666..., 10x = 6.666..., 9x = 6, x = 6/9 = 2/3.',
        misconception: 'Choosing 3/5 = 0.6 exactly, confusing a terminating with a recurring decimal.',
        tier: 'Foundation',
      },
      {
        id: 'recurring-decimals-to-fractions-3',
        topicSlug: 'recurring-decimals-to-fractions',
        question: 'Convert 0.1111... (0.1 recurring) to a fraction.',
        options: ['1/10', '1/9', '1/11', '11/100'],
        correctIndex: 1,
        explanation: 'x = 0.111..., 10x = 1.111..., 9x = 1, x = 1/9.',
        misconception: 'Choosing 1/10 means you treated it as a terminating decimal.',
        tier: 'Foundation',
      },
      {
        id: 'recurring-decimals-to-fractions-4',
        topicSlug: 'recurring-decimals-to-fractions',
        question: 'Convert 0.272727... (0.27 recurring) to a fraction.',
        options: ['27/100', '27/99', '3/11', '27/90'],
        correctIndex: 2,
        explanation: 'x = 0.2727..., 100x = 27.2727..., 99x = 27, x = 27/99 = 3/11.',
        misconception: 'Choosing 27/100 means you treated it as a terminating decimal.',
        tier: 'Higher',
      },
      {
        id: 'recurring-decimals-to-fractions-5',
        topicSlug: 'recurring-decimals-to-fractions',
        question: 'Convert 0.1666... (0.16 recurring, with only the 6 recurring) to a fraction.',
        options: ['16/100', '16/99', '1/6', '15/90'],
        correctIndex: 2,
        explanation: 'x = 0.1666..., 10x = 1.666... = 1 + 2/3 = 5/3. So x = 5/30 = 1/6.',
        misconception: 'Choosing 16/99 means you treated both digits as recurring.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 27. rounding-decimal-places-significant-figures                     */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'rounding-decimal-places-significant-figures',
    topicTitle: 'Rounding',
    strand: 'Number',
    questions: [
      {
        id: 'rounding-decimal-places-significant-figures-1',
        topicSlug: 'rounding-decimal-places-significant-figures',
        question: 'Round 3.647 to 1 decimal place.',
        options: ['3.6', '3.7', '4.0', '3.65'],
        correctIndex: 0,
        explanation: 'To round to 1dp, look at the 2nd decimal digit (4). Since 4 < 5, round down: 3.6.',
        misconception: 'Choosing 3.7 means you looked at the third decimal digit (7) instead of the second (4).',
        tier: 'Foundation',
      },
      {
        id: 'rounding-decimal-places-significant-figures-2',
        topicSlug: 'rounding-decimal-places-significant-figures',
        question: 'Round 0.03651 to 2 significant figures.',
        options: ['0.04', '0.036', '0.037', '0.0365'],
        correctIndex: 2,
        explanation: 'First two significant figures are 3 and 6. The next digit is 5, so round up: 0.037.',
        misconception: 'Choosing 0.04 means you counted zeros as significant figures.',
        tier: 'Foundation',
      },
      {
        id: 'rounding-decimal-places-significant-figures-3',
        topicSlug: 'rounding-decimal-places-significant-figures',
        question: 'Round 2856 to 2 significant figures.',
        options: ['2800', '2900', '2860', '29'],
        correctIndex: 1,
        explanation: 'First two SF are 2 and 8. Next digit is 5, so round up: 2900.',
        misconception: 'Choosing 2800 means you rounded down when the digit was exactly 5.',
        tier: 'Foundation',
      },
      {
        id: 'rounding-decimal-places-significant-figures-4',
        topicSlug: 'rounding-decimal-places-significant-figures',
        question: 'Round 0.004972 to 3 significant figures.',
        options: ['0.00497', '0.005', '0.00500', '0.004'],
        correctIndex: 0,
        explanation: 'First 3 SF are 4, 9, 7. Next digit is 2, so round down: 0.00497.',
        misconception: 'Choosing 0.005 means you only found 1 significant figure, mistaking zeros as significant.',
        tier: 'Higher',
      },
      {
        id: 'rounding-decimal-places-significant-figures-5',
        topicSlug: 'rounding-decimal-places-significant-figures',
        question: 'Truncate 7.389 to 2 decimal places.',
        options: ['7.38', '7.39', '7.40', '7.3'],
        correctIndex: 0,
        explanation: 'Truncation simply cuts off: 7.389 truncated to 2dp is 7.38 (no rounding).',
        misconception: 'Choosing 7.39 means you rounded up instead of truncating.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 28. surds                                                           */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'surds',
    topicTitle: 'Surds',
    strand: 'Number',
    questions: [
      {
        id: 'surds-1',
        topicSlug: 'surds',
        question: 'Simplify sqrt(50).',
        options: ['5sqrt(2)', '25sqrt(2)', '2sqrt(25)', '10sqrt(5)'],
        correctIndex: 0,
        explanation: 'sqrt(50) = sqrt(25 x 2) = 5sqrt(2).',
        misconception: 'Choosing 25sqrt(2) means you forgot to square root the 25.',
        tier: 'Foundation',
      },
      {
        id: 'surds-2',
        topicSlug: 'surds',
        question: 'What is sqrt(3) x sqrt(3)?',
        options: ['sqrt(9)', '3', 'sqrt(6)', '9'],
        correctIndex: 1,
        explanation: 'sqrt(3) x sqrt(3) = 3.',
        misconception: 'Choosing 9 means you squared 3 instead of recognising sqrt(3) x sqrt(3) = 3.',
        tier: 'Foundation',
      },
      {
        id: 'surds-3',
        topicSlug: 'surds',
        question: 'Simplify sqrt(72).',
        options: ['6sqrt(2)', '8sqrt(3)', '2sqrt(18)', '36sqrt(2)'],
        correctIndex: 0,
        explanation: 'sqrt(72) = sqrt(36 x 2) = 6sqrt(2).',
        misconception: 'Choosing 2sqrt(18) is not fully simplified because sqrt(18) = 3sqrt(2).',
        tier: 'Foundation',
      },
      {
        id: 'surds-4',
        topicSlug: 'surds',
        question: 'What is sqrt(5) x sqrt(20)?',
        options: ['sqrt(100)', '10', '5sqrt(4)', 'sqrt(25)'],
        correctIndex: 1,
        explanation: 'sqrt(5) x sqrt(20) = sqrt(100) = 10.',
        misconception: 'Choosing sqrt(25) = 5 means you added 5 + 20 = 25 instead of multiplying.',
        tier: 'Higher',
      },
      {
        id: 'surds-5',
        topicSlug: 'surds',
        question: 'Express sqrt(12) + sqrt(27) in the form a*sqrt(3).',
        options: ['5sqrt(3)', '39sqrt(3)', 'sqrt(39)', '7sqrt(3)'],
        correctIndex: 0,
        explanation: 'sqrt(12) = 2sqrt(3) and sqrt(27) = 3sqrt(3). So 2sqrt(3) + 3sqrt(3) = 5sqrt(3).',
        misconception: 'Choosing sqrt(39) means you added 12 + 27 = 39 and put it under one square root.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 29. simplifying-surds                                               */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'simplifying-surds',
    topicTitle: 'Simplifying Surds',
    strand: 'Number',
    questions: [
      {
        id: 'simplifying-surds-1',
        topicSlug: 'simplifying-surds',
        question: 'Simplify sqrt(32).',
        options: ['4sqrt(2)', '2sqrt(8)', '8sqrt(2)', '16sqrt(2)'],
        correctIndex: 0,
        explanation: 'sqrt(32) = sqrt(16 x 2) = 4sqrt(2).',
        misconception: 'Choosing 2sqrt(8) is not fully simplified since sqrt(8) = 2sqrt(2).',
        tier: 'Foundation',
      },
      {
        id: 'simplifying-surds-2',
        topicSlug: 'simplifying-surds',
        question: 'Simplify sqrt(45).',
        options: ['5sqrt(3)', '3sqrt(5)', '9sqrt(5)', '15'],
        correctIndex: 1,
        explanation: 'sqrt(45) = sqrt(9 x 5) = 3sqrt(5).',
        misconception: 'Choosing 5sqrt(3) mixes up which factor is the perfect square.',
        tier: 'Foundation',
      },
      {
        id: 'simplifying-surds-3',
        topicSlug: 'simplifying-surds',
        question: 'Simplify sqrt(200).',
        options: ['10sqrt(2)', '2sqrt(100)', '100sqrt(2)', '20sqrt(5)'],
        correctIndex: 0,
        explanation: 'sqrt(200) = sqrt(100 x 2) = 10sqrt(2).',
        misconception: 'Choosing 2sqrt(100) = 2 x 10 = 20 is not in surd form.',
        tier: 'Foundation',
      },
      {
        id: 'simplifying-surds-4',
        topicSlug: 'simplifying-surds',
        question: 'Simplify 3sqrt(8).',
        options: ['sqrt(24)', '6sqrt(2)', '24sqrt(2)', '3sqrt(4)'],
        correctIndex: 1,
        explanation: 'sqrt(8) = 2sqrt(2), so 3 x 2sqrt(2) = 6sqrt(2).',
        misconception: 'Choosing sqrt(24) means you put everything under one root incorrectly.',
        tier: 'Higher',
      },
      {
        id: 'simplifying-surds-5',
        topicSlug: 'simplifying-surds',
        question: 'Simplify sqrt(75) - sqrt(12).',
        options: ['sqrt(63)', '3sqrt(3)', '3sqrt(5)', '7sqrt(3)'],
        correctIndex: 1,
        explanation: 'sqrt(75) = 5sqrt(3) and sqrt(12) = 2sqrt(3). 5sqrt(3) - 2sqrt(3) = 3sqrt(3).',
        misconception: 'Choosing sqrt(63) means you subtracted 75 - 12 = 63 inside the root.',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 30. rationalising-the-denominator                                   */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'rationalising-the-denominator',
    topicTitle: 'Rationalising the Denominator',
    strand: 'Number',
    questions: [
      {
        id: 'rationalising-the-denominator-1',
        topicSlug: 'rationalising-the-denominator',
        question: 'Rationalise the denominator of 1/sqrt(5).',
        options: ['1/5', 'sqrt(5)/5', '5/sqrt(5)', 'sqrt(5)'],
        correctIndex: 1,
        explanation: 'Multiply top and bottom by sqrt(5): sqrt(5)/5.',
        misconception: 'Choosing 1/5 means you squared the denominator without adjusting the numerator.',
        tier: 'Foundation',
      },
      {
        id: 'rationalising-the-denominator-2',
        topicSlug: 'rationalising-the-denominator',
        question: 'Rationalise the denominator of 6/sqrt(3).',
        options: ['6/3', '2sqrt(3)', '6sqrt(3)', '6sqrt(3)/3'],
        correctIndex: 1,
        explanation: '6/sqrt(3) x sqrt(3)/sqrt(3) = 6sqrt(3)/3 = 2sqrt(3).',
        misconception: 'Choosing 6/3 = 2 means you just squared the denominator and divided.',
        tier: 'Foundation',
      },
      {
        id: 'rationalising-the-denominator-3',
        topicSlug: 'rationalising-the-denominator',
        question: 'Rationalise the denominator of 4/sqrt(2).',
        options: ['2', '4sqrt(2)/2', '2sqrt(2)', '4/2'],
        correctIndex: 2,
        explanation: '4/sqrt(2) x sqrt(2)/sqrt(2) = 4sqrt(2)/2 = 2sqrt(2).',
        misconception: 'Choosing 2 means you just divided 4 by 2 without rationalising.',
        tier: 'Foundation',
      },
      {
        id: 'rationalising-the-denominator-4',
        topicSlug: 'rationalising-the-denominator',
        question: 'Rationalise the denominator of 5/(3 + sqrt(2)).',
        options: [
          '5(3 - sqrt(2))/7',
          '5(3 + sqrt(2))/7',
          '5(3 - sqrt(2))/11',
          '(15 - 5sqrt(2))/11',
        ],
        correctIndex: 0,
        explanation: 'Multiply by (3 - sqrt(2))/(3 - sqrt(2)): denominator = 9 - 2 = 7. Result = 5(3 - sqrt(2))/7.',
        misconception: 'Choosing 5(3 - sqrt(2))/11 means you added 9 + 2 = 11 instead of subtracting.',
        tier: 'Higher',
      },
      {
        id: 'rationalising-the-denominator-5',
        topicSlug: 'rationalising-the-denominator',
        question: 'Rationalise the denominator of 1/(sqrt(3) - 1).',
        options: [
          '(sqrt(3) + 1)/2',
          'sqrt(3) + 1',
          '(sqrt(3) - 1)/2',
          '1/(3 - 1)',
        ],
        correctIndex: 0,
        explanation: 'Multiply by (sqrt(3) + 1)/(sqrt(3) + 1): (sqrt(3) + 1)/(3 - 1) = (sqrt(3) + 1)/2.',
        misconception: 'Choosing sqrt(3) + 1 means you forgot to divide by the denominator result (2).',
        tier: 'Higher',
      },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* 31. bounds-and-error-intervals                                      */
  /* ------------------------------------------------------------------ */
  {
    topicSlug: 'bounds-and-error-intervals',
    topicTitle: 'Bounds and Error Intervals',
    strand: 'Number',
    questions: [
      {
        id: 'bounds-and-error-intervals-1',
        topicSlug: 'bounds-and-error-intervals',
        question: 'A length is measured as 5.7 cm to 1 decimal place. What is the lower bound?',
        options: ['5.6', '5.65', '5.60', '5.69'],
        correctIndex: 1,
        explanation: 'Rounded to 1dp, the lower bound is 5.65 cm.',
        misconception: 'Choosing 5.6 means you subtracted 0.1 instead of 0.05.',
        tier: 'Foundation',
      },
      {
        id: 'bounds-and-error-intervals-2',
        topicSlug: 'bounds-and-error-intervals',
        question: 'A mass is given as 3.2 kg to 1 decimal place. What is the upper bound?',
        options: ['3.3', '3.25', '3.29', '3.20'],
        correctIndex: 1,
        explanation: 'Upper bound = 3.25 kg (values up to but not including 3.25 round to 3.2).',
        misconception: 'Choosing 3.3 means you added 0.1 instead of 0.05.',
        tier: 'Foundation',
      },
      {
        id: 'bounds-and-error-intervals-3',
        topicSlug: 'bounds-and-error-intervals',
        question: 'A distance is 400 m to the nearest 10 m. Write the error interval.',
        options: [
          '390 <= d < 410',
          '395 <= d < 405',
          '400 <= d < 410',
          '399 <= d < 401',
        ],
        correctIndex: 1,
        explanation: 'Nearest 10: half of 10 is 5, so 395 <= d < 405.',
        misconception: 'Choosing 390 <= d < 410 means you used 10 either side instead of 5.',
        tier: 'Foundation',
      },
      {
        id: 'bounds-and-error-intervals-4',
        topicSlug: 'bounds-and-error-intervals',
        question: 'x = 7.2 (1 dp) and y = 3.8 (1 dp). Find the lower bound of x - y.',
        options: ['3.4', '3.3', '3.35', '3.45'],
        correctIndex: 1,
        explanation: 'Lower bound of x = 7.15, upper bound of y = 3.85. Lower bound of x - y = 7.15 - 3.85 = 3.3.',
        misconception: 'Choosing 3.4 means you subtracted the rounded values instead of using LB and UB.',
        tier: 'Higher',
      },
      {
        id: 'bounds-and-error-intervals-5',
        topicSlug: 'bounds-and-error-intervals',
        question: 'p = 12.4 (1 dp) and q = 8.7 (1 dp). Find the upper bound of p + q.',
        options: ['21.1', '21.15', '21.2', '21.05'],
        correctIndex: 2,
        explanation: 'Upper bound of p = 12.45, upper bound of q = 8.75. Upper bound of p + q = 12.45 + 8.75 = 21.2.',
        misconception: 'Choosing 21.1 means you added the rounded values instead of the upper bounds.',
        tier: 'Higher',
      },
    ],
  },
]
