import type { TopicMCQSet } from './types'

export const RATIO_MCQS: TopicMCQSet[] = [
  // ─── 1. Ratio Basics and Sharing ────────────────────────────────────
  {
    topicSlug: 'ratio-basics-and-sharing',
    topicTitle: 'Ratio Basics and Sharing',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'ratio-basics-and-sharing-1',
        topicSlug: 'ratio-basics-and-sharing',
        question: 'Share £60 in the ratio 2:3. What is the larger share?',
        options: ['£36', '£30', '£24', '£40'],
        correctIndex: 0,
        explanation: 'Total parts = 2 + 3 = 5. Each part = £60 ÷ 5 = £12. Larger share = 3 × £12 = £36.',
        misconception: 'Choosing £30 means dividing £60 by 2 instead of finding total parts.',
        tier: 'Both',
      },
      {
        id: 'ratio-basics-and-sharing-2',
        topicSlug: 'ratio-basics-and-sharing',
        question: 'Write the ratio 12:8 in its simplest form.',
        options: ['3:2', '6:4', '4:3', '2:3'],
        correctIndex: 0,
        explanation: 'HCF of 12 and 8 is 4. 12 ÷ 4 = 3, 8 ÷ 4 = 2, so 3:2.',
        misconception: 'Choosing 6:4 means only dividing by 2 instead of fully simplifying.',
        tier: 'Both',
      },
      {
        id: 'ratio-basics-and-sharing-3',
        topicSlug: 'ratio-basics-and-sharing',
        question: 'The ratio of cats to dogs is 5:3. There are 15 cats. How many dogs are there?',
        options: ['9', '3', '25', '5'],
        correctIndex: 0,
        explanation: 'Scale factor = 15 ÷ 5 = 3. Dogs = 3 × 3 = 9.',
        misconception: 'Choosing 3 means using the ratio number directly without scaling.',
        tier: 'Both',
      },
      {
        id: 'ratio-basics-and-sharing-4',
        topicSlug: 'ratio-basics-and-sharing',
        question: 'Share 40 sweets in the ratio 3:5. How many does the smaller share get?',
        options: ['15', '24', '25', '20'],
        correctIndex: 0,
        explanation: 'Total parts = 3 + 5 = 8. Each part = 40 ÷ 8 = 5. Smaller share = 3 × 5 = 15.',
        misconception: 'Choosing 25 means dividing 40 by the ratio number 8 incorrectly and multiplying by 5.',
        tier: 'Both',
      },
      {
        id: 'ratio-basics-and-sharing-5',
        topicSlug: 'ratio-basics-and-sharing',
        question: 'A recipe uses flour and sugar in the ratio 4:1. If you use 200 g of flour, how much sugar do you need?',
        options: ['50 g', '100 g', '40 g', '800 g'],
        correctIndex: 0,
        explanation: 'Scale factor = 200 ÷ 4 = 50. Sugar = 1 × 50 = 50 g.',
        misconception: 'Choosing 100 g means dividing 200 by 2 instead of by the ratio part for flour.',
        tier: 'Both',
      },
    ],
  },

  // ─── 2. Sharing in a Ratio ──────────────────────────────────────────
  {
    topicSlug: 'sharing-in-a-ratio',
    topicTitle: 'Sharing in a Ratio',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'sharing-in-a-ratio-1',
        topicSlug: 'sharing-in-a-ratio',
        question: 'Share £100 in the ratio 3:2. How much does the larger share receive?',
        options: ['£60', '£50', '£40', '£33'],
        correctIndex: 0,
        explanation: 'Total parts = 5. Each part = £100 ÷ 5 = £20. Larger share = 3 × £20 = £60.',
        misconception: 'Choosing £50 means splitting equally instead of using the ratio.',
        tier: 'Both',
      },
      {
        id: 'sharing-in-a-ratio-2',
        topicSlug: 'sharing-in-a-ratio',
        question: 'Share 72 in the ratio 5:3:1. What is the largest share?',
        options: ['40', '24', '36', '8'],
        correctIndex: 0,
        explanation: 'Total parts = 5 + 3 + 1 = 9. Each part = 72 ÷ 9 = 8. Largest = 5 × 8 = 40.',
        misconception: 'Choosing 24 means finding 3 parts instead of 5 parts.',
        tier: 'Both',
      },
      {
        id: 'sharing-in-a-ratio-3',
        topicSlug: 'sharing-in-a-ratio',
        question: 'Amy and Ben share money in the ratio 7:3. Amy gets £35. How much does Ben get?',
        options: ['£15', '£21', '£10', '£5'],
        correctIndex: 0,
        explanation: 'Scale factor = £35 ÷ 7 = £5. Ben = 3 × £5 = £15.',
        misconception: 'Choosing £21 means subtracting 35 − 14 instead of finding one part then multiplying.',
        tier: 'Both',
      },
      {
        id: 'sharing-in-a-ratio-4',
        topicSlug: 'sharing-in-a-ratio',
        question: 'Share £48 in the ratio 1:2:3. What is the middle share?',
        options: ['£16', '£24', '£8', '£12'],
        correctIndex: 0,
        explanation: 'Total parts = 1 + 2 + 3 = 6. Each part = £48 ÷ 6 = £8. Middle share = 2 × £8 = £16.',
        misconception: 'Choosing £24 means confusing the middle share with the largest share.',
        tier: 'Both',
      },
      {
        id: 'sharing-in-a-ratio-5',
        topicSlug: 'sharing-in-a-ratio',
        question: 'Three friends share a bill in the ratio 2:3:5. The total bill is £200. How much does the person paying the most contribute?',
        options: ['£100', '£60', '£80', '£40'],
        correctIndex: 0,
        explanation: 'Total parts = 2 + 3 + 5 = 10. Each part = £200 ÷ 10 = £20. Largest = 5 × £20 = £100.',
        misconception: 'Choosing £60 means finding 3 parts instead of 5 parts.',
        tier: 'Both',
      },
    ],
  },

  // ─── 3. Simplifying Ratios ──────────────────────────────────────────
  {
    topicSlug: 'simplifying-ratios',
    topicTitle: 'Simplifying Ratios',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'simplifying-ratios-1',
        topicSlug: 'simplifying-ratios',
        question: 'Simplify the ratio 18:24.',
        options: ['3:4', '9:12', '6:8', '2:3'],
        correctIndex: 0,
        explanation: 'HCF of 18 and 24 is 6. 18 ÷ 6 = 3, 24 ÷ 6 = 4. Simplified ratio is 3:4.',
        misconception: 'Choosing 9:12 means only dividing by 2, not fully simplifying.',
        tier: 'Both',
      },
      {
        id: 'simplifying-ratios-2',
        topicSlug: 'simplifying-ratios',
        question: 'Simplify 0.5 : 1.5.',
        options: ['1:3', '5:15', '1:2', '3:1'],
        correctIndex: 0,
        explanation: 'Multiply both by 2 to get 1:3. This is already in simplest form.',
        misconception: 'Choosing 1:2 means halving the larger value instead of scaling both equally.',
        tier: 'Both',
      },
      {
        id: 'simplifying-ratios-3',
        topicSlug: 'simplifying-ratios',
        question: 'Simplify the ratio 45:30:15.',
        options: ['3:2:1', '9:6:3', '15:10:5', '6:4:2'],
        correctIndex: 0,
        explanation: 'HCF of 45, 30, 15 is 15. Dividing each by 15 gives 3:2:1.',
        misconception: 'Choosing 9:6:3 means dividing by 5 instead of 15.',
        tier: 'Both',
      },
      {
        id: 'simplifying-ratios-4',
        topicSlug: 'simplifying-ratios',
        question: 'Write 250 ml to 1 litre as a ratio in its simplest form.',
        options: ['1:4', '250:1', '25:100', '1:250'],
        correctIndex: 0,
        explanation: '1 litre = 1000 ml. Ratio = 250:1000. HCF = 250. Simplified = 1:4.',
        misconception: 'Choosing 250:1 means not converting to the same units first.',
        tier: 'Both',
      },
      {
        id: 'simplifying-ratios-5',
        topicSlug: 'simplifying-ratios',
        question: 'Simplify the ratio ¾ : ½.',
        options: ['3:2', '4:2', '3:4', '1:2'],
        correctIndex: 0,
        explanation: 'Multiply both by 4: ¾ × 4 = 3, ½ × 4 = 2. Ratio = 3:2.',
        misconception: 'Choosing 3:4 means using the numerator and denominator of the first fraction only.',
        tier: 'Both',
      },
    ],
  },

  // ─── 4. Ratio and Fractions ─────────────────────────────────────────
  {
    topicSlug: 'ratio-and-fractions',
    topicTitle: 'Ratio and Fractions',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'ratio-and-fractions-1',
        topicSlug: 'ratio-and-fractions',
        question: 'The ratio of red to blue beads is 2:5. What fraction of the beads are red?',
        options: ['2/7', '2/5', '5/7', '5/2'],
        correctIndex: 0,
        explanation: 'Total parts = 2 + 5 = 7. Fraction of red = 2/7.',
        misconception: 'Choosing 2/5 means using the other part as the denominator instead of the total.',
        tier: 'Both',
      },
      {
        id: 'ratio-and-fractions-2',
        topicSlug: 'ratio-and-fractions',
        question: 'In a class, the ratio of boys to girls is 3:5. What fraction of the class are girls?',
        options: ['5/8', '3/5', '5/3', '3/8'],
        correctIndex: 0,
        explanation: 'Total parts = 3 + 5 = 8. Fraction of girls = 5/8.',
        misconception: 'Choosing 3/5 means writing the ratio as a fraction without adding total parts.',
        tier: 'Both',
      },
      {
        id: 'ratio-and-fractions-3',
        topicSlug: 'ratio-and-fractions',
        question: '¼ of a bag of marbles are green. The rest are yellow. What is the ratio of green to yellow?',
        options: ['1:3', '1:4', '3:1', '1:2'],
        correctIndex: 0,
        explanation: 'Green = ¼, Yellow = ¾. Ratio = ¼ : ¾ = 1:3.',
        misconception: 'Choosing 1:4 means using the denominator instead of the remaining fraction.',
        tier: 'Both',
      },
      {
        id: 'ratio-and-fractions-4',
        topicSlug: 'ratio-and-fractions',
        question: 'The ratio of apples to oranges is 4:1. There are 30 fruits total. How many apples are there?',
        options: ['24', '6', '20', '15'],
        correctIndex: 0,
        explanation: 'Total parts = 4 + 1 = 5. Each part = 30 ÷ 5 = 6. Apples = 4 × 6 = 24.',
        misconception: 'Choosing 6 means finding one part but forgetting to multiply by 4.',
        tier: 'Both',
      },
      {
        id: 'ratio-and-fractions-5',
        topicSlug: 'ratio-and-fractions',
        question: 'A drink is mixed in the ratio 2:3 (juice to water). What fraction of the drink is water?',
        options: ['3/5', '2/3', '2/5', '3/2'],
        correctIndex: 0,
        explanation: 'Total parts = 2 + 3 = 5. Fraction of water = 3/5.',
        misconception: 'Choosing 2/3 means writing the ratio as a fraction without using the total.',
        tier: 'Both',
      },
    ],
  },

  // ─── 5. Ratio Given Difference ──────────────────────────────────────
  {
    topicSlug: 'ratio-given-difference',
    topicTitle: 'Ratio Given Difference',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'ratio-given-difference-1',
        topicSlug: 'ratio-given-difference',
        question: 'Two numbers are in the ratio 3:7. The difference between them is 20. What is the smaller number?',
        options: ['15', '35', '12', '10'],
        correctIndex: 0,
        explanation: 'Difference in parts = 7 − 3 = 4. One part = 20 ÷ 4 = 5. Smaller number = 3 × 5 = 15.',
        misconception: 'Choosing 12 means dividing 20 by something other than the part difference.',
        tier: 'Both',
      },
      {
        id: 'ratio-given-difference-2',
        topicSlug: 'ratio-given-difference',
        question: 'Ali and Ben share money in the ratio 5:2. Ali gets £18 more than Ben. How much does Ben get?',
        options: ['£12', '£6', '£18', '£30'],
        correctIndex: 0,
        explanation: 'Difference in parts = 5 − 2 = 3. One part = £18 ÷ 3 = £6. Ben = 2 × £6 = £12.',
        misconception: 'Choosing £6 means finding one part but forgetting to multiply by Ben\'s share.',
        tier: 'Both',
      },
      {
        id: 'ratio-given-difference-3',
        topicSlug: 'ratio-given-difference',
        question: 'Two lengths are in the ratio 5:8. The difference is 12 cm. What is the longer length?',
        options: ['32 cm', '20 cm', '40 cm', '24 cm'],
        correctIndex: 0,
        explanation: 'Difference in parts = 8 − 5 = 3. One part = 12 ÷ 3 = 4 cm. Longer = 8 × 4 = 32 cm.',
        misconception: 'Choosing 20 cm means finding 5 parts instead of 8 parts.',
        tier: 'Both',
      },
      {
        id: 'ratio-given-difference-4',
        topicSlug: 'ratio-given-difference',
        question: 'The ratio of Kate\'s age to Liam\'s age is 3:5. Liam is 8 years older. How old is Kate?',
        options: ['12', '20', '8', '15'],
        correctIndex: 0,
        explanation: 'Difference in parts = 5 − 3 = 2. One part = 8 ÷ 2 = 4. Kate = 3 × 4 = 12.',
        misconception: 'Choosing 20 means finding 5 parts instead of 3.',
        tier: 'Both',
      },
      {
        id: 'ratio-given-difference-5',
        topicSlug: 'ratio-given-difference',
        question: 'Two amounts are in the ratio 1:4. The difference is £27. What is the total?',
        options: ['£45', '£36', '£27', '£54'],
        correctIndex: 0,
        explanation: 'Difference in parts = 4 − 1 = 3. One part = £27 ÷ 3 = £9. Total parts = 5. Total = 5 × £9 = £45.',
        misconception: 'Choosing £36 means finding 4 parts and assuming that is the total.',
        tier: 'Both',
      },
    ],
  },

  // ─── 6. Ratio Problem Solving in Context ────────────────────────────
  {
    topicSlug: 'ratio-problem-solving-in-context',
    topicTitle: 'Ratio Problem Solving in Context',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'ratio-problem-solving-in-context-1',
        topicSlug: 'ratio-problem-solving-in-context',
        question: 'A paint mix uses red and white in the ratio 2:5. You need 35 litres total. How many litres of red paint?',
        options: ['10', '14', '25', '7'],
        correctIndex: 0,
        explanation: 'Total parts = 7. Each part = 35 ÷ 7 = 5. Red = 2 × 5 = 10 litres.',
        misconception: 'Choosing 14 means dividing 35 by the ratio number 2.5 incorrectly.',
        tier: 'Both',
      },
      {
        id: 'ratio-problem-solving-in-context-2',
        topicSlug: 'ratio-problem-solving-in-context',
        question: 'Concrete is mixed in the ratio 1:2:3 (cement:sand:gravel). How much sand is needed for 180 kg of concrete?',
        options: ['60 kg', '90 kg', '30 kg', '36 kg'],
        correctIndex: 0,
        explanation: 'Total parts = 1 + 2 + 3 = 6. Each part = 180 ÷ 6 = 30 kg. Sand = 2 × 30 = 60 kg.',
        misconception: 'Choosing 90 kg means finding the gravel amount instead of sand.',
        tier: 'Both',
      },
      {
        id: 'ratio-problem-solving-in-context-3',
        topicSlug: 'ratio-problem-solving-in-context',
        question: 'In a school, the ratio of teachers to students is 1:15. There are 480 students. How many teachers are there?',
        options: ['32', '30', '48', '15'],
        correctIndex: 0,
        explanation: 'Teachers = 480 ÷ 15 = 32.',
        misconception: 'Choosing 30 means rounding or dividing by 16 instead of 15.',
        tier: 'Both',
      },
      {
        id: 'ratio-problem-solving-in-context-4',
        topicSlug: 'ratio-problem-solving-in-context',
        question: 'A map uses the scale 1:25000. Two towns are 8 cm apart on the map. What is the real distance in km?',
        options: ['2 km', '200 km', '20 km', '0.2 km'],
        correctIndex: 0,
        explanation: 'Real distance = 8 × 25000 = 200000 cm = 2000 m = 2 km.',
        misconception: 'Choosing 200 km means forgetting to convert from cm to km.',
        tier: 'Both',
      },
      {
        id: 'ratio-problem-solving-in-context-5',
        topicSlug: 'ratio-problem-solving-in-context',
        question: 'Purple paint is made by mixing red and blue in the ratio 3:5. Sam has 12 litres of red. How much blue does he need?',
        options: ['20 litres', '15 litres', '8 litres', '5 litres'],
        correctIndex: 0,
        explanation: 'Scale factor = 12 ÷ 3 = 4. Blue = 5 × 4 = 20 litres.',
        misconception: 'Choosing 15 means adding 3 to 12 instead of using the scale factor.',
        tier: 'Both',
      },
    ],
  },

  // ─── 7. Proportional Reasoning ──────────────────────────────────────
  {
    topicSlug: 'proportional-reasoning',
    topicTitle: 'Proportional Reasoning',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'proportional-reasoning-1',
        topicSlug: 'proportional-reasoning',
        question: '5 pens cost £3.50. How much do 8 pens cost?',
        options: ['£5.60', '£4.50', '£6.40', '£28.00'],
        correctIndex: 0,
        explanation: 'Cost per pen = £3.50 ÷ 5 = £0.70. 8 pens = 8 × £0.70 = £5.60.',
        misconception: 'Choosing £28.00 means multiplying £3.50 × 8 without finding the unit cost.',
        tier: 'Both',
      },
      {
        id: 'proportional-reasoning-2',
        topicSlug: 'proportional-reasoning',
        question: 'A car travels 120 miles on 15 litres of fuel. How far can it travel on 25 litres?',
        options: ['200 miles', '180 miles', '300 miles', '160 miles'],
        correctIndex: 0,
        explanation: 'Miles per litre = 120 ÷ 15 = 8. On 25 litres: 25 × 8 = 200 miles.',
        misconception: 'Choosing 180 means adding 60 to 120 instead of finding the unit rate.',
        tier: 'Both',
      },
      {
        id: 'proportional-reasoning-3',
        topicSlug: 'proportional-reasoning',
        question: 'If 3 workers can paint a fence in 12 hours, how long would 6 workers take?',
        options: ['6 hours', '24 hours', '4 hours', '18 hours'],
        correctIndex: 0,
        explanation: 'Doubling the workers halves the time: 12 ÷ 2 = 6 hours.',
        misconception: 'Choosing 24 hours means doubling the time instead of halving it (confusing direct with inverse).',
        tier: 'Both',
      },
      {
        id: 'proportional-reasoning-4',
        topicSlug: 'proportional-reasoning',
        question: 'A recipe for 4 people uses 300 g of flour. How much flour is needed for 10 people?',
        options: ['750 g', '120 g', '600 g', '3000 g'],
        correctIndex: 0,
        explanation: 'Per person = 300 ÷ 4 = 75 g. For 10 people = 10 × 75 = 750 g.',
        misconception: 'Choosing 3000 g means multiplying 300 × 10 without adjusting for 4 people.',
        tier: 'Both',
      },
      {
        id: 'proportional-reasoning-5',
        topicSlug: 'proportional-reasoning',
        question: '12 identical toys weigh 840 g in total. How much do 5 of these toys weigh?',
        options: ['350 g', '420 g', '168 g', '700 g'],
        correctIndex: 0,
        explanation: 'Weight per toy = 840 ÷ 12 = 70 g. 5 toys = 5 × 70 = 350 g.',
        misconception: 'Choosing 420 g means halving 840 instead of finding the unit weight.',
        tier: 'Both',
      },
    ],
  },

  // ─── 8. Direct and Inverse Proportion ───────────────────────────────
  {
    topicSlug: 'direct-and-inverse-proportion',
    topicTitle: 'Direct and Inverse Proportion',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'direct-and-inverse-proportion-1',
        topicSlug: 'direct-and-inverse-proportion',
        question: 'y is directly proportional to x. When x = 4, y = 20. Find y when x = 7.',
        options: ['35', '28', '11', '140'],
        correctIndex: 0,
        explanation: 'k = y/x = 20/4 = 5. When x = 7: y = 5 × 7 = 35.',
        misconception: 'Choosing 28 means multiplying 4 × 7 instead of using the constant of proportionality.',
        tier: 'Higher',
      },
      {
        id: 'direct-and-inverse-proportion-2',
        topicSlug: 'direct-and-inverse-proportion',
        question: 'y is inversely proportional to x. When x = 2, y = 18. Find y when x = 6.',
        options: ['6', '54', '9', '3'],
        correctIndex: 0,
        explanation: 'k = xy = 2 × 18 = 36. When x = 6: y = 36 ÷ 6 = 6.',
        misconception: 'Choosing 54 means multiplying 18 × 3 (treating it as direct proportion).',
        tier: 'Higher',
      },
      {
        id: 'direct-and-inverse-proportion-3',
        topicSlug: 'direct-and-inverse-proportion',
        question: 'If y is directly proportional to x, which statement is true?',
        options: ['Doubling x doubles y', 'Doubling x halves y', 'Doubling x adds 2 to y', 'y stays the same when x changes'],
        correctIndex: 0,
        explanation: 'In direct proportion, y = kx, so doubling x doubles y.',
        misconception: 'Choosing "Doubling x halves y" confuses direct with inverse proportion.',
        tier: 'Both',
      },
      {
        id: 'direct-and-inverse-proportion-4',
        topicSlug: 'direct-and-inverse-proportion',
        question: 'y is inversely proportional to x. When x = 5, y = 12. Find y when x = 10.',
        options: ['6', '24', '60', '2'],
        correctIndex: 0,
        explanation: 'k = 5 × 12 = 60. When x = 10: y = 60 ÷ 10 = 6.',
        misconception: 'Choosing 24 means doubling y when x doubles (treating as direct proportion).',
        tier: 'Higher',
      },
      {
        id: 'direct-and-inverse-proportion-5',
        topicSlug: 'direct-and-inverse-proportion',
        question: 'y is directly proportional to x. When x = 3, y = 12. What is x when y = 28?',
        options: ['7', '9', '84', '16'],
        correctIndex: 0,
        explanation: 'k = 12/3 = 4. y = 4x, so x = 28 ÷ 4 = 7.',
        misconception: 'Choosing 84 means multiplying 28 × 3 instead of dividing by k.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 9. Direct Proportion Equations ─────────────────────────────────
  {
    topicSlug: 'direct-proportion-equations',
    topicTitle: 'Direct Proportion Equations',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'direct-proportion-equations-1',
        topicSlug: 'direct-proportion-equations',
        question: 'y is directly proportional to x². When x = 3, y = 36. Find y when x = 5.',
        options: ['100', '60', '180', '75'],
        correctIndex: 0,
        explanation: 'y = kx². 36 = k × 9, so k = 4. When x = 5: y = 4 × 25 = 100.',
        misconception: 'Choosing 60 means using y = kx instead of y = kx².',
        tier: 'Higher',
      },
      {
        id: 'direct-proportion-equations-2',
        topicSlug: 'direct-proportion-equations',
        question: 'y ∝ x³. When x = 2, y = 24. Find the value of k.',
        options: ['3', '12', '6', '8'],
        correctIndex: 0,
        explanation: 'y = kx³. 24 = k × 8, so k = 24 ÷ 8 = 3.',
        misconception: 'Choosing 12 means dividing by x instead of x³.',
        tier: 'Higher',
      },
      {
        id: 'direct-proportion-equations-3',
        topicSlug: 'direct-proportion-equations',
        question: 'y ∝ √x. When x = 16, y = 12. Find y when x = 25.',
        options: ['15', '20', '18.75', '12.5'],
        correctIndex: 0,
        explanation: 'y = k√x. 12 = k × 4, so k = 3. When x = 25: y = 3 × 5 = 15.',
        misconception: 'Choosing 18.75 means multiplying 12 by 25/16 (linear proportion instead of square root).',
        tier: 'Higher',
      },
      {
        id: 'direct-proportion-equations-4',
        topicSlug: 'direct-proportion-equations',
        question: 'y is directly proportional to x². When x = 2, y = 12. Find y when x = 6.',
        options: ['108', '36', '72', '144'],
        correctIndex: 0,
        explanation: 'y = kx². 12 = k × 4, k = 3. When x = 6: y = 3 × 36 = 108.',
        misconception: 'Choosing 36 means using y = kx instead of y = kx².',
        tier: 'Higher',
      },
      {
        id: 'direct-proportion-equations-5',
        topicSlug: 'direct-proportion-equations',
        question: 'y ∝ x². When x = 4, y = 80. What is x when y = 20?',
        options: ['2', '1', '4', '10'],
        correctIndex: 0,
        explanation: 'y = kx². 80 = k × 16, k = 5. 20 = 5x², x² = 4, x = 2.',
        misconception: 'Choosing 1 means dividing y by 20 instead of solving x² = 4.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 10. Direct Proportion Graphs ───────────────────────────────────
  {
    topicSlug: 'direct-proportion-graphs',
    topicTitle: 'Direct Proportion Graphs',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'direct-proportion-graphs-1',
        topicSlug: 'direct-proportion-graphs',
        question: 'Which type of graph shows direct proportion between y and x?',
        options: ['A straight line through the origin', 'A curved line through the origin', 'A straight line with y-intercept 3', 'A horizontal line'],
        correctIndex: 0,
        explanation: 'Direct proportion means y = kx, which is a straight line passing through (0, 0).',
        misconception: 'Choosing a straight line with y-intercept 3 confuses y = kx with y = mx + c.',
        tier: 'Both',
      },
      {
        id: 'direct-proportion-graphs-2',
        topicSlug: 'direct-proportion-graphs',
        question: 'A direct proportion graph passes through (4, 10). What is the gradient?',
        options: ['2.5', '4', '10', '0.4'],
        correctIndex: 0,
        explanation: 'Gradient = y/x = 10/4 = 2.5 (line through origin so gradient = k).',
        misconception: 'Choosing 0.4 means calculating x/y instead of y/x.',
        tier: 'Both',
      },
      {
        id: 'direct-proportion-graphs-3',
        topicSlug: 'direct-proportion-graphs',
        question: 'A graph of y against x is a straight line through the origin with gradient 3. What is y when x = 7?',
        options: ['21', '10', '3', '7'],
        correctIndex: 0,
        explanation: 'y = 3x. When x = 7: y = 3 × 7 = 21.',
        misconception: 'Choosing 10 means adding 3 + 7 instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'direct-proportion-graphs-4',
        topicSlug: 'direct-proportion-graphs',
        question: 'Which of these relationships does NOT show direct proportion?',
        options: ['y = 2x + 1', 'y = 5x', 'y = 0.5x', 'y = 10x'],
        correctIndex: 0,
        explanation: 'y = 2x + 1 has a constant term (+1), so the line does not pass through the origin.',
        misconception: 'Choosing y = 0.5x means thinking a small gradient cannot show direct proportion.',
        tier: 'Both',
      },
      {
        id: 'direct-proportion-graphs-5',
        topicSlug: 'direct-proportion-graphs',
        question: 'On a y against x² graph, direct proportion between y and x² appears as:',
        options: ['A straight line through the origin', 'A parabola', 'A straight line with positive y-intercept', 'A curve that levels off'],
        correctIndex: 0,
        explanation: 'If y ∝ x², plotting y against x² gives y = kx², a straight line through the origin.',
        misconception: 'Choosing a parabola confuses the y vs x graph with the y vs x² graph.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 11. Inverse Proportion ─────────────────────────────────────────
  {
    topicSlug: 'inverse-proportion',
    topicTitle: 'Inverse Proportion',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'inverse-proportion-1',
        topicSlug: 'inverse-proportion',
        question: 'y is inversely proportional to x. When x = 3, y = 8. Find y when x = 12.',
        options: ['2', '32', '4', '6'],
        correctIndex: 0,
        explanation: 'k = xy = 3 × 8 = 24. When x = 12: y = 24 ÷ 12 = 2.',
        misconception: 'Choosing 32 means multiplying 8 × 4, treating it as direct proportion.',
        tier: 'Higher',
      },
      {
        id: 'inverse-proportion-2',
        topicSlug: 'inverse-proportion',
        question: 'y is inversely proportional to x². When x = 2, y = 5. Find y when x = 4.',
        options: ['1.25', '20', '10', '2.5'],
        correctIndex: 0,
        explanation: 'k = y × x² = 5 × 4 = 20. When x = 4: y = 20 ÷ 16 = 1.25.',
        misconception: 'Choosing 2.5 means using inverse proportion to x instead of x².',
        tier: 'Higher',
      },
      {
        id: 'inverse-proportion-3',
        topicSlug: 'inverse-proportion',
        question: '4 machines take 6 hours to complete a job. How long would 8 machines take?',
        options: ['3 hours', '12 hours', '2 hours', '48 hours'],
        correctIndex: 0,
        explanation: 'Inverse proportion: 4 × 6 = 24. With 8 machines: 24 ÷ 8 = 3 hours.',
        misconception: 'Choosing 12 hours means doubling the time when doubling machines.',
        tier: 'Both',
      },
      {
        id: 'inverse-proportion-4',
        topicSlug: 'inverse-proportion',
        question: 'y ∝ 1/x. When x = 5, y = 10. Find x when y = 25.',
        options: ['2', '50', '5', '0.5'],
        correctIndex: 0,
        explanation: 'k = xy = 5 × 10 = 50. When y = 25: x = 50 ÷ 25 = 2.',
        misconception: 'Choosing 50 means multiplying 5 × 10 and giving k as the answer.',
        tier: 'Higher',
      },
      {
        id: 'inverse-proportion-5',
        topicSlug: 'inverse-proportion',
        question: 'Which graph shape represents inverse proportion (y = k/x)?',
        options: ['A reciprocal curve (hyperbola)', 'A straight line through the origin', 'A parabola', 'A straight horizontal line'],
        correctIndex: 0,
        explanation: 'y = k/x produces a reciprocal curve (hyperbola) in the first quadrant for positive k.',
        misconception: 'Choosing a straight line through the origin confuses inverse with direct proportion.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 12. Speed Distance and Time ────────────────────────────────────
  {
    topicSlug: 'speed-distance-and-time',
    topicTitle: 'Speed, Distance and Time',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'speed-distance-and-time-1',
        topicSlug: 'speed-distance-and-time',
        question: 'A car travels 150 miles in 3 hours. What is its average speed?',
        options: ['50 mph', '450 mph', '45 mph', '30 mph'],
        correctIndex: 0,
        explanation: 'Speed = Distance ÷ Time = 150 ÷ 3 = 50 mph.',
        misconception: 'Choosing 450 mph means multiplying distance × time instead of dividing.',
        tier: 'Both',
      },
      {
        id: 'speed-distance-and-time-2',
        topicSlug: 'speed-distance-and-time',
        question: 'A cyclist travels at 12 km/h for 2.5 hours. How far does the cyclist travel?',
        options: ['30 km', '4.8 km', '14.5 km', '24 km'],
        correctIndex: 0,
        explanation: 'Distance = Speed × Time = 12 × 2.5 = 30 km.',
        misconception: 'Choosing 4.8 means dividing speed by time instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'speed-distance-and-time-3',
        topicSlug: 'speed-distance-and-time',
        question: 'How long does it take to travel 200 km at 80 km/h?',
        options: ['2.5 hours', '2 hours', '120 minutes', '3 hours'],
        correctIndex: 0,
        explanation: 'Time = Distance ÷ Speed = 200 ÷ 80 = 2.5 hours.',
        misconception: 'Choosing 120 minutes means calculating 200 − 80 = 120.',
        tier: 'Both',
      },
      {
        id: 'speed-distance-and-time-4',
        topicSlug: 'speed-distance-and-time',
        question: 'A train travels at 60 mph for 45 minutes. What distance does it cover?',
        options: ['45 miles', '60 miles', '2700 miles', '30 miles'],
        correctIndex: 0,
        explanation: '45 minutes = 0.75 hours. Distance = 60 × 0.75 = 45 miles.',
        misconception: 'Choosing 2700 means multiplying 60 × 45 without converting minutes to hours.',
        tier: 'Both',
      },
      {
        id: 'speed-distance-and-time-5',
        topicSlug: 'speed-distance-and-time',
        question: 'A runner completes a 10 km race in 50 minutes. What is the runner\'s speed in km/h?',
        options: ['12 km/h', '0.2 km/h', '500 km/h', '5 km/h'],
        correctIndex: 0,
        explanation: '50 minutes = 50/60 = 5/6 hours. Speed = 10 ÷ (5/6) = 10 × 6/5 = 12 km/h.',
        misconception: 'Choosing 0.2 means dividing 10 by 50 without converting minutes to hours.',
        tier: 'Both',
      },
    ],
  },

  // ─── 13. Speed Distance Time Calculations ──────────────────────────
  {
    topicSlug: 'speed-distance-time-calculations',
    topicTitle: 'Speed, Distance, Time Calculations',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'speed-distance-time-calculations-1',
        topicSlug: 'speed-distance-time-calculations',
        question: 'A car travels 90 km at 60 km/h, then 60 km at 40 km/h. What is the total time?',
        options: ['3 hours', '2.5 hours', '2 hours', '3.5 hours'],
        correctIndex: 0,
        explanation: 'Time1 = 90/60 = 1.5 h. Time2 = 60/40 = 1.5 h. Total = 3 hours.',
        misconception: 'Choosing 2.5 hours means averaging the speeds instead of finding each time separately.',
        tier: 'Both',
      },
      {
        id: 'speed-distance-time-calculations-2',
        topicSlug: 'speed-distance-time-calculations',
        question: 'A bus leaves at 09:15 and arrives at 11:00. It travels 70 miles. What is its average speed?',
        options: ['40 mph', '35 mph', '70 mph', '50 mph'],
        correctIndex: 0,
        explanation: 'Time = 1 hour 45 min = 1.75 hours. Speed = 70 ÷ 1.75 = 40 mph.',
        misconception: 'Choosing 35 means dividing 70 by 2 instead of 1.75.',
        tier: 'Both',
      },
      {
        id: 'speed-distance-time-calculations-3',
        topicSlug: 'speed-distance-time-calculations',
        question: 'Convert 54 km/h to m/s.',
        options: ['15 m/s', '54 m/s', '150 m/s', '1.5 m/s'],
        correctIndex: 0,
        explanation: '54 km/h = 54 × 1000 ÷ 3600 = 54000 ÷ 3600 = 15 m/s.',
        misconception: 'Choosing 54 m/s means not converting units at all.',
        tier: 'Higher',
      },
      {
        id: 'speed-distance-time-calculations-4',
        topicSlug: 'speed-distance-time-calculations',
        question: 'A journey of 210 miles takes 3 hours 30 minutes. What is the average speed?',
        options: ['60 mph', '70 mph', '63 mph', '30 mph'],
        correctIndex: 0,
        explanation: '3 hours 30 min = 3.5 hours. Speed = 210 ÷ 3.5 = 60 mph.',
        misconception: 'Choosing 70 means dividing 210 by 3 instead of 3.5.',
        tier: 'Both',
      },
      {
        id: 'speed-distance-time-calculations-5',
        topicSlug: 'speed-distance-time-calculations',
        question: 'Two cars start 300 miles apart and drive towards each other at 40 mph and 60 mph. After how long do they meet?',
        options: ['3 hours', '5 hours', '7.5 hours', '2 hours'],
        correctIndex: 0,
        explanation: 'Combined speed = 40 + 60 = 100 mph. Time = 300 ÷ 100 = 3 hours.',
        misconception: 'Choosing 5 hours means dividing 300 by 60 only.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 14. Distance-Time Graphs ───────────────────────────────────────
  {
    topicSlug: 'distance-time-graphs',
    topicTitle: 'Distance-Time Graphs',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'distance-time-graphs-1',
        topicSlug: 'distance-time-graphs',
        question: 'On a distance-time graph, what does a horizontal line represent?',
        options: ['The object is stationary', 'The object is accelerating', 'The object is moving at constant speed', 'The object is decelerating'],
        correctIndex: 0,
        explanation: 'A horizontal line means distance is not changing, so the object is stationary.',
        misconception: 'Choosing constant speed confuses distance-time with speed-time graphs.',
        tier: 'Both',
      },
      {
        id: 'distance-time-graphs-2',
        topicSlug: 'distance-time-graphs',
        question: 'On a distance-time graph, how do you find the speed?',
        options: ['Calculate the gradient of the line', 'Find the area under the line', 'Read the y-intercept', 'Read the x-intercept'],
        correctIndex: 0,
        explanation: 'Speed = distance ÷ time = rise ÷ run = gradient of a distance-time graph.',
        misconception: 'Finding the area under the line is how you find distance on a speed-time graph.',
        tier: 'Both',
      },
      {
        id: 'distance-time-graphs-3',
        topicSlug: 'distance-time-graphs',
        question: 'A distance-time graph shows a straight line from (0, 0) to (4, 20). What is the speed?',
        options: ['5 km/h', '20 km/h', '4 km/h', '80 km/h'],
        correctIndex: 0,
        explanation: 'Gradient = (20 − 0)/(4 − 0) = 20/4 = 5 km/h.',
        misconception: 'Choosing 80 means multiplying 20 × 4 instead of dividing.',
        tier: 'Both',
      },
      {
        id: 'distance-time-graphs-4',
        topicSlug: 'distance-time-graphs',
        question: 'On a distance-time graph, a steeper line means:',
        options: ['A faster speed', 'A slower speed', 'A longer distance', 'The object is stationary'],
        correctIndex: 0,
        explanation: 'A steeper gradient on a distance-time graph means a greater speed.',
        misconception: 'Choosing a slower speed confuses steeper gradient with slower movement.',
        tier: 'Both',
      },
      {
        id: 'distance-time-graphs-5',
        topicSlug: 'distance-time-graphs',
        question: 'A distance-time graph curves upward (getting steeper). What does this show?',
        options: ['The object is accelerating', 'The object is decelerating', 'The object is at constant speed', 'The object is stationary'],
        correctIndex: 0,
        explanation: 'A curve getting steeper means the speed is increasing, so the object is accelerating.',
        misconception: 'Choosing constant speed ignores that a straight line would show constant speed, not a curve.',
        tier: 'Both',
      },
    ],
  },

  // ─── 15. Velocity-Time Graphs ───────────────────────────────────────
  {
    topicSlug: 'velocity-time-graphs',
    topicTitle: 'Velocity-Time Graphs',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'velocity-time-graphs-1',
        topicSlug: 'velocity-time-graphs',
        question: 'On a velocity-time graph, what does the gradient represent?',
        options: ['Acceleration', 'Distance', 'Speed', 'Time'],
        correctIndex: 0,
        explanation: 'Gradient of a velocity-time graph = change in velocity ÷ time = acceleration.',
        misconception: 'Choosing distance confuses gradient with area under the graph.',
        tier: 'Higher',
      },
      {
        id: 'velocity-time-graphs-2',
        topicSlug: 'velocity-time-graphs',
        question: 'On a velocity-time graph, how do you find the distance travelled?',
        options: ['Calculate the area under the graph', 'Calculate the gradient', 'Read the highest point', 'Find the y-intercept'],
        correctIndex: 0,
        explanation: 'Area under a velocity-time graph = distance travelled.',
        misconception: 'Calculating the gradient gives acceleration, not distance.',
        tier: 'Higher',
      },
      {
        id: 'velocity-time-graphs-3',
        topicSlug: 'velocity-time-graphs',
        question: 'A velocity-time graph shows a horizontal line at 20 m/s for 5 seconds. What is the distance?',
        options: ['100 m', '25 m', '4 m', '20 m'],
        correctIndex: 0,
        explanation: 'Area = base × height = 5 × 20 = 100 m.',
        misconception: 'Choosing 4 m means dividing 20 by 5 instead of multiplying.',
        tier: 'Higher',
      },
      {
        id: 'velocity-time-graphs-4',
        topicSlug: 'velocity-time-graphs',
        question: 'A car accelerates from 0 to 30 m/s in 6 seconds. What is the acceleration?',
        options: ['5 m/s²', '180 m/s²', '36 m/s²', '0.2 m/s²'],
        correctIndex: 0,
        explanation: 'Acceleration = (30 − 0) ÷ 6 = 5 m/s².',
        misconception: 'Choosing 180 means multiplying 30 × 6 instead of dividing.',
        tier: 'Higher',
      },
      {
        id: 'velocity-time-graphs-5',
        topicSlug: 'velocity-time-graphs',
        question: 'A velocity-time graph forms a triangle with base 8 s and peak velocity 12 m/s. What is the distance?',
        options: ['48 m', '96 m', '20 m', '24 m'],
        correctIndex: 0,
        explanation: 'Area of triangle = ½ × base × height = ½ × 8 × 12 = 48 m.',
        misconception: 'Choosing 96 m means using base × height without halving for the triangle.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 16. Compound Measures: Density and Pressure ────────────────────
  {
    topicSlug: 'compound-measures-density-and-pressure',
    topicTitle: 'Compound Measures: Density and Pressure',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'compound-measures-density-and-pressure-1',
        topicSlug: 'compound-measures-density-and-pressure',
        question: 'What is density measured in?',
        options: ['g/cm³', 'g × cm³', 'cm³/g', 'g + cm³'],
        correctIndex: 0,
        explanation: 'Density = mass ÷ volume, measured in g/cm³ (or kg/m³).',
        misconception: 'Choosing cm³/g confuses the formula by putting volume over mass.',
        tier: 'Both',
      },
      {
        id: 'compound-measures-density-and-pressure-2',
        topicSlug: 'compound-measures-density-and-pressure',
        question: 'An object has mass 240 g and volume 80 cm³. What is its density?',
        options: ['3 g/cm³', '160 g/cm³', '320 g/cm³', '0.33 g/cm³'],
        correctIndex: 0,
        explanation: 'Density = 240 ÷ 80 = 3 g/cm³.',
        misconception: 'Choosing 0.33 means dividing volume by mass instead of mass by volume.',
        tier: 'Both',
      },
      {
        id: 'compound-measures-density-and-pressure-3',
        topicSlug: 'compound-measures-density-and-pressure',
        question: 'A force of 200 N acts on an area of 4 m². What is the pressure?',
        options: ['50 N/m²', '800 N/m²', '204 N/m²', '196 N/m²'],
        correctIndex: 0,
        explanation: 'Pressure = Force ÷ Area = 200 ÷ 4 = 50 N/m².',
        misconception: 'Choosing 800 means multiplying force × area instead of dividing.',
        tier: 'Both',
      },
      {
        id: 'compound-measures-density-and-pressure-4',
        topicSlug: 'compound-measures-density-and-pressure',
        question: 'Which formula correctly links pressure, force and area?',
        options: ['Pressure = Force ÷ Area', 'Pressure = Force × Area', 'Force = Pressure ÷ Area', 'Area = Force × Pressure'],
        correctIndex: 0,
        explanation: 'Pressure = Force ÷ Area is the correct formula.',
        misconception: 'Choosing Force × Area confuses the relationship between the three quantities.',
        tier: 'Both',
      },
      {
        id: 'compound-measures-density-and-pressure-5',
        topicSlug: 'compound-measures-density-and-pressure',
        question: 'A material has density 2.5 g/cm³. What is the mass of 20 cm³ of this material?',
        options: ['50 g', '8 g', '22.5 g', '0.125 g'],
        correctIndex: 0,
        explanation: 'Mass = Density × Volume = 2.5 × 20 = 50 g.',
        misconception: 'Choosing 8 means dividing 20 by 2.5 (finding volume instead of mass).',
        tier: 'Both',
      },
    ],
  },

  // ─── 17. Density Mass Volume ────────────────────────────────────────
  {
    topicSlug: 'density-mass-volume',
    topicTitle: 'Density, Mass and Volume',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'density-mass-volume-1',
        topicSlug: 'density-mass-volume',
        question: 'A block has mass 600 g and density 8 g/cm³. What is its volume?',
        options: ['75 cm³', '4800 cm³', '592 cm³', '608 cm³'],
        correctIndex: 0,
        explanation: 'Volume = Mass ÷ Density = 600 ÷ 8 = 75 cm³.',
        misconception: 'Choosing 4800 means multiplying mass × density instead of dividing.',
        tier: 'Both',
      },
      {
        id: 'density-mass-volume-2',
        topicSlug: 'density-mass-volume',
        question: 'Iron has a density of 7.8 g/cm³. What is the mass of 10 cm³ of iron?',
        options: ['78 g', '1.28 g', '17.8 g', '0.78 g'],
        correctIndex: 0,
        explanation: 'Mass = Density × Volume = 7.8 × 10 = 78 g.',
        misconception: 'Choosing 1.28 means dividing density by volume.',
        tier: 'Both',
      },
      {
        id: 'density-mass-volume-3',
        topicSlug: 'density-mass-volume',
        question: 'A liquid has mass 450 g and volume 500 cm³. What is its density?',
        options: ['0.9 g/cm³', '50 g/cm³', '950 g/cm³', '1.11 g/cm³'],
        correctIndex: 0,
        explanation: 'Density = Mass ÷ Volume = 450 ÷ 500 = 0.9 g/cm³.',
        misconception: 'Choosing 1.11 means dividing volume by mass instead of mass by volume.',
        tier: 'Both',
      },
      {
        id: 'density-mass-volume-4',
        topicSlug: 'density-mass-volume',
        question: 'Object A has density 2 g/cm³. Object B has density 5 g/cm³. They have the same mass. Which has the larger volume?',
        options: ['Object A', 'Object B', 'They have the same volume', 'Cannot be determined'],
        correctIndex: 0,
        explanation: 'V = M/D. For the same mass, lower density means larger volume. Object A has lower density.',
        misconception: 'Choosing Object B confuses higher density with larger volume.',
        tier: 'Both',
      },
      {
        id: 'density-mass-volume-5',
        topicSlug: 'density-mass-volume',
        question: 'A cube has side length 5 cm and mass 375 g. What is its density?',
        options: ['3 g/cm³', '75 g/cm³', '15 g/cm³', '25 g/cm³'],
        correctIndex: 0,
        explanation: 'Volume = 5³ = 125 cm³. Density = 375 ÷ 125 = 3 g/cm³.',
        misconception: 'Choosing 75 means dividing 375 by 5 instead of by 125.',
        tier: 'Both',
      },
    ],
  },

  // ─── 18. Pressure Force Area ────────────────────────────────────────
  {
    topicSlug: 'pressure-force-area',
    topicTitle: 'Pressure, Force and Area',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'pressure-force-area-1',
        topicSlug: 'pressure-force-area',
        question: 'A pressure of 25 N/m² acts on an area of 8 m². What is the force?',
        options: ['200 N', '3.125 N', '33 N', '17 N'],
        correctIndex: 0,
        explanation: 'Force = Pressure × Area = 25 × 8 = 200 N.',
        misconception: 'Choosing 3.125 means dividing pressure by area instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'pressure-force-area-2',
        topicSlug: 'pressure-force-area',
        question: 'A force of 500 N produces a pressure of 100 N/m². What is the area?',
        options: ['5 m²', '50000 m²', '400 m²', '600 m²'],
        correctIndex: 0,
        explanation: 'Area = Force ÷ Pressure = 500 ÷ 100 = 5 m².',
        misconception: 'Choosing 50000 means multiplying force × pressure.',
        tier: 'Both',
      },
      {
        id: 'pressure-force-area-3',
        topicSlug: 'pressure-force-area',
        question: 'A box weighs 120 N and sits on a face of area 0.4 m². What pressure does it exert?',
        options: ['300 N/m²', '48 N/m²', '120.4 N/m²', '480 N/m²'],
        correctIndex: 0,
        explanation: 'Pressure = Force ÷ Area = 120 ÷ 0.4 = 300 N/m².',
        misconception: 'Choosing 48 means multiplying 120 × 0.4 instead of dividing.',
        tier: 'Both',
      },
      {
        id: 'pressure-force-area-4',
        topicSlug: 'pressure-force-area',
        question: 'To decrease the pressure on a surface, you should:',
        options: ['Increase the area', 'Increase the force', 'Decrease the area', 'Double the force'],
        correctIndex: 0,
        explanation: 'Pressure = Force ÷ Area. Increasing area decreases pressure (for the same force).',
        misconception: 'Choosing decrease the area would increase pressure, not decrease it.',
        tier: 'Both',
      },
      {
        id: 'pressure-force-area-5',
        topicSlug: 'pressure-force-area',
        question: 'A rectangular base is 0.5 m by 0.2 m. A force of 30 N acts on it. What is the pressure?',
        options: ['300 N/m²', '3 N/m²', '150 N/m²', '60 N/m²'],
        correctIndex: 0,
        explanation: 'Area = 0.5 × 0.2 = 0.1 m². Pressure = 30 ÷ 0.1 = 300 N/m².',
        misconception: 'Choosing 60 means dividing 30 by 0.5 and ignoring the other dimension.',
        tier: 'Both',
      },
    ],
  },

  // ─── 19. Percentages Increase and Decrease ──────────────────────────
  {
    topicSlug: 'percentages-increase-and-decrease',
    topicTitle: 'Percentage Increase and Decrease',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'percentages-increase-and-decrease-1',
        topicSlug: 'percentages-increase-and-decrease',
        question: 'Increase £80 by 15%.',
        options: ['£92', '£68', '£95', '£12'],
        correctIndex: 0,
        explanation: '15% of £80 = £12. New amount = £80 + £12 = £92.',
        misconception: 'Choosing £12 gives the increase amount, not the new total.',
        tier: 'Both',
      },
      {
        id: 'percentages-increase-and-decrease-2',
        topicSlug: 'percentages-increase-and-decrease',
        question: 'Decrease 200 by 30%.',
        options: ['140', '60', '170', '230'],
        correctIndex: 0,
        explanation: '30% of 200 = 60. New amount = 200 − 60 = 140.',
        misconception: 'Choosing 60 gives the decrease amount, not the new total.',
        tier: 'Both',
      },
      {
        id: 'percentages-increase-and-decrease-3',
        topicSlug: 'percentages-increase-and-decrease',
        question: 'A price rises from £40 to £50. What is the percentage increase?',
        options: ['25%', '10%', '20%', '80%'],
        correctIndex: 0,
        explanation: 'Increase = £10. % increase = (10/40) × 100 = 25%.',
        misconception: 'Choosing 20% means dividing by 50 (the new value) instead of 40 (the original).',
        tier: 'Both',
      },
      {
        id: 'percentages-increase-and-decrease-4',
        topicSlug: 'percentages-increase-and-decrease',
        question: 'A population decreases from 500 to 400. What is the percentage decrease?',
        options: ['20%', '25%', '100%', '80%'],
        correctIndex: 0,
        explanation: 'Decrease = 100. % decrease = (100/500) × 100 = 20%.',
        misconception: 'Choosing 25% means dividing by 400 (the new value) instead of 500 (the original).',
        tier: 'Both',
      },
      {
        id: 'percentages-increase-and-decrease-5',
        topicSlug: 'percentages-increase-and-decrease',
        question: 'Increase £350 by 20%.',
        options: ['£420', '£70', '£280', '£370'],
        correctIndex: 0,
        explanation: '20% of £350 = £70. New amount = £350 + £70 = £420.',
        misconception: 'Choosing £280 means decreasing instead of increasing.',
        tier: 'Both',
      },
    ],
  },

  // ─── 20. Percentage Increase and Decrease Multipliers ───────────────
  {
    topicSlug: 'percentage-increase-and-decrease-multipliers',
    topicTitle: 'Percentage Increase and Decrease Multipliers',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'percentage-increase-and-decrease-multipliers-1',
        topicSlug: 'percentage-increase-and-decrease-multipliers',
        question: 'What multiplier represents a 25% increase?',
        options: ['1.25', '0.25', '0.75', '25'],
        correctIndex: 0,
        explanation: 'A 25% increase means 100% + 25% = 125% = 1.25.',
        misconception: 'Choosing 0.25 means using just the percentage as a decimal, not adding 1.',
        tier: 'Both',
      },
      {
        id: 'percentage-increase-and-decrease-multipliers-2',
        topicSlug: 'percentage-increase-and-decrease-multipliers',
        question: 'What multiplier represents a 15% decrease?',
        options: ['0.85', '1.15', '0.15', '1.85'],
        correctIndex: 0,
        explanation: 'A 15% decrease means 100% − 15% = 85% = 0.85.',
        misconception: 'Choosing 1.15 represents an increase, not a decrease.',
        tier: 'Both',
      },
      {
        id: 'percentage-increase-and-decrease-multipliers-3',
        topicSlug: 'percentage-increase-and-decrease-multipliers',
        question: 'A TV costs £600. It is reduced by 12%. Use a multiplier to find the sale price.',
        options: ['£528', '£672', '£72', '£588'],
        correctIndex: 0,
        explanation: 'Multiplier = 0.88. Sale price = £600 × 0.88 = £528.',
        misconception: 'Choosing £672 means using 1.12 (increase) instead of 0.88 (decrease).',
        tier: 'Both',
      },
      {
        id: 'percentage-increase-and-decrease-multipliers-4',
        topicSlug: 'percentage-increase-and-decrease-multipliers',
        question: 'A house worth £250,000 increases in value by 8%. What is the new value?',
        options: ['£270,000', '£230,000', '£20,000', '£258,000'],
        correctIndex: 0,
        explanation: 'Multiplier = 1.08. New value = £250,000 × 1.08 = £270,000.',
        misconception: 'Choosing £230,000 means subtracting 8% instead of adding.',
        tier: 'Both',
      },
      {
        id: 'percentage-increase-and-decrease-multipliers-5',
        topicSlug: 'percentage-increase-and-decrease-multipliers',
        question: 'The multiplier 0.65 represents what percentage decrease?',
        options: ['35%', '65%', '0.35%', '135%'],
        correctIndex: 0,
        explanation: '0.65 = 65% remaining, so the decrease is 100% − 65% = 35%.',
        misconception: 'Choosing 65% confuses remaining percentage with the decrease.',
        tier: 'Both',
      },
    ],
  },

  // ─── 21. Percentage Profit and Loss ─────────────────────────────────
  {
    topicSlug: 'percentage-profit-and-loss',
    topicTitle: 'Percentage Profit and Loss',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'percentage-profit-and-loss-1',
        topicSlug: 'percentage-profit-and-loss',
        question: 'A shopkeeper buys an item for £40 and sells it for £50. What is the percentage profit?',
        options: ['25%', '20%', '10%', '80%'],
        correctIndex: 0,
        explanation: 'Profit = £10. % profit = (10/40) × 100 = 25%.',
        misconception: 'Choosing 20% means dividing profit by selling price instead of cost price.',
        tier: 'Both',
      },
      {
        id: 'percentage-profit-and-loss-2',
        topicSlug: 'percentage-profit-and-loss',
        question: 'An item is bought for £120 and sold for £90. What is the percentage loss?',
        options: ['25%', '30%', '33.3%', '75%'],
        correctIndex: 0,
        explanation: 'Loss = £30. % loss = (30/120) × 100 = 25%.',
        misconception: 'Choosing 33.3% means dividing by the selling price instead of the cost price.',
        tier: 'Both',
      },
      {
        id: 'percentage-profit-and-loss-3',
        topicSlug: 'percentage-profit-and-loss',
        question: 'A car is bought for £8000 and sold at a 15% loss. What is the selling price?',
        options: ['£6800', '£9200', '£1200', '£7850'],
        correctIndex: 0,
        explanation: '15% of £8000 = £1200. Selling price = £8000 − £1200 = £6800.',
        misconception: 'Choosing £1200 gives the loss, not the selling price.',
        tier: 'Both',
      },
      {
        id: 'percentage-profit-and-loss-4',
        topicSlug: 'percentage-profit-and-loss',
        question: 'An item bought for £60 is sold with a 40% profit. What is the selling price?',
        options: ['£84', '£36', '£24', '£100'],
        correctIndex: 0,
        explanation: '40% of £60 = £24. Selling price = £60 + £24 = £84.',
        misconception: 'Choosing £24 gives the profit, not the selling price.',
        tier: 'Both',
      },
      {
        id: 'percentage-profit-and-loss-5',
        topicSlug: 'percentage-profit-and-loss',
        question: 'A trader buys 20 items at £5 each and sells all of them for a total of £150. What is the percentage profit?',
        options: ['50%', '30%', '25%', '150%'],
        correctIndex: 0,
        explanation: 'Cost = 20 × £5 = £100. Profit = £150 − £100 = £50. % profit = (50/100) × 100 = 50%.',
        misconception: 'Choosing 30% means dividing profit by selling price instead of cost price.',
        tier: 'Both',
      },
    ],
  },

  // ─── 22. Reverse Percentages ────────────────────────────────────────
  {
    topicSlug: 'reverse-percentages',
    topicTitle: 'Reverse Percentages',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'reverse-percentages-1',
        topicSlug: 'reverse-percentages',
        question: 'After a 20% increase, a price is £60. What was the original price?',
        options: ['£50', '£48', '£72', '£12'],
        correctIndex: 0,
        explanation: '120% = £60. 1% = £0.50. Original (100%) = £50.',
        misconception: 'Choosing £48 means subtracting 20% of £60 (£12) instead of dividing by 1.2.',
        tier: 'Both',
      },
      {
        id: 'reverse-percentages-2',
        topicSlug: 'reverse-percentages',
        question: 'After a 25% decrease, the value is £150. What was the original value?',
        options: ['£200', '£187.50', '£112.50', '£175'],
        correctIndex: 0,
        explanation: '75% = £150. Original (100%) = £150 ÷ 0.75 = £200.',
        misconception: 'Choosing £187.50 means adding 25% of £150 instead of dividing by 0.75.',
        tier: 'Both',
      },
      {
        id: 'reverse-percentages-3',
        topicSlug: 'reverse-percentages',
        question: 'A sale offers 30% off. The sale price is £35. What was the original price?',
        options: ['£50', '£45.50', '£24.50', '£65'],
        correctIndex: 0,
        explanation: '70% = £35. Original = £35 ÷ 0.7 = £50.',
        misconception: 'Choosing £45.50 means adding 30% of £35 instead of dividing by 0.7.',
        tier: 'Both',
      },
      {
        id: 'reverse-percentages-4',
        topicSlug: 'reverse-percentages',
        question: 'Including 20% VAT, an item costs £96. What is the price before VAT?',
        options: ['£80', '£76.80', '£115.20', '£19.20'],
        correctIndex: 0,
        explanation: '120% = £96. Original = £96 ÷ 1.2 = £80.',
        misconception: 'Choosing £76.80 means subtracting 20% of £96 instead of dividing by 1.2.',
        tier: 'Both',
      },
      {
        id: 'reverse-percentages-5',
        topicSlug: 'reverse-percentages',
        question: 'After a 10% pay rise, Sara earns £22,000. What was her original salary?',
        options: ['£20,000', '£19,800', '£24,200', '£2,200'],
        correctIndex: 0,
        explanation: '110% = £22,000. Original = £22,000 ÷ 1.1 = £20,000.',
        misconception: 'Choosing £19,800 means subtracting 10% of £22,000 instead of dividing by 1.1.',
        tier: 'Both',
      },
    ],
  },

  // ─── 23. Compound Interest and Depreciation ─────────────────────────
  {
    topicSlug: 'compound-interest-and-depreciation',
    topicTitle: 'Compound Interest and Depreciation',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'compound-interest-and-depreciation-1',
        topicSlug: 'compound-interest-and-depreciation',
        question: '£1000 is invested at 5% compound interest per year for 2 years. What is the final amount?',
        options: ['£1102.50', '£1100', '£1050', '£1010'],
        correctIndex: 0,
        explanation: 'After 1 year: £1050. After 2 years: £1050 × 1.05 = £1102.50.',
        misconception: 'Choosing £1100 means using simple interest (adding £50 each year).',
        tier: 'Both',
      },
      {
        id: 'compound-interest-and-depreciation-2',
        topicSlug: 'compound-interest-and-depreciation',
        question: 'A car worth £12,000 depreciates by 10% per year. What is it worth after 2 years?',
        options: ['£9720', '£9600', '£10,800', '£2400'],
        correctIndex: 0,
        explanation: 'After 1 year: £12,000 × 0.9 = £10,800. After 2 years: £10,800 × 0.9 = £9720.',
        misconception: 'Choosing £9600 means subtracting 10% of original each year (simple depreciation).',
        tier: 'Both',
      },
      {
        id: 'compound-interest-and-depreciation-3',
        topicSlug: 'compound-interest-and-depreciation',
        question: 'What is the formula for compound interest?',
        options: ['A = P(1 + r)ⁿ', 'A = P + Prn', 'A = P × r × n', 'A = P(1 − r)ⁿ'],
        correctIndex: 0,
        explanation: 'A = P(1 + r)ⁿ where P is principal, r is rate (decimal), n is number of periods.',
        misconception: 'Choosing A = P + Prn is the simple interest formula.',
        tier: 'Both',
      },
      {
        id: 'compound-interest-and-depreciation-4',
        topicSlug: 'compound-interest-and-depreciation',
        question: '£500 is invested at 4% compound interest per year. What is the value after 3 years?',
        options: ['£562.43', '£560', '£520', '£612'],
        correctIndex: 0,
        explanation: '£500 × 1.04³ = £500 × 1.124864 = £562.43 (to nearest penny).',
        misconception: 'Choosing £560 means using simple interest (£20 per year × 3).',
        tier: 'Both',
      },
      {
        id: 'compound-interest-and-depreciation-5',
        topicSlug: 'compound-interest-and-depreciation',
        question: 'A laptop worth £800 depreciates by 20% each year. What is it worth after 1 year?',
        options: ['£640', '£160', '£960', '£600'],
        correctIndex: 0,
        explanation: '£800 × 0.8 = £640.',
        misconception: 'Choosing £160 gives the depreciation amount, not the remaining value.',
        tier: 'Both',
      },
    ],
  },

  // ─── 24. Compound Interest Calculations ─────────────────────────────
  {
    topicSlug: 'compound-interest-calculations',
    topicTitle: 'Compound Interest Calculations',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'compound-interest-calculations-1',
        topicSlug: 'compound-interest-calculations',
        question: '£2000 is invested at 3% compound interest per year for 4 years. How much interest is earned?',
        options: ['£251.02', '£240', '£2251.02', '£60'],
        correctIndex: 0,
        explanation: 'Final = £2000 × 1.03⁴ = £2000 × 1.12550881 = £2251.02. Interest = £2251.02 − £2000 = £251.02.',
        misconception: 'Choosing £240 means using simple interest: £2000 × 0.03 × 4.',
        tier: 'Higher',
      },
      {
        id: 'compound-interest-calculations-2',
        topicSlug: 'compound-interest-calculations',
        question: '£5000 is invested at 6% compound interest. After how many years will it exceed £6000?',
        options: ['4 years', '3 years', '2 years', '5 years'],
        correctIndex: 0,
        explanation: 'Year 1: £5300. Year 2: £5618. Year 3: £5955.08. Year 4: £6312.38. It exceeds £6000 after 4 years.',
        misconception: 'Choosing 3 years means rounding up the year 3 value to £6000.',
        tier: 'Higher',
      },
      {
        id: 'compound-interest-calculations-3',
        topicSlug: 'compound-interest-calculations',
        question: '£10,000 is invested at 2.5% compound interest per year for 3 years. What is the final amount?',
        options: ['£10,768.91', '£10,750', '£10,250', '£750'],
        correctIndex: 0,
        explanation: '£10,000 × 1.025³ = £10,000 × 1.076890625 = £10,768.91.',
        misconception: 'Choosing £10,750 means using simple interest.',
        tier: 'Higher',
      },
      {
        id: 'compound-interest-calculations-4',
        topicSlug: 'compound-interest-calculations',
        question: 'An investment of £3000 grows to £3472.88 in 3 years with compound interest. What is the annual rate?',
        options: ['5%', '15%', '3%', '52.8%'],
        correctIndex: 0,
        explanation: '3472.88/3000 = 1.157626... Cube root = 1.05. Rate = 5%.',
        misconception: 'Choosing 15% means dividing the total growth by 3 as a percentage.',
        tier: 'Higher',
      },
      {
        id: 'compound-interest-calculations-5',
        topicSlug: 'compound-interest-calculations',
        question: '£4000 earns compound interest at 10% per year. What is the total after 2 years?',
        options: ['£4840', '£4800', '£800', '£4400'],
        correctIndex: 0,
        explanation: '£4000 × 1.1² = £4000 × 1.21 = £4840.',
        misconception: 'Choosing £4800 means using simple interest (£400 per year × 2).',
        tier: 'Both',
      },
    ],
  },

  // ─── 25. Simple Interest ────────────────────────────────────────────
  {
    topicSlug: 'simple-interest',
    topicTitle: 'Simple Interest',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'simple-interest-1',
        topicSlug: 'simple-interest',
        question: '£500 is invested at 4% simple interest per year for 3 years. How much interest is earned?',
        options: ['£60', '£62.43', '£520', '£1500'],
        correctIndex: 0,
        explanation: 'Simple interest = £500 × 0.04 × 3 = £60.',
        misconception: 'Choosing £62.43 means using compound interest instead of simple interest.',
        tier: 'Both',
      },
      {
        id: 'simple-interest-2',
        topicSlug: 'simple-interest',
        question: '£2000 is invested at 5% simple interest per year. What is the total after 4 years?',
        options: ['£2400', '£400', '£2431.01', '£10,000'],
        correctIndex: 0,
        explanation: 'Interest = £2000 × 0.05 × 4 = £400. Total = £2000 + £400 = £2400.',
        misconception: 'Choosing £400 gives the interest only, not the total amount.',
        tier: 'Both',
      },
      {
        id: 'simple-interest-3',
        topicSlug: 'simple-interest',
        question: '£800 earns £120 simple interest over 3 years. What is the annual interest rate?',
        options: ['5%', '15%', '40%', '3%'],
        correctIndex: 0,
        explanation: 'Rate = Interest ÷ (Principal × Time) = 120 ÷ (800 × 3) = 120 ÷ 2400 = 0.05 = 5%.',
        misconception: 'Choosing 15% means dividing £120 by £800 without dividing by the number of years.',
        tier: 'Both',
      },
      {
        id: 'simple-interest-4',
        topicSlug: 'simple-interest',
        question: 'How long does it take for £1000 to earn £200 in simple interest at 8% per year?',
        options: ['2.5 years', '25 years', '0.25 years', '2 years'],
        correctIndex: 0,
        explanation: 'Time = Interest ÷ (Principal × Rate) = 200 ÷ (1000 × 0.08) = 200 ÷ 80 = 2.5 years.',
        misconception: 'Choosing 25 years means dividing 200 by 8 instead of by 80.',
        tier: 'Both',
      },
      {
        id: 'simple-interest-5',
        topicSlug: 'simple-interest',
        question: '£3000 is invested at 2% simple interest for 5 years. What is the total amount?',
        options: ['£3300', '£300', '£3312.24', '£6000'],
        correctIndex: 0,
        explanation: 'Interest = £3000 × 0.02 × 5 = £300. Total = £3000 + £300 = £3300.',
        misconception: 'Choosing £3312.24 means using compound interest instead of simple interest.',
        tier: 'Both',
      },
    ],
  },

  // ─── 26. Reverse Compound Interest ──────────────────────────────────
  {
    topicSlug: 'reverse-compound-interest',
    topicTitle: 'Reverse Compound Interest',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'reverse-compound-interest-1',
        topicSlug: 'reverse-compound-interest',
        question: 'After 2 years at 10% compound interest, an investment is worth £6050. What was the original amount?',
        options: ['£5000', '£4840', '£5500', '£5445'],
        correctIndex: 0,
        explanation: 'Original = £6050 ÷ 1.1² = £6050 ÷ 1.21 = £5000.',
        misconception: 'Choosing £4840 means subtracting 10% twice from £6050 sequentially.',
        tier: 'Higher',
      },
      {
        id: 'reverse-compound-interest-2',
        topicSlug: 'reverse-compound-interest',
        question: 'A car depreciates at 15% per year. After 3 years it is worth £4913.75. What was the original price?',
        options: ['£8000', '£5801.25', '£7500', '£6000'],
        correctIndex: 0,
        explanation: 'Original = £4913.75 ÷ 0.85³ = £4913.75 ÷ 0.614125 = £8000.',
        misconception: 'Choosing £5801.25 means adding 15% of the current value back once.',
        tier: 'Higher',
      },
      {
        id: 'reverse-compound-interest-3',
        topicSlug: 'reverse-compound-interest',
        question: 'After 2 years at 5% compound interest, the amount is £1102.50. What was the principal?',
        options: ['£1000', '£992.38', '£1050', '£1047.62'],
        correctIndex: 0,
        explanation: 'Principal = £1102.50 ÷ 1.05² = £1102.50 ÷ 1.1025 = £1000.',
        misconception: 'Choosing £1050 means only dividing by 1.05 once.',
        tier: 'Higher',
      },
      {
        id: 'reverse-compound-interest-4',
        topicSlug: 'reverse-compound-interest',
        question: 'An item depreciates at 20% per year. After 2 years it is worth £3200. What was the original value?',
        options: ['£5000', '£4000', '£3840', '£4800'],
        correctIndex: 0,
        explanation: 'Original = £3200 ÷ 0.8² = £3200 ÷ 0.64 = £5000.',
        misconception: 'Choosing £4000 means adding 20% of 3200 once then adding again.',
        tier: 'Higher',
      },
      {
        id: 'reverse-compound-interest-5',
        topicSlug: 'reverse-compound-interest',
        question: 'After 3 years at 4% compound interest, an investment is worth £5624.32. What was the original investment?',
        options: ['£5000', '£5400', '£4949.20', '£5200'],
        correctIndex: 0,
        explanation: 'Original = £5624.32 ÷ 1.04³ = £5624.32 ÷ 1.124864 ≈ £5000.',
        misconception: 'Choosing £5400 means subtracting a rough 4% per year from the final amount.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 27. Growth and Decay ───────────────────────────────────────────
  {
    topicSlug: 'growth-and-decay',
    topicTitle: 'Growth and Decay',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'growth-and-decay-1',
        topicSlug: 'growth-and-decay',
        question: 'A population of 5000 bacteria grows by 20% each hour. How many bacteria after 2 hours?',
        options: ['7200', '7000', '6000', '5040'],
        correctIndex: 0,
        explanation: 'After 1 hour: 5000 × 1.2 = 6000. After 2 hours: 6000 × 1.2 = 7200.',
        misconception: 'Choosing 7000 means adding 20% of original (1000) each time (simple growth).',
        tier: 'Higher',
      },
      {
        id: 'growth-and-decay-2',
        topicSlug: 'growth-and-decay',
        question: 'A radioactive substance decays by 50% each day. Starting with 400 g, how much remains after 3 days?',
        options: ['50 g', '200 g', '100 g', '0 g'],
        correctIndex: 0,
        explanation: 'Day 1: 200 g. Day 2: 100 g. Day 3: 50 g.',
        misconception: 'Choosing 100 g means only halving twice instead of three times.',
        tier: 'Both',
      },
      {
        id: 'growth-and-decay-3',
        topicSlug: 'growth-and-decay',
        question: 'A car depreciates from £20,000 at 25% per year. What is it worth after 2 years?',
        options: ['£11,250', '£10,000', '£15,000', '£5000'],
        correctIndex: 0,
        explanation: 'Year 1: £20,000 × 0.75 = £15,000. Year 2: £15,000 × 0.75 = £11,250.',
        misconception: 'Choosing £10,000 means subtracting 25% of original each year.',
        tier: 'Both',
      },
      {
        id: 'growth-and-decay-4',
        topicSlug: 'growth-and-decay',
        question: 'Which formula represents exponential decay?',
        options: ['N = N₀ × (1 − r)ᵗ', 'N = N₀ × (1 + r)ᵗ', 'N = N₀ − rt', 'N = N₀ + rt'],
        correctIndex: 0,
        explanation: 'Decay uses (1 − r) as the multiplier each period.',
        misconception: 'Choosing N = N₀ × (1 + r)ᵗ represents growth, not decay.',
        tier: 'Higher',
      },
      {
        id: 'growth-and-decay-5',
        topicSlug: 'growth-and-decay',
        question: 'A tree grows by 8% each year. It is currently 2 m tall. How tall after 3 years (1 d.p.)?',
        options: ['2.5 m', '2.2 m', '2.4 m', '4.8 m'],
        correctIndex: 0,
        explanation: '2 × 1.08³ = 2 × 1.259712 = 2.519... ≈ 2.5 m.',
        misconception: 'Choosing 2.4 means using simple growth: 2 + 3 × 0.16 = 2.48, rounded to 2.4.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 28. Exponential Growth and Decay ───────────────────────────────
  {
    topicSlug: 'exponential-growth-and-decay',
    topicTitle: 'Exponential Growth and Decay',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'exponential-growth-and-decay-1',
        topicSlug: 'exponential-growth-and-decay',
        question: 'A population P = 2000 × 1.05ᵗ. What is the initial population?',
        options: ['2000', '2100', '1050', '100'],
        correctIndex: 0,
        explanation: 'When t = 0: P = 2000 × 1.05⁰ = 2000 × 1 = 2000.',
        misconception: 'Choosing 2100 means calculating for t = 1 instead of t = 0.',
        tier: 'Higher',
      },
      {
        id: 'exponential-growth-and-decay-2',
        topicSlug: 'exponential-growth-and-decay',
        question: 'The value of a painting is given by V = 500 × 1.12ᵗ. What is the annual growth rate?',
        options: ['12%', '1.12%', '112%', '0.12%'],
        correctIndex: 0,
        explanation: 'The multiplier is 1.12, meaning 12% increase per year.',
        misconception: 'Choosing 1.12% means reading the multiplier directly as a percentage.',
        tier: 'Higher',
      },
      {
        id: 'exponential-growth-and-decay-3',
        topicSlug: 'exponential-growth-and-decay',
        question: 'A substance decays: M = 100 × 0.9ᵗ (t in days). How much remains after 2 days?',
        options: ['81 g', '80 g', '90 g', '10 g'],
        correctIndex: 0,
        explanation: 'M = 100 × 0.9² = 100 × 0.81 = 81 g.',
        misconception: 'Choosing 80 g means subtracting 10% of original each day.',
        tier: 'Higher',
      },
      {
        id: 'exponential-growth-and-decay-4',
        topicSlug: 'exponential-growth-and-decay',
        question: 'Which graph shape represents exponential growth?',
        options: ['A curve that gets steeper and steeper', 'A straight line going up', 'A curve that levels off', 'A straight line going down'],
        correctIndex: 0,
        explanation: 'Exponential growth produces a J-shaped curve that steepens over time.',
        misconception: 'A curve that levels off describes a logarithmic or limited growth curve.',
        tier: 'Higher',
      },
      {
        id: 'exponential-growth-and-decay-5',
        topicSlug: 'exponential-growth-and-decay',
        question: 'N = 800 × 0.75ᵗ models decay. What percentage is lost each time period?',
        options: ['25%', '75%', '0.75%', '80%'],
        correctIndex: 0,
        explanation: '0.75 means 75% remains, so 25% is lost each period.',
        misconception: 'Choosing 75% confuses the remaining fraction with the decay rate.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 29. Rates of Change ────────────────────────────────────────────
  {
    topicSlug: 'rates-of-change',
    topicTitle: 'Rates of Change',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'rates-of-change-1',
        topicSlug: 'rates-of-change',
        question: 'On a graph, the rate of change at a point on a curve is found by:',
        options: ['Drawing a tangent and finding its gradient', 'Finding the area under the curve', 'Reading the y-coordinate', 'Joining two points with a straight line'],
        correctIndex: 0,
        explanation: 'The instantaneous rate of change equals the gradient of the tangent at that point.',
        misconception: 'Finding the area under the curve gives total accumulation, not rate of change.',
        tier: 'Higher',
      },
      {
        id: 'rates-of-change-2',
        topicSlug: 'rates-of-change',
        question: 'A graph shows temperature (°C) against time (min). The gradient at t = 5 is 3. What does this mean?',
        options: ['Temperature is increasing at 3 °C per minute', 'Temperature is 3 °C', 'Temperature decreased by 3 °C', 'It took 3 minutes to reach max temperature'],
        correctIndex: 0,
        explanation: 'Gradient = rate of change. A gradient of 3 means +3 °C per minute.',
        misconception: 'Choosing "Temperature is 3 °C" confuses the gradient with the function value.',
        tier: 'Higher',
      },
      {
        id: 'rates-of-change-3',
        topicSlug: 'rates-of-change',
        question: 'The number of bacteria is modelled by N = 200 + 50t². What is the rate of change at t = 3?',
        options: ['300 bacteria per hour', '650 bacteria per hour', '450 bacteria per hour', '50 bacteria per hour'],
        correctIndex: 0,
        explanation: 'dN/dt = 100t. At t = 3: rate = 100 × 3 = 300 bacteria per hour.',
        misconception: 'Choosing 650 means finding N(3) = 200 + 450 = 650 instead of the derivative.',
        tier: 'Higher',
      },
      {
        id: 'rates-of-change-4',
        topicSlug: 'rates-of-change',
        question: 'A negative gradient on a distance-time graph indicates:',
        options: ['The object is returning to the start', 'The object has stopped', 'The object is speeding up', 'The object is accelerating'],
        correctIndex: 0,
        explanation: 'A negative gradient means distance is decreasing, so the object is moving back.',
        misconception: 'Choosing the object has stopped confuses negative gradient with zero gradient.',
        tier: 'Both',
      },
      {
        id: 'rates-of-change-5',
        topicSlug: 'rates-of-change',
        question: 'Water fills a tank: V = 4t + t² (litres, t in minutes). What is the flow rate at t = 5?',
        options: ['14 litres per minute', '45 litres per minute', '9 litres per minute', '29 litres per minute'],
        correctIndex: 0,
        explanation: 'dV/dt = 4 + 2t. At t = 5: rate = 4 + 10 = 14 litres per minute.',
        misconception: 'Choosing 45 means finding V(5) = 20 + 25 = 45 instead of the derivative.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 30. Scale Drawings and Maps ────────────────────────────────────
  {
    topicSlug: 'scale-drawings-and-maps',
    topicTitle: 'Scale Drawings and Maps',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'scale-drawings-and-maps-1',
        topicSlug: 'scale-drawings-and-maps',
        question: 'A map has a scale of 1:50000. Two towns are 6 cm apart on the map. What is the real distance?',
        options: ['3 km', '300 km', '30 km', '0.3 km'],
        correctIndex: 0,
        explanation: 'Real distance = 6 × 50000 = 300000 cm = 3000 m = 3 km.',
        misconception: 'Choosing 300 km means not converting cm to km correctly.',
        tier: 'Both',
      },
      {
        id: 'scale-drawings-and-maps-2',
        topicSlug: 'scale-drawings-and-maps',
        question: 'A real room is 8 m long. On a scale drawing at 1:200, how long is the room?',
        options: ['4 cm', '40 cm', '0.4 cm', '16 cm'],
        correctIndex: 0,
        explanation: '8 m = 800 cm. Drawing length = 800 ÷ 200 = 4 cm.',
        misconception: 'Choosing 40 cm means dividing by 20 instead of 200.',
        tier: 'Both',
      },
      {
        id: 'scale-drawings-and-maps-3',
        topicSlug: 'scale-drawings-and-maps',
        question: 'On a map, 1 cm represents 5 km. What is this as a ratio?',
        options: ['1:500,000', '1:5000', '1:50,000', '1:5,000,000'],
        correctIndex: 0,
        explanation: '5 km = 500,000 cm. Scale = 1:500,000.',
        misconception: 'Choosing 1:5000 means converting km to m but not to cm.',
        tier: 'Both',
      },
      {
        id: 'scale-drawings-and-maps-4',
        topicSlug: 'scale-drawings-and-maps',
        question: 'A model car is built at a scale of 1:40. The real car is 4 m long. How long is the model?',
        options: ['10 cm', '100 cm', '1 cm', '160 cm'],
        correctIndex: 0,
        explanation: '4 m = 400 cm. Model = 400 ÷ 40 = 10 cm.',
        misconception: 'Choosing 100 cm means dividing 4 m by 4 instead of 40.',
        tier: 'Both',
      },
      {
        id: 'scale-drawings-and-maps-5',
        topicSlug: 'scale-drawings-and-maps',
        question: 'A garden is drawn at scale 1:100. On the drawing it is 12 cm by 8 cm. What is the real area?',
        options: ['96 m²', '9600 m²', '9.6 m²', '960 m²'],
        correctIndex: 0,
        explanation: 'Real length = 12 × 100 = 1200 cm = 12 m. Real width = 8 × 100 = 800 cm = 8 m. Area = 12 × 8 = 96 m².',
        misconception: 'Choosing 9600 m² means multiplying the area by 100 instead of multiplying each dimension by 100.',
        tier: 'Both',
      },
    ],
  },

  // ─── 31. Unit Conversions ───────────────────────────────────────────
  {
    topicSlug: 'unit-conversions',
    topicTitle: 'Unit Conversions',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'unit-conversions-1',
        topicSlug: 'unit-conversions',
        question: 'Convert 3.5 km to metres.',
        options: ['3500 m', '350 m', '35 m', '35000 m'],
        correctIndex: 0,
        explanation: '1 km = 1000 m. 3.5 × 1000 = 3500 m.',
        misconception: 'Choosing 350 m means multiplying by 100 instead of 1000.',
        tier: 'Both',
      },
      {
        id: 'unit-conversions-2',
        topicSlug: 'unit-conversions',
        question: 'Convert 4500 g to kilograms.',
        options: ['4.5 kg', '45 kg', '0.45 kg', '450 kg'],
        correctIndex: 0,
        explanation: '1 kg = 1000 g. 4500 ÷ 1000 = 4.5 kg.',
        misconception: 'Choosing 45 kg means dividing by 100 instead of 1000.',
        tier: 'Both',
      },
      {
        id: 'unit-conversions-3',
        topicSlug: 'unit-conversions',
        question: 'Convert 2 hours 15 minutes to minutes.',
        options: ['135 minutes', '215 minutes', '225 minutes', '115 minutes'],
        correctIndex: 0,
        explanation: '2 hours = 120 minutes. 120 + 15 = 135 minutes.',
        misconception: 'Choosing 215 means writing 2 and 15 together instead of converting hours to minutes.',
        tier: 'Both',
      },
      {
        id: 'unit-conversions-4',
        topicSlug: 'unit-conversions',
        question: 'Convert 0.75 litres to millilitres.',
        options: ['750 ml', '75 ml', '7.5 ml', '7500 ml'],
        correctIndex: 0,
        explanation: '1 litre = 1000 ml. 0.75 × 1000 = 750 ml.',
        misconception: 'Choosing 75 ml means multiplying by 100 instead of 1000.',
        tier: 'Both',
      },
      {
        id: 'unit-conversions-5',
        topicSlug: 'unit-conversions',
        question: 'Convert 250 cm to metres.',
        options: ['2.5 m', '25 m', '0.25 m', '2500 m'],
        correctIndex: 0,
        explanation: '1 m = 100 cm. 250 ÷ 100 = 2.5 m.',
        misconception: 'Choosing 25 m means dividing by 10 instead of 100.',
        tier: 'Both',
      },
    ],
  },

  // ─── 32. Metric and Imperial Conversions ────────────────────────────
  {
    topicSlug: 'metric-and-imperial-conversions',
    topicTitle: 'Metric and Imperial Conversions',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'metric-and-imperial-conversions-1',
        topicSlug: 'metric-and-imperial-conversions',
        question: '1 inch ≈ 2.5 cm. Convert 12 inches to centimetres.',
        options: ['30 cm', '14.5 cm', '4.8 cm', '120 cm'],
        correctIndex: 0,
        explanation: '12 × 2.5 = 30 cm.',
        misconception: 'Choosing 4.8 means dividing 12 by 2.5 instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'metric-and-imperial-conversions-2',
        topicSlug: 'metric-and-imperial-conversions',
        question: '5 miles ≈ 8 km. Convert 20 miles to km.',
        options: ['32 km', '12.5 km', '160 km', '25 km'],
        correctIndex: 0,
        explanation: 'Scale factor = 20 ÷ 5 = 4. 8 × 4 = 32 km.',
        misconception: 'Choosing 12.5 means dividing 20 by 1.6 incorrectly.',
        tier: 'Both',
      },
      {
        id: 'metric-and-imperial-conversions-3',
        topicSlug: 'metric-and-imperial-conversions',
        question: '1 kg ≈ 2.2 lbs. Convert 5 kg to pounds.',
        options: ['11 lbs', '7.2 lbs', '2.27 lbs', '10 lbs'],
        correctIndex: 0,
        explanation: '5 × 2.2 = 11 lbs.',
        misconception: 'Choosing 2.27 means dividing 5 by 2.2 instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'metric-and-imperial-conversions-4',
        topicSlug: 'metric-and-imperial-conversions',
        question: '1 gallon ≈ 4.5 litres. How many litres in 3 gallons?',
        options: ['13.5 litres', '7.5 litres', '1.5 litres', '4.5 litres'],
        correctIndex: 0,
        explanation: '3 × 4.5 = 13.5 litres.',
        misconception: 'Choosing 7.5 means adding 3 to 4.5 instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'metric-and-imperial-conversions-5',
        topicSlug: 'metric-and-imperial-conversions',
        question: '5 miles ≈ 8 km. Convert 40 km to miles.',
        options: ['25 miles', '64 miles', '20 miles', '48 miles'],
        correctIndex: 0,
        explanation: 'Scale factor = 40 ÷ 8 = 5. 5 × 5 = 25 miles.',
        misconception: 'Choosing 64 means multiplying 40 × 1.6 (converting miles to km direction).',
        tier: 'Both',
      },
    ],
  },

  // ─── 33. Converting Area and Volume Units ───────────────────────────
  {
    topicSlug: 'converting-area-and-volume-units',
    topicTitle: 'Converting Area and Volume Units',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'converting-area-and-volume-units-1',
        topicSlug: 'converting-area-and-volume-units',
        question: 'Convert 3 m² to cm².',
        options: ['30,000 cm²', '300 cm²', '3000 cm²', '30 cm²'],
        correctIndex: 0,
        explanation: '1 m² = 10,000 cm² (100 × 100). 3 × 10,000 = 30,000 cm².',
        misconception: 'Choosing 300 cm² means multiplying by 100 instead of 10,000.',
        tier: 'Higher',
      },
      {
        id: 'converting-area-and-volume-units-2',
        topicSlug: 'converting-area-and-volume-units',
        question: 'Convert 5 cm³ to mm³.',
        options: ['5000 mm³', '500 mm³', '50 mm³', '50,000 mm³'],
        correctIndex: 0,
        explanation: '1 cm³ = 1000 mm³ (10 × 10 × 10). 5 × 1000 = 5000 mm³.',
        misconception: 'Choosing 50 means multiplying by 10 instead of 1000.',
        tier: 'Higher',
      },
      {
        id: 'converting-area-and-volume-units-3',
        topicSlug: 'converting-area-and-volume-units',
        question: 'Convert 2,000,000 cm³ to m³.',
        options: ['2 m³', '20 m³', '200 m³', '2000 m³'],
        correctIndex: 0,
        explanation: '1 m³ = 1,000,000 cm³. 2,000,000 ÷ 1,000,000 = 2 m³.',
        misconception: 'Choosing 2000 means dividing by 1000 instead of 1,000,000.',
        tier: 'Higher',
      },
      {
        id: 'converting-area-and-volume-units-4',
        topicSlug: 'converting-area-and-volume-units',
        question: 'How many cm² are in 1 m²?',
        options: ['10,000', '100', '1000', '1,000,000'],
        correctIndex: 0,
        explanation: '1 m = 100 cm. 1 m² = 100 × 100 = 10,000 cm².',
        misconception: 'Choosing 100 means using the linear conversion factor instead of squaring it.',
        tier: 'Both',
      },
      {
        id: 'converting-area-and-volume-units-5',
        topicSlug: 'converting-area-and-volume-units',
        question: 'A field has area 50,000 m². What is this in km²?',
        options: ['0.05 km²', '50 km²', '5 km²', '0.5 km²'],
        correctIndex: 0,
        explanation: '1 km² = 1,000,000 m². 50,000 ÷ 1,000,000 = 0.05 km².',
        misconception: 'Choosing 50 means dividing by 1000 instead of 1,000,000.',
        tier: 'Higher',
      },
    ],
  },

  // ─── 34. Best Buy Problems ──────────────────────────────────────────
  {
    topicSlug: 'best-buy-problems',
    topicTitle: 'Best Buy Problems',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'best-buy-problems-1',
        topicSlug: 'best-buy-problems',
        question: 'Pack A: 6 cans for £2.40. Pack B: 10 cans for £3.50. Which is better value?',
        options: ['Pack B', 'Pack A', 'They are the same', 'Cannot tell'],
        correctIndex: 0,
        explanation: 'A: £2.40 ÷ 6 = 40p per can. B: £3.50 ÷ 10 = 35p per can. Pack B is cheaper per can.',
        misconception: 'Choosing Pack A means assuming fewer items always means better value.',
        tier: 'Both',
      },
      {
        id: 'best-buy-problems-2',
        topicSlug: 'best-buy-problems',
        question: 'Soap: 3 bars for £1.80 or 5 bars for £2.75. What is the cost per bar for the 5-pack?',
        options: ['55p', '60p', '27.5p', '92p'],
        correctIndex: 0,
        explanation: '£2.75 ÷ 5 = £0.55 = 55p per bar.',
        misconception: 'Choosing 60p means finding the cost per bar for the 3-pack instead.',
        tier: 'Both',
      },
      {
        id: 'best-buy-problems-3',
        topicSlug: 'best-buy-problems',
        question: 'Orange juice: 1 litre for £1.20 or 1.5 litres for £1.65. Which is better value?',
        options: ['1.5 litre bottle', '1 litre bottle', 'They are the same', 'Cannot tell'],
        correctIndex: 0,
        explanation: '1L: £1.20/L. 1.5L: £1.65 ÷ 1.5 = £1.10/L. The 1.5L bottle is better value.',
        misconception: 'Choosing the 1L bottle means comparing total prices instead of unit prices.',
        tier: 'Both',
      },
      {
        id: 'best-buy-problems-4',
        topicSlug: 'best-buy-problems',
        question: 'Shop A: 400 g of cheese for £3.20. Shop B: 500 g of cheese for £3.75. Which shop gives better value?',
        options: ['Shop B', 'Shop A', 'They are the same', 'Cannot tell'],
        correctIndex: 0,
        explanation: 'A: £3.20 ÷ 400 = 0.8p/g. B: £3.75 ÷ 500 = 0.75p/g. Shop B is cheaper per gram.',
        misconception: 'Choosing Shop A means comparing total price only.',
        tier: 'Both',
      },
      {
        id: 'best-buy-problems-5',
        topicSlug: 'best-buy-problems',
        question: 'Washing powder: 2 kg for £4.00 or 3 kg for £5.40. How much do you save per kg buying the bigger box?',
        options: ['20p per kg', '£1.40 per kg', '40p per kg', '10p per kg'],
        correctIndex: 0,
        explanation: 'Small: £4 ÷ 2 = £2/kg. Large: £5.40 ÷ 3 = £1.80/kg. Saving = £2 − £1.80 = 20p/kg.',
        misconception: 'Choosing £1.40 means subtracting total prices instead of unit prices.',
        tier: 'Both',
      },
    ],
  },

  // ─── 35. Exchange Rate Problems ─────────────────────────────────────
  {
    topicSlug: 'exchange-rate-problems',
    topicTitle: 'Exchange Rate Problems',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'exchange-rate-problems-1',
        topicSlug: 'exchange-rate-problems',
        question: '£1 = €1.20. Convert £250 to euros.',
        options: ['€300', '€208.33', '€251.20', '€3000'],
        correctIndex: 0,
        explanation: '£250 × 1.20 = €300.',
        misconception: 'Choosing €208.33 means dividing by 1.20 instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'exchange-rate-problems-2',
        topicSlug: 'exchange-rate-problems',
        question: '£1 = $1.30. Convert $520 to pounds.',
        options: ['£400', '£676', '£518.70', '£521.30'],
        correctIndex: 0,
        explanation: '$520 ÷ 1.30 = £400.',
        misconception: 'Choosing £676 means multiplying by 1.30 instead of dividing.',
        tier: 'Both',
      },
      {
        id: 'exchange-rate-problems-3',
        topicSlug: 'exchange-rate-problems',
        question: '£1 = ¥150. How many yen do you get for £40?',
        options: ['¥6000', '¥3.75', '¥190', '¥110'],
        correctIndex: 0,
        explanation: '£40 × 150 = ¥6000.',
        misconception: 'Choosing ¥3.75 means dividing 150 by 40 instead of multiplying.',
        tier: 'Both',
      },
      {
        id: 'exchange-rate-problems-4',
        topicSlug: 'exchange-rate-problems',
        question: '£1 = €1.15. A meal costs €57.50 in France. What is this in pounds?',
        options: ['£50', '£66.13', '£56.35', '£58.65'],
        correctIndex: 0,
        explanation: '€57.50 ÷ 1.15 = £50.',
        misconception: 'Choosing £66.13 means multiplying by 1.15 instead of dividing.',
        tier: 'Both',
      },
      {
        id: 'exchange-rate-problems-5',
        topicSlug: 'exchange-rate-problems',
        question: 'Emma changes £300 to dollars at £1 = $1.40. She spends $350. She converts the rest back. How many pounds does she get back?',
        options: ['£50', '£70', '£107.14', '£250'],
        correctIndex: 0,
        explanation: 'She gets $420. Spends $350. Left: $70. Convert back: $70 ÷ 1.40 = £50.',
        misconception: 'Choosing £70 means not converting the remaining dollars back to pounds.',
        tier: 'Both',
      },
    ],
  },

  // ─── 36. Recipe and Scaling Problems ────────────────────────────────
  {
    topicSlug: 'recipe-and-scaling-problems',
    topicTitle: 'Recipe and Scaling Problems',
    strand: 'Ratio, Proportion & Rates of Change',
    questions: [
      {
        id: 'recipe-and-scaling-problems-1',
        topicSlug: 'recipe-and-scaling-problems',
        question: 'A recipe for 4 people uses 200 g of pasta. How much pasta is needed for 6 people?',
        options: ['300 g', '1200 g', '150 g', '250 g'],
        correctIndex: 0,
        explanation: 'Per person = 200 ÷ 4 = 50 g. For 6 = 6 × 50 = 300 g.',
        misconception: 'Choosing 1200 means multiplying 200 × 6 without adjusting for servings.',
        tier: 'Both',
      },
      {
        id: 'recipe-and-scaling-problems-2',
        topicSlug: 'recipe-and-scaling-problems',
        question: 'A recipe for 8 cakes uses 240 g of sugar. How much sugar for 12 cakes?',
        options: ['360 g', '160 g', '480 g', '2880 g'],
        correctIndex: 0,
        explanation: 'Per cake = 240 ÷ 8 = 30 g. For 12 cakes = 12 × 30 = 360 g.',
        misconception: 'Choosing 480 means doubling 240 instead of scaling correctly.',
        tier: 'Both',
      },
      {
        id: 'recipe-and-scaling-problems-3',
        topicSlug: 'recipe-and-scaling-problems',
        question: 'A recipe for 10 serves uses 500 ml of cream. Jake has 350 ml. How many can he serve?',
        options: ['7', '5', '3', '10'],
        correctIndex: 0,
        explanation: 'Per person = 500 ÷ 10 = 50 ml. Jake can serve 350 ÷ 50 = 7 people.',
        misconception: 'Choosing 5 means dividing 350 by something other than 50.',
        tier: 'Both',
      },
      {
        id: 'recipe-and-scaling-problems-4',
        topicSlug: 'recipe-and-scaling-problems',
        question: 'A recipe for 5 people: 300 g flour, 4 eggs, 250 ml milk. How many eggs for 15 people?',
        options: ['12', '20', '9', '60'],
        correctIndex: 0,
        explanation: 'Scale factor = 15 ÷ 5 = 3. Eggs = 4 × 3 = 12.',
        misconception: 'Choosing 20 means multiplying 4 × 5 instead of 4 × 3.',
        tier: 'Both',
      },
      {
        id: 'recipe-and-scaling-problems-5',
        topicSlug: 'recipe-and-scaling-problems',
        question: 'A recipe for 6 needs 150 g butter. How much butter for 9 people?',
        options: ['225 g', '900 g', '250 g', '100 g'],
        correctIndex: 0,
        explanation: 'Scale factor = 9 ÷ 6 = 1.5. Butter = 150 × 1.5 = 225 g.',
        misconception: 'Choosing 900 means multiplying 150 × 6 instead of using the scale factor.',
        tier: 'Both',
      },
    ],
  },
]
